### PR TITLE
Remove httpsTrigger from field mask to stop overwrite of securityLevel

### LINKED ISSUE #4171: HTTPS trigger securityLevel is overwritten on function re-deploy
### [REQUIRED] Environment info

**firebase-tools:** 10.2.0

**Platform:** macOS

### [REQUIRED] Test case

Using the [getting started with Firebase functions](https://firebase.google.com/docs/functions/get-started) article deploy and redeploy a function. The Require HTTPs flag is removed when the function is updated.

### [REQUIRED] Steps to reproduce

1. Create a GCP project in the Cloud Console
2. Follow steps 1-3 from the article
3. Edit `index.js` to include the `helloWorld` function
```
const functions = require("firebase-functions");
exports.helloWorld = functions.https.onRequest((request, response) => {
  functions.logger.info("Hello logs!", {structuredData: true});
  response.send("Hello from Firebase!");
});
```
4. Deploy the function `firebase deploy --project PROJECT_ID --only functions:helloWorld`
5. Go back to the console, click edit. The Function has the `Require HTTPS` flag enabled
6. Execute the `deploy` command again
7. Go back to Cloud Console, edit the function 
8. The function no longer has the `Require HTTPS` flag

### [REQUIRED] Expected behavior

The function retains the `Require HTTPS` flag

### [REQUIRED] Actual behavior

The `Require HTTPS` flag is removed

### Additional information

@inlined enforced HTTPS in newly created functions in the [createV1Function](https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/release/fabricator.ts#L212-L214) which enables the flag (awesome)

However, when we re-deploy, the [updateV1Function](https://github.com/firebase/firebase-tools/blob/master/src/deploy/functions/release/fabricator.ts#L325) sends the `updateMask` which contains the `httpsTrigger` field but the trigger is an empty object. 

Either `httpsTrigger` should not be sent as part of the `updateMask` properties or enforce HTTPs in the `updateV1Function` as well.

image

### PR DESCRIPTION
**Pull request by colerogers**
Fixes #4171 by removing `httpsTrigger` from the field mask array on updates.

This is a patch bug fix that does not break currently deployed https functions. @inlined suggested changing `proto.fieldMasks` to ignore empty objects, but empty objects are needed for protobuf.Empty. When we introduce a breaking change, then we should either set the `securityLevel` in Fabricator's `updateV1Function` or directly in `functionFromEndpoint`.

### CODE REVIEW

File: src/gcp/cloudfunctions.ts [hunk 1]
```diff
@@ -356,11 +356,16 @@ export async function updateFunction(
   cloudFunction: Omit<CloudFunction, OutputOnlyFields>
 ): Promise<Operation> {
   const endpoint = `/${cloudFunction.name}`;
+  // TODO(colerogers): remove cloudFunctionWithoutHttpsTrigger and set securityLevel in functionFromEndpoint during a breaking change release
+  const cloudFunctionWithoutHttpsTrigger = { ...cloudFunction };
+  delete cloudFunctionWithoutHttpsTrigger.httpsTrigger;
```
Comment (taeold) [inline src/gcp/cloudfunctions.ts:361]: nit* can you add a comment on why we are clearing this field (e.g. link to the issue)

**Review by taeold — APPROVED** [review]

File: src/gcp/cloudfunctions.ts (hunk 1 above)
Comment (inlined) [inline src/gcp/cloudfunctions.ts:361]: This can work for now, but it won't scale if we have additional fields added to httpsTrigger. Is `prepare.ts:inferDetailsFromExisting` a good candidate here?

**Review by inlined — COMMENTED** [review]
LGTM with Daniel's request for a comment.

File: src/gcp/cloudfunctions.ts (hunk 1 above)
Comment (colerogers) [reply src/gcp/cloudfunctions.ts]: Changed the implementation to set `securityLevel` in `backend.Endpoint`. I removed this delete field code

Comment (colerogers) [reply src/gcp/cloudfunctions.ts]: Latest commit we set securityLevel in `backend.Endpoint` and use `prepare.ts:inferDetailsFromExisting` to copy the current value.

File: src/deploy/functions/backend.ts [hunk 2]
```diff
@@ -255,6 +257,9 @@ export type Endpoint = TargetIds &
     // on GCFv2 always
     uri?: string;
     sourceUploadUrl?: string;
+    // GCFv1 can be http or https and
+    // GCFv2 is always https
+    securityLevel?: SecurityLevel;
```
Comment (taeold) [inline src/deploy/functions/backend.ts:262]: Hmm I honestly liked the old solution better. I'm a little concerned that `securityLevel` is only relevant to GCFv1 HTTP triggers yet we are proposing here that it's part of any Endpoint.

Should we at lesast annotate this as a temporary hack? IIUC, the way forward is to have a breaking change where we always set HTTP function to HTTPS-only.

Comment (colerogers) [reply src/deploy/functions/backend.ts:262]: Would dumping it in `backend.Endpoint.httpsTrigger` fit a bit better? I'll also make a comment about this being temporary and link to the Issue.

Looking at the old solution, deleting the entire `httpsTrigger` object doesn't really match with the rest of the deployment process. This way we're at least utilizing the built-in flow, leveraging `inferDetailsFromExisting`, and actually creating the exact CloudFunction object that should be deployed.

Comment (taeold) [reply src/deploy/functions/backend.ts]: One thing I liked about the old way is that it is egregious (and therefore obvious) that it's an hack! 

Regardless, if this is something we intend to clean up in the future, I don't think this is that harmful.

File: src/deploy/functions/backend.ts [hunk 3]
```diff
@@ -204,6 +204,8 @@ export interface ServiceConfiguration {
 
 export type FunctionsPlatform = "gcfv1" | "gcfv2";
 
+export type SecurityLevel = "SECURE_ALWAYS" | "SECURE_OPTIONAL";
```
Comment (taeold) [inline src/deploy/functions/backend.ts:207]: nit* you might want to use type definition define din cloudfunctions.ts instead.

**Review by taeold — APPROVED** [review]
