### PR TITLE
dynamically import Vite

### LINKED ISSUE #6652: The CJS build of Vite's Node API is deprecated.
### [REQUIRED] Environment info

**firebase-tools: 13.0.2**

**Platform: Ubuntu**

### [REQUIRED] Test case

  $> VITE (VUE3) start app , config VueFire with  auth and hosting
  $> firebase experiments:enabled webframeworks
  $> firebase init hosting auth

### [REQUIRED] Steps to reproduce

  $> firebase emulators: start => ERRORS BUT
  $> firebase deploy => deploys OK with folowinf MSG (from Vite 5.0)
      "The CJS build of Vite's Node API is deprecated. See 
              https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
       for more details."

### [REQUIRED] Expected behavior

  No more CJS (node require) in firebase code

### [REQUIRED] Actual behavior

      "The CJS build of Vite's Node API is deprecated. See 
              https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
       for more details."

** MY firebase.json file;** see *rewrites* following Vite instructions for FireBase Deploy.
```firebase.json
{
  "hosting": {
    "source": ".",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "us-east1"
    },
    "site": "g2ato-v3p1-fb",
    "rewrites": [{
      "source": "**",
      "destination": "/index.html"
    }],
    "redirects": [],
    "headers": [{
        "source": "**/*.[jt]s",
        "headers": [{
            "key": "Set-Cookie",
            "value": "__FIREBASE_DEFAULTS__=xxx...;"
     }],
    "cleanUrls": true,
    "webFramework": "vite"
  },
  "emulators": {
    "hosting": {
      "port": 5000
    },
    "singleProjectMode": true
  }
}
```

### PR DESCRIPTION
**Pull request by leoortizz**
### Description

closes #6652

### CODE REVIEW

File: src/frameworks/utils.ts [hunk 1]
```diff
@@ -345,7 +345,19 @@ export function relativeRequire(dir: string, mod: string) {
     // eslint-disable-next-line @typescript-eslint/ban-ts-comment
     // @ts-ignore prevent VSCE webpack from erroring on non_webpack_require
     const path = requireFunc.resolve(mod, { paths: [dir] });
-    if (extname(path) === ".mjs") {
+
+    let packageJson: PackageJson | undefined;
+    const isEsm =
+      extname(path) === ".mjs" ||
+      (packageJson = readJsonSync(join(dirname(path), "package.json"), { throws: false }))?.type ===
```
Comment (leoortizz) [inline src/frameworks/utils.ts:352]: @jamesdaniels would love to use the async readJson here but would need to handle the promise in all calls to relativeRequire, WDYT?

Comment (jamesdaniels) [reply src/frameworks/utils.ts:352]: i'm ok with us converting this to be async

**Review by jamesdaniels — APPROVED** [review]
Add changelog, otherwise LGTM
