### PR TITLE
Fix error message for requireAuth

### LINKED ISSUE #2114: firebase init Error: An unexpected error has occurred.
Hi
I ran
npm install -g firebase-tools@latest
C:\>firebase init
Error: An unexpected error has occurred.

firebase --open-sesame emulatorgui
firebase emulators:start 

I tried writing the firebase.json file to c:\ but I dont have write access to that as per company guidelines, but admin access all else.
So used C:\temp\ that has the json security api keys in it
All I wanted to do is see the what was at http://localhost:8080/
Somehow I was expecting to see a copy of  "https://console.firebase.google.com/project/" not just 'OK'
It would be nice if it told me what file was missing, what is "default credentials" CRUD access to a folder a project a node?
Is there a youtube vid  for this?

```
C:\>firebase --debug init
[2020-04-08T15:35:36.718Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2020-04-08T15:35:36.737Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (C:\Users\dthompson\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:160:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async GoogleAuth.getClient (C:\Users\dthompson\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:502:17)
    at async GoogleAuth.getAccessToken (C:\Users\dthompson\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\google-auth-library\build\src\auth\googleauth.js:524:24)

Error: An unexpected error has occurred.
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2114

Before:
Screen Shot 2020-04-24 at 1 22 33 PM

After:
Screen Shot 2020-04-24 at 1 22 26 PM

### Scenarios Tested

Logged out fully:
```
firebase logout
gcloud auth application-default revoke
```

Then ran:
```
firebase init hosting
```

### Sample Commands

N/A

### CODE REVIEW

File: src/requireAuth.ts [hunk 1]
```diff
@@ -57,7 +57,12 @@ export async function requireAuth(options: any): Promise<void> {
   } else if (user) {
     logger.debug("> authorizing via signed-in user");
   } else {
-    return autoAuth(options, options.authScopes);
+    return autoAuth(options, options.authScopes).catch((e) => {
```
Comment (bkendall) [inline src/requireAuth.ts:60]: my preference would be to do:

```typescript
try {
  await autoAuth();
} catch (e) {
  throw new FirebaseError();
}
```

But I think that's all-in-all a pretty small detail.
