### PR TITLE
Integrate functions:shell with the new emulator

### LINKED ISSUE #1243: functions:shell not working
### [REQUIRED] Environment info

firebase-tools: 6.9.0

Platform: Linux

### [REQUIRED] Test case

works on default project from `firebase init functions` 

### [REQUIRED] Steps to reproduce

same as mentioned in docs, for explantion i'm using `firebase functions:shell`
### [REQUIRED] Expected behavior

```
i  functions: Preparing to emulate functions.
✔  functions: helloWorld
firebase > helloWorld
{ [Function]
  get: [Function],
  head: [Function],
  post: [Function],
  put: [Function],
  patch: [Function],
  del: [Function],
  delete: [Function],
  cookie: [Function],
  jar: [Function],
  defaults: [Function] }
```

### [REQUIRED] Actual behavior
```
✔  functions: Emulator running at http://localhost:5001
firebase > helloWorld
ReferenceError: helloWorld is not defined
```

### Note
this works on 6.8.0 though
new version(6.9.0) does not display url too `http://localhost:5000/fresh-con/us-central1/helloWorld`
even default port is changed to 5001

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #1243 

TODO

- [x] Get the `context` object fully populated
- [x] Clean up logging
- [x] Support second "options" param for RTDB and Firestore
- [x] Non-Firestore background functions
- [x] Support Storage, Auth, and Crashlytics

Currently using this to test:
```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');

admin.initializeApp();

// httpFn()
exports.httpFn = functions.https.onRequest((request, response) => {
    console.log("httpLog");
    response.send("Hello from Firebase!");
});

// callableFn({'foo': 'bar'})
exports.callableFn = functions.https.onCall((data, ctx) => {
    return {
        data: {
            hello: 'World!',
            input: data
        }
    };
});

// dbCreateFn('new_data')
exports.dbCreateFn = functions.database.ref('/foo/bar').onCreate((change, ctx) => {
    console.log("dbCreateFn");
    console.log("ctx", JSON.stringify(ctx));
    console.log("change", JSON.stringify(change));
    return true;
});

// dbWriteFn({before: 'old_data', after: 'new_data' })
exports.dbWriteFn = functions.database.ref('/foo/bar').onWrite((change, ctx) => {
    console.log("dbWriteFn");
    console.log("oldvalue", JSON.stringify(change.before.val()));
    console.log("newvalue", JSON.stringify(change.after.val()));
    return true;
});

// dbOptionsFn('data', { auth: { uid: 'abc'}, params: { doc: 'a' }})
exports.dbOptionsFn = functions.database.ref('/foo/{doc}').onWrite((change, ctx)  => {
    console.log("dbOptionsFn");
    console.log("context", JSON.stringify(ctx));
    return true;
});

// firestoreCreateFn({ 'data': 'foo' })
exports.firestoreCreateFn = functions.firestore.document('/foo/bar').onCreate((snap, ctx) => {
    console.log("firestoreCreateFn");
    console.log("snap", JSON.stringify(snap.data()));
    return true;
});

// firestoreWriteFn({before: {foo: 'old'}, after: {foo: 'new'} })
exports.firestoreWriteFn = functions.firestore.document('/foo/bar').onWrite((change, ctx) => {
    console.log("firestoreWriteFn");
    console.log("oldvalue", JSON.stringify(change.before.data()));
    console.log("newvalue", JSON.stringify(change.after.data()));
    return true;
});

// firestoreOptionsFn({ hello: "world" }, { params: { doc: "a" } })
exports.firestoreOptionsFn = functions.firestore.document('/some/{doc}').onCreate((change, ctx) => {
    console.log('firestoreOptionsFn');
    console.log("context", JSON.stringify(ctx));
    return true;
});

// pubsubFn({data: new Buffer('{"hello":"world"}'), attributes: {foo: 'bar'}})
exports.pubsubFn = functions.pubsub.topic("test").onPublish((msg, ctx) => {
    console.log("msg", msg.data);
    return true;
});

// analyticsFn({
//     eventDim: [{
//         params: { foo: 'bar' },
//         name: 'event_name',
//         timestampMicros: Date.now() * 1000,
//         previousTimestampMicros: Date.now() * 1000,
//         date: '20170930'
//     }]
// });
exports.analyticsFn = functions.analytics.event("event").onLog((event, ctx) => {
    console.log("analyticsFn");
    console.log(event);
    return true;
});

// httpToDbFn()
exports.httpToDbFn = functions.https.onRequest(async (request, response) => {
    try {
        await admin.database().ref('write-test').set({
            date: new Date()
        });
        response.status(200).send('Wrote data!\n');
    } catch (e) {
        response.status(500).send(e);
    }
});

// httpToFirestoreFn()
exports.httpToFirestoreFn = functions.https.onRequest(async (request, response) => {
    await admin.firestore().collection("foo").doc("bar").set({
        hello: "world"
    });

    response.status(200).send("Wrote!")
});
```

### CODE REVIEW

**Comment by Cdik** [comment]
I guess this has been fixed with [6.9.1](https://github.com/firebase/firebase-tools/releases/tag/v6.9.1)

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -500,6 +547,116 @@ You can probably fix this by running "npm install ${
...
   }
+
+  getTriggers(): EmulatedTriggerDefinition[] {
+    return this.triggers;
+  }
+
+  /**
+   * Returns the path to a "node" executable to use.
+   */
+  async askInstallNodeVersion(cwd: string): Promise<string> {
```
Comment (samtstern) [inline src/emulator/functionsEmulator.ts]: This method was not changed, it was just moved to be inside the `FunctionsEmulator` class rather than floating.

**Comment by abeisgoat** [comment]
Some general feedback...

1. Historically the shell will print out the names of all loaded functions, we don't need the format to match exactly, but we should print something.
2. We don't surface any errors from the user code, we should make sure that we bubble up errors.
3. I'm struggling to get any non HTTP, Callable, or Firestore triggers to invoke, the methods exist, but for example `dbFn` just hands.
4. Our env isn't providing `FIREBASE_CONFIG` correctly, I've patched this in #1269

**Comment by samtstern** [comment]
@abeisgoat working on a few things related to https://github.com/firebase/firebase-tools/issues/1288 but your review would still be really helpful at this point.  Should work 99%.

File: package.json [hunk 2]
```diff
@@ -100,7 +100,7 @@
     "tmp": "0.0.33",
     "universal-analytics": "^0.4.16",
     "update-notifier": "^2.5.0",
-    "uuid": "^3.0.0",
+    "uuid": "^3.3.2",
```
Comment (abeisgoat) [inline package.json]: This bump intentional?

File: src/emulator/emulatorLogger.ts [hunk 3]
```diff
@@ -0,0 +1,66 @@
+import * as utils from "../utils";
+import * as logger from "../logger";
+
+type LogType = "DEBUG" | "INFO" | "USER" | "BULLET" | "WARN" | "SUCCESS";
```
Comment (abeisgoat) [inline src/emulator/emulatorLogger.ts]: Can we add some info about when to use a INFO vs. a BULLET?

File: src/emulator/events/types.ts [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+ * The types in this file are stolen from the firebase-functions SDK. They are not subject
+ * to change because they are TS interpretations of protobuf wire formats already used in
+ * productiton services.
+ */
+
+/**
+ * Wire formal for v1beta1 EventFlow.
+ * Used by Firestore and some other services.
+ */
+export interface LegacyEvent {
```
Comment (abeisgoat) [inline src/emulator/events/types.ts]: This type can be imported from [here](https://github.com/firebase/firebase-functions/blob/68a669183f61002c269781b3957bf9b74f10bd87/src/cloud-functions.ts#L34) as long as we reference `firebase-functions` as type only (no code calls) and have it as a dev dep which I think we already do.

File: src/emulator/events/types.ts [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+  timestamp?: string;
+  params?: { [option: string]: any };
+  auth?: AuthMode;
+}
+
+/**
+ * Wire format for v1beta2 Eventflow (and likely v1).
+ * Used by PubSub, RTDB, and some other services.
+ */
+export interface Event {
```
Comment (abeisgoat) [inline src/emulator/events/types.ts]: Same as above, let's dedupe if we can from [here](https://github.com/firebase/firebase-functions/blob/68a669183f61002c269781b3957bf9b74f10bd87/src/cloud-functions.ts#L47)

File: src/emulator/events/types.ts [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+    resource: Resource;
+  };
+  data: any;
+}
+
+/**
+ * Resource is a standard format for defining a resource (google.rpc.context.AttributeContext.Resource).
+ * In Cloud Functions, it is the resource that triggered the function - such as a storage bucket.
+ */
+export interface Resource {
```
Comment (abeisgoat) [inline src/emulator/events/types.ts]: Same [here](https://github.com/firebase/firebase-functions/blob/68a669183f61002c269781b3957bf9b74f10bd87/src/cloud-functions.ts#L160)

File: src/emulator/events/types.ts [hunk 7]
```diff
@@ -0,0 +1,101 @@
...
+  service: string;
+  name: string;
+  type?: string;
+  labels?: { [tag: string]: string };
+}
+
+/**
+ * Legacy AuthMode format.
+ */
+export interface AuthMode {
```
Comment (abeisgoat) [inline src/emulator/events/types.ts]: Same [here](https://github.com/firebase/firebase-functions/blob/68a669183f61002c269781b3957bf9b74f10bd87/src/apps.ts#L49)

File: package.json (hunk 2 above)
Comment (samtstern) [reply package.json]: Nope, fixing.

File: src/emulator/events/types.ts [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+    return {
+      eventId: event.context.eventId,
+      timestamp: event.context.timestamp,
+      eventType: event.context.eventType,
+      resource: event.context.resource.name,
+      data: event.data,
+    };
+  }
+
+  private static hasFields(obj: any, fields: string[]): boolean {
```
Comment (abeisgoat) [inline src/emulator/events/types.ts]: May be able to use `_.has` here

File: src/emulator/functionsEmulatorRuntime.ts [hunk 9]
```diff
@@ -560,69 +562,48 @@ async function ProcessBackground(
...
-      break;
-    case "providers/cloud.firestore/eventTypes/document.delete":
-      data = oldSnap;
-      break;
-    case "providers/cloud.firestore/eventTypes/document.create":
-      data = newSnap;
-      break;
-  }
+// TODO: Unify this with the HTTPS one (just Run())
+async function RunBackground(func: (proto: any) => Promise<any>, proto: any): Promise<any> {
```
Comment (abeisgoat) [inline src/emulator/functionsEmulatorRuntime.ts]: Are we going to try to unify this for this PR or nah?

File: src/emulator/functionsEmulatorShell.ts [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+}
+
+export class FunctionsEmulatorShell implements FunctionsShellController {
+  triggers: EmulatedTriggerDefinition[];
+  emulatedFunctions: string[];
+  urls: { [name: string]: string } = {};
+
+  constructor(private emu: FunctionsEmulator) {
+    this.triggers = emu.getTriggers();
+    this.emulatedFunctions = this.triggers.map((t) => {
```
Comment (abeisgoat) [inline src/emulator/functionsEmulatorShell.ts]: Can we call this `trigger` or `definition` instead of `t`?

File: src/emulator/functionsEmulatorShell.ts [hunk 11]
```diff
@@ -0,0 +1,101 @@
...
+      return t.name;
+    });
+
+    utils.logLabeledBullet("functions", `Loaded functions: ${this.emulatedFunctions.join(", ")}`);
+
+    for (const t of this.triggers) {
```
Comment (abeisgoat) [inline src/emulator/functionsEmulatorShell.ts]: Same here, would prefer something other than `t`

File: src/emulator/functionsEmulatorShell.ts [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+    FunctionsEmulator.startFunctionRuntime(
+      this.emu.bundleTemplate,
+      name,
+      this.emu.nodeBinary,
+      proto
+    );
+  }
+
+  private getTrigger(name: string): EmulatedTriggerDefinition {
+    const trig = this.triggers.find((def) => {
```
Comment (abeisgoat) [inline src/emulator/functionsEmulatorShell.ts]: change this to line up with whatever we called `t` above?

File: src/functionsShellCommandAction.js [hunk 13]
```diff
@@ -9,17 +9,20 @@ var util = require("util");
...
 var LocalFunction = require("./localFunction");
 var logger = require("./logger");
+var shell = require("./emulator/functionsEmulatorShell");
 
 module.exports = function(options) {
   options.port = parseInt(options.port, 10);
 
   return serveFunctions
-    .start(options)
+    .start(options, { quiet: true })
```
Comment (abeisgoat) [inline src/functionsShellCommandAction.js]: Should we maybe change `quiet` to be a verbosity level like `"QUIET" | "NORMAL" | "VERBOSE"` so that we could replace `_is_verbose` in tests and just allow us to set a level on `EmulatorLogger`?

File: src/emulator/events/types.ts (hunk 4 above)
Comment (samtstern) [reply src/emulator/events/types.ts]: They're marked as `@internal` though does that matter?

Comment (samtstern) [reply src/emulator/events/types.ts]:
```
import { Event, LegacyEvent } from "firebase-functions/lib/cloud-functions" 
```

That doesn't work for me, am I doing it wrong?

Comment (samtstern) [reply src/emulator/events/types.ts]: Yeah they're @internal so they are not exported :-(

File: src/emulator/events/types.ts (hunk 6 above)
Comment (samtstern) [reply src/emulator/events/types.ts]: This one I was able to import.

File: src/functionsShellCommandAction.js (hunk 13 above)
Comment (samtstern) [reply src/functionsShellCommandAction.js]: Couldn't quite get there (JS/TS fun) but introduced the concept of verbosity.

Comment (samtstern) [reply src/functionsShellCommandAction.js]: So you can set that in tests if you want.

**Comment by JakeHedman** [comment]
@samtstern: Yay! :1st_place_medal: What's the ETA of the next version?

File: src/emulator/events/types.ts [hunk 14]
```diff
@@ -0,0 +1,86 @@
...
+ */
+export interface AuthMode {
+  admin: boolean;
+  variable?: any;
+}
+
+/**
+ * Utilities for determining event types.
+ */
+export class EventUtils {
```
Comment (bkendall) [inline src/emulator/events/types.ts]: I think having a file named "types" is a little odd. I would recommend (maybe in the future) to:

1. put the "types" in a `events.d.ts` file to simply declare the types
1. put the Utils functionality here in a "utils" type file to keep the code separate
