### PR TITLE
Fix small issues with init emulators

### LINKED ISSUE #2287: firebase init emulators uses string for non-default ports
### [REQUIRED] Environment info

**firebase-tools:** 8.4.0

**Platform:** Windows - WSL2 Debian

### [REQUIRED] Test case

```
firebase init emulators
```

### [REQUIRED] Steps to reproduce

When initializing emulators, select port 8040 for Firestore instead of 8080

### [REQUIRED] Expected behavior

```js
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8040 // <--
    },
    "hosting": {
      "port": 5000
    },
    "ui": {
      "enabled": true
    }
  }
```

### [REQUIRED] Actual behavior

```js
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": "8040" // <--
    },
    "hosting": {
      "port": 5000
    },
    "ui": {
      "enabled": true
    }
  }
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

- Fixes #2287
- Fixes an issue with UI not being downloaded

### Scenarios Tested

Run `firebase init emulators` on a fresh project, selecting only Firestore and UI and selecting custom ports for both.

### Sample Commands

N/A

### CODE REVIEW

File: src/init/features/emulators.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ export async function doSetup(setup: any, config: any) {
       if (ui.enabled) {
         await prompt(ui, [
           {
-            type: "input",
+            type: "number",
```
Comment (yuchenshi) [inline src/init/features/emulators.ts:79]: Does empty string (any port) still work here?

Comment (samtstern) [reply src/init/features/emulators.ts:79]: Good question and yes, I was able to produce this:
```json
{
  "emulators": {
    "firestore": {
      "port": 8040
    },
    "ui": {
      "enabled": true
    }
  }
}
```
