### PR TITLE
Fixed issue where firebase init hosting re-prompts for source

### LINKED ISSUE #8587: Astro Initialize Hosting -  Could not determine the web framework to use
### [REQUIRED] Environment info

the issue is with 14.3.1

**firebase-tools:**
14.3.1

**Platform:**
Windows
### [REQUIRED] Test case

Create a new Astro project and attempt initializing hosting
### [REQUIRED] Steps to reproduce

Create a new Astro project and attempt initializing hosting 
### [REQUIRED] Expected behavior

It should allow for creation
### [REQUIRED] Actual behavior

Image

### PR DESCRIPTION
**Pull request by aalej**
### Description

Fixes #8587 

From what I can tell, the previous behavior of `promptOnce` and `prompt` was that, once a question has an answer, we no longer prompt for that question 

--- promptOnce

https://github.com/firebase/firebase-tools/blob/8cc734b079ee3e4e587d17c5a725da2e06555157/src/prompt.ts#L108-L113

--- prompt

https://github.com/firebase/firebase-tools/blob/8cc734b079ee3e4e587d17c5a725da2e06555157/src/prompt.ts#L47-L70

### Scenarios Tested

Verified that the prompts behave the same as the old versions (14.2.2)

#### 14.2.2 behavior
```
$ firebase --version
14.2.2
$ firebase init hosting --project PROJECT_ID

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /PATH/orbital-osiris

Before we get started, keep in mind:

  * You are currently outside your home directory


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add, 
but for now we'll just set up a default project.

i  Using project PROJECT_ID (PROJECT_NAME)

=== Hosting Setup
? Detected an existing Astro codebase in the current directory, should we use this? Yes
? In which region would you like to host server-side content, if applicable? us-central1 (Iowa)
? Set up automatic builds and deploys with GitHub? No

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
```

#### branch behavior
```
$ firebase --version
14.4.0
$ firebase init hosting --project PROJECT_ID

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /PATH/8587


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add, 
but for now we'll just set up a default project.

i  Using project PROJECT_ID (PROJECT_NAME)

=== Hosting Setup
✔ Detected an existing Astro codebase in the current directory, should we use this? Yes
✔ In which region would you like to host server-side content, if applicable? us-central1 (Iowa)
✔ Set up automatic builds and deploys with GitHub? No

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
```

### CODE REVIEW

File: src/init/features/hosting/index.ts [hunk 1]
```diff
@@ -66,10 +66,12 @@ export async function doSetup(setup: any, config: any, options: Options): Promis
   if (experiments.isEnabled("webframeworks")) {
     if (discoveredFramework) {
       const name = WebFrameworks[discoveredFramework.framework].name;
-      setup.hosting.useDiscoveredFramework = await confirm({
-        message: `Detected an existing ${name} codebase in the current directory, should we use this?`,
-        default: true,
-      });
+      setup.hosting.useDiscoveredFramework =
+        setup.hosting.useDiscoveredFramework ||
```
Comment (jamesdaniels) [inline src/init/features/hosting/index.ts:70]: You could simplify with `||=` here for same effect but you really should be using `??` or `??=` here since we want `false` to be a cachable value

**Review by jamesdaniels — CHANGES_REQUESTED** [review]

File: src/init/features/hosting/index.ts (hunk 1 above)
Comment (jamesdaniels) [reply src/init/features/hosting/index.ts:70]: Same feedback for other changed lines

Comment (aalej) [reply src/init/features/hosting/index.ts:70]: Thanks for the feedback! Will update

**Review by jamesdaniels — APPROVED** [review]

**Review by joehan — APPROVED** [review]
