### PR TITLE
Fixes #1280 - Emulator Socket on Windows

### LINKED ISSUE #1280: Emulator socket fails on Windows with EACCES
### [REQUIRED] Environment info

**firebase-tools:**6.9.2

**Platform:**Windows

### [REQUIRED] Test case

With 6.9.2 I try to emulate functions locally and get this whenever I call a function:

`!  Your requested "node" version "8" doesn't match your global version "10"
+  functions: Emulator started at http://localhost:5000
i  functions: Watching "[removed]" for Cloud Functions...
!  Default "firebase-admin" instance created!
i  functions: HTTP trigger initialized at http://localhost:5000/[removed]/us-central1/helloWorld
i  functions: Beginning execution of "helloWorld"
!  Default "firebase-admin" instance created!
>  events.js:174
>        throw er; // Unhandled 'error' event
>        ^
>
>  Error: listen EACCES: permission denied C:\Users\Work\AppData\Local\Temp\firebase_emulator_invocation_10596.sock
>      at Server.setupListenHandle [as _listen2] (net.js:1253:19)
>      at listenInCluster (net.js:1318:12)
>      at Server.listen (net.js:1416:5)
>      at Function.listen (C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\application.js:618:24)
>      at Promise (C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:359:46)
>      at new Promise (<anonymous>)
>      at C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:332:15
>      at Generator.next (<anonymous>)
>      at C:\Users\Work\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorRuntime.js:7:71
>      at new Promise (<anonymous>)
>  Emitted 'error' event at:
>      at emitErrorNT (net.js:1297:8)
>      at process._tickCallback (internal/process/next_tick.js:63:19)
>      at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
>      at startup (internal/bootstrap/node.js:283:19)
>      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

This behaviour was not present in 6.8.0 and I just verified that 6.8.0 works.

I even reinstalled Windows to double check (don't worry, it was time to do it anyway).

Note that I'm running firebase tools as the administrator, so not sure where the permission denied error is coming from.

Also note that when I run a basic express server:

`const express = require('express')
const app = express()
const port = "c:\temp\f.sock"

app.get('/', (req, res) => res.send('Hello World!'))

app.listen(port, () => console.log(`Example app listening on port ${port}!`))`

I get the same error.  

### [REQUIRED] Steps to reproduce

1. Install firebase tools@6.9.2
2. Init a new project with just functions
3. Uncomment the helloWorld function example
4. Emulate the function locally with firebase serve command
5. Call the localhost function url
6. Notice the crash

### [REQUIRED] Expected behavior

The function should run.

### [REQUIRED] Actual behavior

The function crashes.

### PR DESCRIPTION
**Pull request by abeisgoat**
We use an inter-process communication socket / pipe to send HTTP requests to the emulator. On Windows, this requires the use of a special path which we now support.

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -535,6 +536,12 @@ async function ProcessHTTPS(frb: FunctionsRuntimeBundle, trigger: EmulatedTrigge
         res.on("finish", () => {
           instance.close();
           resolveEphemeralServer();
+
+          process.nextTick(() => {
+            if (process.platform !== "win32") {
+              fs.unlinkSync(socketPath);
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: What's going on here?  Also don't tell me, talk to the `//`

File: src/emulator/functionsEmulatorShared.ts [hunk 2]
```diff
@@ -127,7 +127,11 @@ export function getEmulatedTriggersFromDefinitions(
 }
 
 export function getTemporarySocketPath(pid: number): string {
-  return path.join(os.tmpdir(), `firebase_emulator_invocation_${pid}.sock`);
+  if (process.platform === "win32") {
+    return path.join("\\\\?\\pipe", process.cwd(), pid.toString());
```
Comment (samtstern) [inline src/emulator/functionsEmulatorShared.ts]: Where did you learn this magic?  If it's a SO question or something just comment a link to it
