### PR TITLE
Fix two issues with Firestore database updating

### LINKED ISSUE #6451: Datastore mode databases may be silently mode-changed to Firestore native
### [REQUIRED] Environment info

Firebase CLI v12.6.2

**firebase-tools:**

Linux

**Platform:**

### [REQUIRED] Test case

* A Google Cloud project which is being used for Firebase
* At least one Datastore mode database in that project, with at least one entity (assume is called "fbcli"), and PITR is disabled

### [REQUIRED] Steps to reproduce

1. `firebase firestore:databases:update --point-in-time-recovery ENABLED fbcli`
2. `firebase firestore:databases:update --point-in-time-recovery DISABLED fbcli`
3. Delete the entity from Datastore
4. `firebase firestore:databases:update --point-in-time-recovery DISABLED fbcli`

### [REQUIRED] Expected behavior

In all 3 cases, the database should be recognized as being in Datastore mode and the CLI should not make any changes. It should instead respond with an error message saying that only Firestore Native databases are supported by Firebase.

### [REQUIRED] Actual behavior

1. "Error: HTTP Error: 400, Updating database type and other fields together is not supported." PITR is not updated.
2. Error: HTTP Error: 400, A document with key 't/123456789L' exists in the database. The database must be empty to make this change. Delete this document and try again.
3. (Not part of Firebase-cli)
4. CLI returns success message and database has changed to Firebase Native type.

### PR DESCRIPTION
**Pull request by rwhogg**
### Description

* Performing an update on a Datastore mode database could silently change it to Firestore Native
* Enabling PITR (--point-in-time-recovery=ENABLED) while not specifying --disaster-recovery=ENABLED would silently disable disaster recovery, and vice-versa

 The former issue was due to always sending FIRESTORE_NATIVE as the database type, when we
 actually didn't need to send it at all. The latter issue was due to command-line option
 parsing that assumed not specifying an option was equivalent to sending an explicit DISABLE.

### Scenarios Tested

* [x] Datastore mode db has data - no complaints about updating type at same time as delete protection
* [x] Datastore mode db has data - no complaints about updating type at same time as pitr
* [x] Datastore mode no data - mode is not silently changed to Firestore Native
* [x] Firestore Native mode - delete protection and PITR enabled, --point-in-time-recovery=DISABLED updates PITR but not delete protection
* [x] Firestore Native mode - delete protection and PITR enabled, --delete-protection=DISABLED updates delete protection but not PITR
* [x] Firestore Native mode - delete proetection and PITR enabled, --point-in-time-recovery=DISABLED --delete-protection=DISABLED updates both
* [x] Firestore Native mode - delete protection and PITR disabled, --point-in-time-recovery=ENABLED updates PITR but not delete protection
* [x] Firestore Native mode - delete protection and PITR disabled, --delete-protection=ENABLED updates delete protection but not PITR
* [x] Firestore Native mode - delete protection enabled and PITR disabled, --point-in-time-recovery=ENABLED updates PITR but not delete protection
* [x] Firestore Native mode - delete protection disabled and PITR enabled, --delete-protection=ENABLED updates delete protection but not PITR
* [x] Firestore Native mode - delete protection enabled and PITR disabled, --delete-protection=DISABLED and --point-in-time-recovery=ENABLED updates both
* [x] Firestore Native mode - delete protection disabled and PITR enabled, --delete-protection=ENABLED and --point-in-time-recovery=DISABLED updates both
* [x] Firestore Native mode - delete protection enabled and PITR disabled, --delete-protection=ENABLED and --point-in-time-recovery=DISABLED has no effect
* [x] Firestore Native mode - delete protection disabled and PITR enabled, --delete-protection=DISABLED and --point-in-time-recovery=ENABLED has no effect

Closes #6451

### CODE REVIEW

**Review by joshuamelcon — APPROVED** [review]

**Review by bkendall — APPROVED** [review]
LGTM. Consider adding an entry in `CHANGELOG.md`

File: src/commands/firestore-databases-update.ts [hunk 1]
```diff
@@ -26,13 +26,12 @@ export const command = new Command("firestore:databases:update <database>")
   .action(async (database: string, options: FirestoreOptions) => {
     const api = new fsi.FirestoreApi();
 
-    if (!options.type && !options.deleteProtection && !options.pointInTimeRecovery) {
+    if (!options.deleteProtection && !options.pointInTimeRecovery) {
```
Comment (rwhogg) [inline src/commands/firestore-databases-update.ts:29]: NOTE TO SELF: please write a changelog entry
