### PR TITLE
Provide default values for namespace and database for v2 Firestore triggers in extensions

### LINKED ISSUE #8390: `A namespace must be supplied` with no further debugging explanation on emulator setup
### [REQUIRED] Environment info

**firebase-tools:** 13.29.0

**Platform:** Linux 6.12.17-1-lts

### [REQUIRED] Test case
https://github.com/tharropoulos/firebase-reprod

### [REQUIRED] Steps to reproduce
* Create a project with emulators for functions, extensions and firestore
* Add the Typesense Firestore adapter with the v2 API
* Try to start the emulators
* Get the `a namespace must be supplied` error, with no further explanation

### [REQUIRED] Expected behavior
Get a better debug log to identify the issue in the extension

### [REQUIRED] Actual behavior
Get this debug log:
```
[2025-03-31T09:05:39.533Z] [Extensions] Connecting Extensions emulator, this is a noop.
i  functions: Watching "/home/fanis/.cache/firebase/extensions/typesense/firestore-typesense-search@2.0.1/functions" for Cloud Functions... {"metadata":{"emulator":{"name":"functions"},"message":"Watching \"/home/fanis/.cache/firebase/extensions/typesense/firestore-typesense-search@2.0.1/functions\" for Cloud Functions..."}}
✔  functions: Loaded functions definitions from source: indexOnWrite, backfill. {"metadata":{"emulator":{"name":"functions"},"message":"Loaded functions definitions from source: indexOnWrite, backfill."}}
[2025-03-31T09:05:39.535Z] Found a v2 firestore trigger.
[2025-03-31T09:05:39.537Z] Could not find VSCode notification endpoint: FetchError: request to http://localhost:40001/vscode/notify failed, reason: connect ECONNREFUSED ::1:40001. If you are not running the Firebase Data Connect VSCode extension, this is expected and not an issue.
i  emulators: Shutting down emulators. {"metadata":{"emulator":{"name":"hub"},"message":"Shutting down emulators."}}
i  ui: Stopping Emulator UI {"metadata":{"emulator":{"name":"ui"},"message":"Stopping Emulator UI"}}
i  extensions: Stopping Extensions Emulator {"metadata":{"emulator":{"name":"extensions"},"message":"Stopping Extensions Emulator"}}
[2025-03-31T09:05:39.538Z] [Extensions] Stopping Extensions emulator, this is a noop.
i  functions: Stopping Functions Emulator {"metadata":{"emulator":{"name":"functions"},"message":"Stopping Functions Emulator"}}
i  firestore: Stopping Firestore Emulator {"metadata":{"emulator":{"name":"firestore"},"message":"Stopping Firestore Emulator"}}
[2025-03-31T09:05:39.540Z] *** shutting down gRPC server since JVM is shutting down
 {"metadata":{"emulator":{"name":"firestore"},"message":"*** shutting down gRPC server since JVM is shutting down\n"}}
[2025-03-31T09:05:39.556Z] *** server shut down
 {"metadata":{"emulator":{"name":"firestore"},"message":"*** server shut down\n"}}
i  eventarc: Stopping Eventarc Emulator {"metadata":{"emulator":{"name":"eventarc"},"message":"Stopping Eventarc Emulator"}}
i  tasks: Stopping Cloud Tasks Emulator {"metadata":{"emulator":{"name":"tasks"},"message":"Stopping Cloud Tasks Emulator"}}
i  hub: Stopping emulator hub {"metadata":{"emulator":{"name":"hub"},"message":"Stopping emulator hub"}}
i  logging: Stopping Logging Emulator {"metadata":{"emulator":{"name":"logging"},"message":"Stopping Logging Emulator"}}
[2025-03-31T09:05:39.896Z] Could not find VSCode notification endpoint: FetchError: request to http://localhost:40001/vscode/notify failed, reason: connect ECONNREFUSED ::1:40001. If you are not running the Firebase Data Connect VSCode extension, this is expected and not an issue.

Error: A namespace must be supplied.
```

### PR DESCRIPTION
**Pull request by joehan**
### Description
If omitted from the resource definition, we should still use fallback values for these triggers (to match the behavior of firebase-functions).

Fixes #8390.

### Scenarios Tested
Successfully emulated the v2.0.1 of the typesense extension (following the repro provided at https://github.com/tharropoulos/firebase-reprod)

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -1140,7 +1140,7 @@ export class FunctionsEmulator implements EmulatorInstance {
     if (!EmulatorRegistry.isRunning(Emulators.FIRESTORE)) {
       return Promise.resolve(false);
     }
-
+    console.log(eventTrigger);
```
Comment (pavelgj) [inline src/emulator/functionsEmulator.ts:1143]: intentional?

**Review by pavelgj — APPROVED** [review]

File: src/emulator/functionsEmulator.ts (hunk 1 above)
Comment (joehan) [inline src/emulator/functionsEmulator.ts:1143]:
```suggestion
```

Comment (joehan) [reply src/emulator/functionsEmulator.ts:1143]: Nope, just forgot to clean it up
