### PR TITLE
Authorize using Firebase CLI credentials

### LINKED ISSUE #1940: Functions shell/emulator unable to load default credentials
### [REQUIRED] Environment info

**firebase-tools:** 7.12.1

**Platform:** Debian on WSL on Windows 10

### [REQUIRED] Test case

``` ts
import * as functions from 'firebase-functions';
const admin = require('firebase-admin').initializeApp(functions.config().firebase);

exports.action1 = functions.https.onCall(() => {
  return admin.database().ref('action').push({ 'a': 1 })
});
```

### [REQUIRED] Steps to reproduce

`npm run shell` with the above code, execute function `action({})`

### [REQUIRED] Expected behavior

The shell environment should be able to locally simulate the function and access the database, according to the documentation: [Cloud Firestore and Realtime Database triggers already have sufficient credentials, and do not require additional setup.
](https://firebase.google.com/docs/functions/local-emulator#set_up_admin_credentials_optional)

### [REQUIRED] Actual behavior

I receive the following message:

> @firebase/database: FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"Error fetching access token: Error while making request: getaddrinfo ENOTFOUND metadata.google.internal. Error code: ENOTFOUND\"."}

Some digging through the documentation provided me with various different answers, none of which solved my issue. Please note that I would like to locally develop with the same code as the one that I deploy. Some things I found:
1. I tried with and without `functions.config().firebase` but it's not clear when and if this is required

2. [Setup Admin Credentials](https://firebase.google.com/docs/functions/local-shell#set_up_admin_credentials_optional) using the export command. I changed the default command to:
```
"shell": "export GOOGLE_APPLICATION_CREDENTIALS=\"my-owner-key.json\" && tsc --watch --preserveWatchOutput & firebase functions:shell",
```
According to the (closed) issue #595 for some reason a `protect_env` flag sets this environment variable to an empty string. **I don't see the reasoning for this 'protection'** as the documentation explicitly explains you need to set this variable if you wish to use the shell in an authenticated fashion. PR #1252 added the functionality to disable `protect_env` but I couldn't get the `--disable-features` flag working or even find any documentation on it anywhere.

3. [Manually updating the autopopulated config](https://firebase.google.com/docs/functions/config-env)
```
serviceAccount = require('./serviceAccount.json');

const adminConfig = JSON.parse(process.env.FIREBASE_CONFIG);
adminConfig.credential = admin.credential.cert(serviceAccount);
admin.initializeApp(adminConfig);
```

Somehow injecting the json is supposed to work according to the documentation however this code fails to compile with the following error:
```
error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

const adminConfig = JSON.parse(process.env.FIREBASE_CONFIG);
```

It also feels hacky and would not be transferrable to the server as-is as it explicitly depends on a `.json` credential file being deployed.

Edit: I found a 4 month old issue on this topic that is still regularly receiving reports of users encountering the same problem: #1708

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1940

TODO:
- [x] Add pre-execution warnings about accessing prod
- [x] Add a description of how auth works in the README

This change will allow the Firebase emulators to pass the credentials from `firebase login` as Cloud application default credentials.

Currently the emulators rely on picking up gcloud auth application-default login credentials on the machine which is at best annoying and at worst means that the emulators are authorized as the wrong user.

Here's the new behavior matrix:

| # | Firebase Login | Application Default | `GAC` Env | Result |
|---|----------------|---------------------|-----------|-------|
| 1 | ❌  | ❌  | ❌  | Emulator has no auth at all |
| 2 | ✅  | ❌  | ❌  | CLI passes `GAC` env to emulator with user credential |
| 3 | ❌  | ✅ | ❌  | ADC may be discovered and used|
| 4 | ❌  | ❌  | ✅  | Emulator will use explicit `GAC` credential |
| 5 | ✅  |✅  | ❌  | CLI passes `GAC` env, ADC is ignored |
| 6 | ✅  | ❌  | ✅  | CLI does not pass cred, Emulator will use explicit `GAC` credential |
| 7 | ❌  | ✅  | ✅  | Emulator will use explicit `GAC` credential, ADC is ignored |
| 8 |✅ | ✅  | ✅  | Emulator will use explicit `GAC` credential, all others |

Note: we can/should change the behavior of Scenario 3 when this bug is fixed:
https://github.com/firebase/firebase-js-sdk/issues/3144

### Scenarios Tested

Functions used for all tests:
```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

async function tryRtdbWrite() {
  const db = admin.database();
  try {
    await db.ref().child('test').set({
      date: new Date().toISOString()
    });
    return true;
  } catch (e) {
    console.warn(e);
    return false;
  }
}

exports.helloWorld = functions.https.onRequest(async (request, response) => {
  response.json({
    creds: process.env.GOOGLE_APPLICATION_CREDENTIALS || null,
    canWriteToDatabase: await tryRtdbWrite()
  });
});
```

**Scenario 1**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld

http: error: Request timed out (30s).
```

Emulator logs
```
>  [2020-07-07T18:30:07.387Z]  @firebase/database: FIREBASE WARNING: {"code":"app/invalid-credential","message":"Credential implementation provided to initializeApp() via the \"credential\" property failed to fetch a valid Google OAuth2 access token with the following error: \"Error fetching access token: Error while making request: getaddrinfo ENOTFOUND metadata.google.int
```

</details>

**Scenario 2**
<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 127
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:32:07 GMT
etag: W/"7f-QwapyiMrFDzSQjxgEK52zAhX9pU"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": "/Users/samstern/.config/firebase/samstern_google_com_application_default_credentials.json"
}
```

</details>

**Scenario 3**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 40
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:40:37 GMT
etag: W/"28-0p3KpSLf1GtAozwuGH12/ekZOZY"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": null
}
```

</details>

**Scenario 4**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 104
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:36:43 GMT
etag: W/"68-YwHpi6KFuPjLagvh8WBTCXYvjUY"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": "/Users/samstern/service-accounts/fir-dumpster/service-account.json"
}
```

</details>

**Scenario 5**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 127
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:38:08 GMT
etag: W/"7f-QwapyiMrFDzSQjxgEK52zAhX9pU"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": "/Users/samstern/.config/firebase/samstern_google_com_application_default_credentials.json"
}
```

</details>

**Scenario 6**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 104
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:34:23 GMT
etag: W/"68-YwHpi6KFuPjLagvh8WBTCXYvjUY"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": "/Users/samstern/service-accounts/fir-dumpster/service-account.json"
}
```

</details>

**Scenario 7**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 104
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:39:34 GMT
etag: W/"68-YwHpi6KFuPjLagvh8WBTCXYvjUY"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": "/Users/samstern/service-accounts/fir-dumpster/service-account.json"
}
```

</details>

**Scenario 8**

<details>
<summary>See logs</summary>

```
$ http http://localhost:5001/fir-dumpster/us-central1/helloWorld
HTTP/1.1 200 OK
connection: keep-alive
content-length: 104
content-type: application/json; charset=utf-8
date: Tue, 07 Jul 2020 18:38:46 GMT
etag: W/"68-YwHpi6KFuPjLagvh8WBTCXYvjUY"
x-powered-by: Express

{
    "canWriteToDatabase": true,
    "creds": "/Users/samstern/service-accounts/fir-dumpster/service-account.json"
}
```

</details>

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/controller.ts [hunk 1]
```diff
@@ -263,20 +265,39 @@ export async function startAll(options: any, noUi: boolean = false): Promise<voi
...
-      EmulatorLogger.forEmulator(Emulators.FUNCTIONS).logLabeled(
+      functionsLogger.logLabeled(
         "WARN",
         "functions",
         `You are running the functions emulator in debug mode (port=${inspectFunctions}). This means that functions will execute in sequence rather than in parallel.`
       );
     }
 
+    // Provide default application credentials when appropriate
+    const credentialEnv = {} as any;
```
Comment (yuchenshi) [inline src/emulator/controller.ts:276]:
```suggestion
    const credentialEnv: Record<string, string> = {};
```

File: src/defaultCredentials.ts [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+
+interface RefreshTokenCredential {
+  client_id: string;
+  client_secret: string;
+  refresh_token: string;
+  type: string;
+}
+
+/**
+ * Creates Cloud application default credentials using the authorization from
```
Comment (bkendall) [inline src/defaultCredentials.ts:16]: This class doesn't actually create anything. The methods inside it do. That said, this class doesn't hold any information that's required across all the functions - why have a class at all?

Could all the public methods in this class be top-level exported functions, and the helper (private) methods be unexported? That would eliminate the need for a class (which is preferred - these are functionally static methods, and container classes for static methods are discouraged)

File: src/defaultCredentials.ts [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+ * 'firebase login'.
+ */
+export class DefaultCredentials {
+  /**
+   * Get a path to the application default credentials JSON file.
+   */
+  public async getPathAsync(): Promise<string | undefined> {
```
Comment (bkendall) [inline src/defaultCredentials.ts:23]: Is it worth writing any unit tests for exported methods in this file?

File: src/defaultCredentials.ts [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+import * as path from "path";
+
+import * as api from "./api";
+import { configstore } from "./configstore";
+import * as logger from "./logger";
+
+interface RefreshTokenCredential {
+  client_id: string;
+  client_secret: string;
+  refresh_token: string;
```
Comment (bkendall) [inline src/defaultCredentials.ts:11]: I would very strongly suggest using camelCase for consistency with the rest of the codebase. If underscores are required, please silence the warning with a `eslint-disable-line` to acknowledge that they are required in this form.

Comment (samtstern) [reply src/defaultCredentials.ts:11]: This is not a choice, we have to have this exact format for it to be a valid credential.

Comment (bkendall) [reply src/defaultCredentials.ts:11]: Got it. I think that's an even stronger case for adding the comments then - you don't want someone like me coming along and "cleaning these up" and causing it to break 🙂

File: src/defaultCredentials.ts [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+
+  const cred = getCredential();
+  if (!cred) {
+    logger.debug("defaultcredentials: no credential available.");
+    return undefined;
+  }
+
+  // We could use fs.writeFileSync() here but it's important that the caller understands
+  // that this is a somewhat expensive operation so we make it a Promise.
+  return new Promise((res, rej) => {
```
Comment (hiranya911) [inline src/defaultCredentials.ts:35]: Wouldn't this overwrite whatever is currently in that path? Is that the behavior we want?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 6]
```diff
@@ -963,14 +963,6 @@ async function initializeRuntime(
   }
 
   initializeEnvironmentalVariables(frb);
-  if (process.env.GOOGLE_APPLICATION_CREDENTIALS) {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts:966]: TODO(me): We need to re-instate this warning but only if the user provided the credentials themselves.

File: src/defaultCredentials.ts (hunk 5 above)
Comment (samtstern) [reply src/defaultCredentials.ts:35]: Yes that's the behavior we want.  I'm willing to pay this small extra cost to avoid the whole class of bugs that come with potentially out of date credentials.

File: src/defaultCredentials.ts (hunk 3 above)
Comment (samtstern) [reply src/defaultCredentials.ts]: Done, good idea.

File: src/defaultCredentials.ts [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+
+  if (!configDir) {
+    return undefined;
+  }
+
+  if (!fs.existsSync(configDir)) {
+    fs.mkdirSync(configDir);
+  }
+
+  const fbtConfigDir = path.join(configDir, "firebase-tools");
```
Comment (mbleigh) [inline src/defaultCredentials.ts:79]: Just `firebase` maybe?

File: src/defaultCredentials.ts [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+  if (!fs.existsSync(fbtConfigDir)) {
+    fs.mkdirSync(fbtConfigDir);
+  }
+
+  return path.join(fbtConfigDir, "application_default_credentials.json");
```
Comment (mbleigh) [inline src/defaultCredentials.ts:84]: I think we should potentially embed the signed-in email as part of the filename here. Developers sometimes have multiple accounts that they switch between, and it seems like being able to concretely identify the scope of the credentials by sight would be a good thing.

Also we may add the ability to quickly switch between accounts in the future which would future-proof this particular thing as well.

Also this file needs to be deleted when the user logs out.

Comment (samtstern) [reply src/defaultCredentials.ts:84]: Ok I am gonna put the user's email as a prefix like this:

```
"samstern@google.com" --> "samstern_google_com_application_default_credentials.json"
```

WDYT?

Comment (mbleigh) [reply src/defaultCredentials.ts:84]: SGTM

**Comment by samtstern** [comment]
TODO: @samtstern - handle the case where the user has Application Default Credentials but has never called `firebase login`
