### PR TITLE
Dont try to use expired refresh tokens

### LINKED ISSUE #7442: Tool commands 'logout' and 'login --reauth' fail when credentials are expired in firebase-tools@13.13.2
### Environment info

**firebase-tools: 13.13.2**

**Platform: macOS**

### Test case

```
(base) andrewjenkins@Andrews-MBP tmpt_me_client %  firebase login --reauth
(node:85243) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

(base) andrewjenkins@Andrews-MBP tmpt_me_client % firebase logout
(node:53687) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Error: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth
```

### Steps to reproduce

With most recent version of 13.13.2:

```
 npm install -g firebase-tools
firebase login
```
...wait for credentials to expire
```
firebase login --reauth
```

### Expected behavior

I should be able to logout or refresh expired credentials

### Actual behavior

The tool produces an Authentication Error even on logout.  Downgrading to **npm install -g firebase-tools@13.13.1** works

### PR DESCRIPTION
**Pull request by joehan**
### Description
Fixes #7442 

### Testing
- Built VSCode and verified that credentials from 'firebase login' were correctly picked up and the project picker worked correctly.
- Tested auth from the CLI with an expired refresh_token and verified that `firebase logout` does not fail with 'run firebase login --reauth'

### CODE REVIEW

File: firebase-vscode/src/cli.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export async function requireAuthWrapper(
     return (
       account &&
       account.user.email === optionsUser.email &&
-      account.tokens.access_token === optionsTokens.access_token // TODO: check if this is necessary
+      account.tokens.refresh_token === optionsTokens.refresh_token // Should check refresh token which is consistent, not access_token which is short lived.
```
Comment (hlshen) [inline firebase-vscode/src/cli.ts:59]: ++ nice find

File: firebase-vscode/src/cli.ts [hunk 2]
```diff
@@ -80,8 +80,12 @@ export async function requireAuthWrapper(
   // over Google login tokens and must be removed if a Google
   // account is the current user.
   try {
-    setAccessToken(); // clears the current access token
     const userEmail = await requireAuth(currentOptions.value); // client email
+    // SetAccessToken is necessary here to ensure that access_tokens are available when:
+    // - we are using tokens from configstore (aka those set by firebase login), AND
+    // - we are calling CLI code that skips Command (where we normally call this)
+
+    setAccessToken(await getAccessToken());
```
Comment (hlshen) [inline firebase-vscode/src/cli.ts:88]: ahh this is a cleaner solution. Thanks for fixing this!

**Review by hlshen — APPROVED** [review]
