### PR TITLE
Reset global functions deploy variables on each deploy

### LINKED ISSUE #2628: Deploying Cloud Functions via firebase-tools js module results in redeploying of previous functions in memory
### Summary

I am reporting this issue on behalf of a firebase customer that reported this behavior. This customer had 70+ functions and was using `setTimeout` js method in order to avoid hitting a quota of deploying functions too quickly. Using this they intended to deploy 10 functions, wait, deploy 10 more functions, wait, etc..

However, the behavior they experienced was quite the opposite instead they encountered that the firebase-tools module was caching previous deploys in memory and providing the following behavior: deploy 10 functions, wait, deploy 20 functions, wait deploy 30 functions, etc.. thus leading them to exceed the quota they were trying to avoid.

I have created a simple [MCVE](https://github.com/thomasmburke/firebase-function-deploy-bug-MCVE) that illustrates this behavior with just 2 functions. Within the MCVE is the [script](https://github.com/thomasmburke/firebase-function-deploy-bug-MCVE/blob/master/cli-test.js) used to deploy functions by using firebase-tools standard Node module. I have place two functions in there

- `testFirebaseFuncDeploy`: Which exhibits the problematic behavior described above
- `testFirebaseFuncDeployWithCacheDelete`: Which works around the issue by clearing the require cache (only deploying each function once)

### [REQUIRED] Environment info

**firebase-tools: 8.10.0**

**Platform: macOS Catalina**

### [REQUIRED] Test case

[MCVE](https://github.com/thomasmburke/firebase-function-deploy-bug-MCVE)

### [REQUIRED] Steps to reproduce

`node cli-test.js`

This [cli-test.js script](https://github.com/thomasmburke/firebase-function-deploy-bug-MCVE/blob/master/cli-test.js) uses firebase-tools as a module to deploy firebase functions. When running this against the [MCVE](https://github.com/thomasmburke/firebase-function-deploy-bug-MCVE), 3 function deploys occur the first function, the second function, and then the first function again.

### [REQUIRED] Expected behavior

Deploy each function once.

### [REQUIRED] Actual behavior

Caching is deploying functions that have previously been deployed earlier in the script.

### PR DESCRIPTION
**Pull request by kmcnellis**
### Description

Fix #2628

### Scenarios Tested

See bug [MCVE](https://github.com/thomasmburke/firebase-function-deploy-bug-MCVE)

### CODE REVIEW

**Review by joehan — APPROVED** [review]
LGTM - and yikes, I hate that we are using global variables for this.

File: src/deploy/functions/release.js [hunk 1]
```diff
@@ -127,6 +127,12 @@ module.exports = function(context, options, payload) {
 
   var projectId = context.projectId;
   var sourceUrl = context.uploadUrl;
+
+  // Reset global variables to prevent duplicate deploys when using firebase-tools as an import.
```
Comment (bkendall) [inline src/deploy/functions/release.js:131]:
```suggestion
  // Reset module-level variables to prevent duplicate deploys when using firebase-tools as an import.
```

**Review by bkendall — APPROVED** [review]

**Comment by kmcnellis** [comment]
(manually squashed to remove Bryan's co-authored suggestion commit, since it used a personal email that hadn't signed the cla)
