### PR TITLE
Correctly copy over secret environment variables

### LINKED ISSUE #4540: Firebase deploy function with secret does not set secret env
### [REQUIRED] Environment info

**firebase-tools:**
v10.9.0

node 14

**Platform:**

macOS, GitHub Actions

### [REQUIRED] Test case
```
export const taskSchedulerEndPoint = functions
    .runWith({
      secrets: [
        'SECRET_NAME',
      ],
    })
    .https
    .onRequest(async (req, res) => {
      res.send('ok');
    });
```

### [REQUIRED] Steps to reproduce

deploy a function with runWith secrets config

### [REQUIRED] Expected behavior
Should set secret env accordingly 

### [REQUIRED] Actual behavior
no secret environment variables get set, in fact all previous secret env gets wiped out

### PR DESCRIPTION
**Pull request by inlined**
Fixes #4540

### CODE REVIEW

**Review by colerogers — APPROVED** [review]

File: src/deploy/functions/runtimes/discovery/v1alpha1.ts [hunk 1]
```diff
@@ -250,16 +250,15 @@ function parseEndpoints(
...
-          }
+        const secretEnvironmentVariables: backend.SecretEnvVar[] = [];
+        for (const { key, secret } of senvs!) {
+          secretEnvironmentVariables.push({
+            key,
+            secret: secret || key, // if secret is undefined, assume env var key == secret name
+            projectId: project,
+          });
         }
+        return secretEnvironmentVariables;
```
Comment (bkendall) [inline src/deploy/functions/runtimes/discovery/v1alpha1.ts:261]: Can there be a test written for this case? Running coverage for the test suite for this file tells me this block of code isn't exercised :)

**Review by bkendall — APPROVED** [review]
