### PR TITLE
Fix port conflicts with functions:shell

### LINKED ISSUE #3210: Can't connect to functions shell when hosting emulator is running
### [REQUIRED] Environment info

**firebase-tools:** 9.6.1

**Platform:** macOS

### [REQUIRED] Test case
A project with all the emulators enabled (hosting, pubsub, functions, database, ui) - a good example is https://github.com/Hacksore/firebase-shell-bug 

### [REQUIRED] Steps to reproduce

See: https://github.com/Hacksore/firebase-shell-bug/blob/master/README.md

### [REQUIRED] Expected behavior

I should be able to get the functions shell REPL while the hosting emulator is running.

### [REQUIRED] Actual behavior
When all emulators are running via `firebase emulators:start` you will get a connection error when attempting to `firebase functions:shell`

```log
Error: Port 5000 is not open on localhost, could not start functions emulator.
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #3210

Also I converted the file to `.ts` while I was in there

### Scenarios Tested

- Picking up the port from `firebase.json`
- Detecting another running emulator and printing a warning
- Using the `--port` flag

### Sample Commands

N/A

### CODE REVIEW

File: src/functionsShellCommandAction.ts [hunk 1]
```diff
@@ -61,11 +83,11 @@ module.exports = async function (options) {
         process.exit();
       }
 
-      var initializeContext = function (context) {
-        _.forEach(emulator.triggers, function (trigger) {
+      const initializeContext = (context: any) => {
+        _.forEach(emulator.triggers, (trigger) => {
```
Comment (joehan) [inline src/functionsShellCommandAction.ts:87]: Optional - it would be pretty easy to refactor this chunk to use plain JS instead of lodash, and then we're one step closer to removing the dependency for good

**Review by joehan — APPROVED** [review]
LGTM after a few tiny cleanups + lodash removal.

File: src/functionsShellCommandAction.ts (hunk 1 above)
Comment (samtstern) [reply src/functionsShellCommandAction.ts:87]: I got rid of `_.forEach` and `_.includes` but `_.set` with dot-separated path notation is a bit tricky so I left that. We'll probably need to create our own `utils.set` to replace that throughout the codebase and that seems out of scope for this PR.
