### PR TITLE
Fix rules hot reloading bug

### LINKED ISSUE #2371: Saving database rules creates a new database on the emulator and applies the rules to it
### [REQUIRED] Environment info

**firebase-tools:** 8.4.2

**Platform:** Windows

### [REQUIRED] Test case

https://github.com/filipesilva/firebase-rtdb-loglevel

### [REQUIRED] Steps to reproduce

- `git clone https://github.com/filipesilva/firebase-rtdb-loglevel`
- `cd firebase-rtdb-loglevel`
- `npm i`
- `npm run emulators`
- open http://localhost:4000/database, see the `emulator-test-1` database
- save `database.rules.json` once
- in the emulator logs in the console, see the following lines:
```
i  database: Change detected, updating rules for undefined...
+  database: Rules updated.
```
- open http://localhost:4000/database, see the `undefined` database

### [REQUIRED] Expected behavior

The rules should be applied to `emulator-test-1` and no new database should be created.

### [REQUIRED] Actual behavior

The rules are applied to a new database named `undefined`.

You can also change the code in `public/index.html` if you want to verify if the rules are applied to the correct database, but I was using the same reproduction for both this and https://github.com/firebase/firebase-js-sdk/issues/3211 and since this repro doesn't actually need to run any database code, I left it as is.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2371 

I also cleaned up some logging methods that were using the old `utils.*` loggers while I was in there.

### Scenarios Tested

See included reproduction by @felipesilva in #2371

### Sample Commands

N/A

### CODE REVIEW

File: src/database/rulesConfig.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export function getRulesConfig(projectId: string, options: any): RulesInstanceCo
 
   if (!Array.isArray(dbConfig)) {
     if (dbConfig && dbConfig.rules) {
-      return [{ rules: dbConfig.rules, instance: options.instance }];
+      return [{ rules: dbConfig.rules, instance: options.instance || options.project }];
```
Comment (samtstern) [inline src/database/rulesConfig.ts:27]: This is the bug.  We now fall back to the project Id when there is no `instance` in `options`.

File: src/emulator/databaseEmulator.ts [hunk 2]
```diff
@@ -33,6 +34,16 @@ export class DatabaseEmulator implements EmulatorInstance {
     }
     if (this.args.rules) {
       for (const c of this.args.rules) {
+        if (!c.instance) {
```
Comment (samtstern) [inline src/emulator/databaseEmulator.ts:37]: Purely defensive but should prevent any regression.

File: src/emulator/databaseEmulator.ts [hunk 3]
```diff
@@ -86,7 +98,7 @@ export class DatabaseEmulator implements EmulatorInstance {
     const { host, port } = this.getInfo();
     try {
       await api.request("PUT", `/.settings/rules.json?ns=${instance}`, {
-        origin: `http://${host}:${[port]}`,
+        origin: `http://${host}:${port}`,
```
Comment (samtstern) [inline src/emulator/databaseEmulator.ts:101]: I have no idea how this ever worked ...

Comment (bkendall) [reply src/emulator/databaseEmulator.ts:101]: Probably because it would join the array with commas, which would just be the port number

File: CHANGELOG.md [hunk 4]
```diff
@@ -0,0 +1 @@
+- Fixes bug with rules hot reloading in the Database emulator (#2371)
```
Comment (bkendall) [inline CHANGELOG.md:1]:
```suggestion
- Fixes a bug with RTDB Rules hot reloading in the RTDB emulator. (#2371)
```

? It's a little... too generic for my brain
