### PR TITLE
Fixes #1474 and #1447

### LINKED ISSUE #1447: Firebase emulator error "Unexpected end of multipart data"
### [REQUIRED] Environment info

7.0.2

macOS

### [REQUIRED] Test case

Create cloud function as https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/http/index.js

exports.uploadFile = (req, res) => {
please see in the example link above
};

run firebase serve

### [REQUIRED] Steps to reproduce

Create cloud function as https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/functions/http/index.js

exports.uploadFile = (req, res) => {
please see in the example link above
};

run firebase serve

Call the function via HTTP POST with Content-Type multipart/form-data

### [REQUIRED] Expected behavior

Run cloud function and response

### [REQUIRED] Actual behavior

>  events.js:174
>        throw er; // Unhandled 'error' event
>        ^
>  
>  Error: Unexpected end of multipart data
>      at /Users/jarruspong/Downloads/Dev/concordian-api/node_modules/dicer/lib/Dicer.js:62:28
>      at process._tickCallback (internal/process/next_tick.js:61:11)
>  Emitted 'error' event at:
>      at Busboy.emit (/Users/jarruspong/Downloads/Dev/concordian-api/node_modules/busboy/lib/main.js:38:33)
>      at Dicer.<anonymous> (/Users/jarruspong/Downloads/Dev/concordian-api/node_modules/busboy/lib/types/multipart.js:281:9)
>      at Dicer.emit (events.js:198:13)
>      at Dicer.emit (/Users/jarruspong/Downloads/Dev/concordian-api/node_modules/dicer/lib/Dicer.js:80:35)
>      at /Users/jarruspong/Downloads/Dev/concordian-api/node_modules/dicer/lib/Dicer.js:62:14
>      at process._tickCallback (internal/process/next_tick.js:61:11)

### LINKED ISSUE #1474: JSON string was partially returned when running function via Emulator
### Environment info

**firebase-tools:**
7.0.2

**Platform:**
macOS

### Test case

Here is the code:
```js
'use strict';

const FUNCTIONS = require('firebase-functions');
const ADMIN = require('firebase-admin');
ADMIN.initializeApp(FUNCTIONS.config().firebase); // Must be invoked before importing any other modules

exports.test = FUNCTIONS.https.onRequest((req, res) => {
    res.send({
        "events": [{
            "applicants": [],
            "latitude": 50.00525403677713,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "BSc0yXZILbaDWgHb0U3o",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.01933028798618,
            "geolocation": {
                "geohash_7": "y0zh7zp",
                "geohash_6": "y0zh7z",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.00525403677713,
                "geohash_9": "y0zh7zpve",
                "geohash_8": "y0zh7zpv",
                "longitude": 100.01933028798618
            }
        }, {
            "applicants": [],
            "latitude": 50.01345844676508,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "Hr1FzSbFHXCWQRw9Llbx",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.00143075971695,
            "geolocation": {
                "geohash_7": "y0zhe8d",
                "geohash_6": "y0zhe8",
                "geohash_5": "y0zhe",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.01345844676508,
                "geohash_9": "y0zhe8dvd",
                "geohash_8": "y0zhe8dv",
                "longitude": 100.00143075971695
            }
        }, {
            "applicants": [],
            "latitude": 50.01294618070128,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "KUwTov4vU6lfcNm6N38E",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 99.99410144063775,
            "geolocation": {
                "geohash_7": "y0zhe2t",
                "geohash_6": "y0zhe2",
                "geohash_5": "y0zhe",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.01294618070128,
                "geohash_9": "y0zhe2t6x",
                "geohash_8": "y0zhe2t6",
                "longitude": 99.99410144063775
            }
        }, {
            "applicants": [],
            "latitude": 50.00645698648151,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "VPBkHMBOYxrg7TyHYRNu",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 99.98157261550644,
            "geolocation": {
                "geohash_7": "y0zh7pk",
                "geohash_6": "y0zh7p",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.00645698648151,
                "geohash_9": "y0zh7pkke",
                "geohash_8": "y0zh7pkk",
                "longitude": 99.98157261550644
            }
        }, {
            "applicants": [],
            "latitude": 49.98709928565629,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "lp9RwqKLLVcEJsHKMUr1",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.00613333202384,
            "geolocation": {
                "geohash_7": "y0zh7ey",
                "geohash_6": "y0zh7e",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 49.98709928565629,
                "geohash_9": "y0zh7ey5z",
                "geohash_8": "y0zh7ey5",
                "longitude": 100.00613333202384
            }
        }, {
            "applicants": [],
            "latitude": 49.98778668034447,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "m0FWH7RAiGaGyUDAS6lk",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 99.9910899193208,
            "geolocation": {
                "geohash_7": "y0zh77g",
                "geohash_6": "y0zh77",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 49.98778668034447,
                "geohash_9": "y0zh77grc",
                "geohash_8": "y0zh77gr",
                "longitude": 99.9910899193208
            }
        }, {
            "applicants": [],
            "latitude": 49.98651826765737,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "oQxwxbjDd0F56xyIQRlV",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.0007266842588,
            "geolocation": {
                "geohash_7": "y0zh7ef",
                "geohash_6": "y0zh7e",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 49.98651826765737,
                "geohash_9": "y0zh7ef29",
                "geohash_8": "y0zh7ef2",
                "longitude": 100.0007266842588
            }
        }, {
            "applicants": [],
            "latitude": 49.989803363963425,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "pIjVwrGjdstxmRL2LtRX",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 99.98626132650382,
            "geolocation": {
                "geohash_7": "y0zh7hr",
                "geohash_6": "y0zh7h",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 49.989803363963425,
                "geohash_9": "y0zh7hrg8",
                "geohash_8": "y0zh7hrg",
                "longitude": 99.98626132650382
            }
        }, {
            "applicants": [],
            "latitude": 50.00834664175281,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "rMacoII9Brr3kSvuvm1j",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.01648835554931,
            "geolocation": {
                "geohash_7": "y0zh7zt",
                "geohash_6": "y0zh7z",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.00834664175281,
                "geohash_9": "y0zh7ztz9",
                "geohash_8": "y0zh7ztz",
                "longitude": 100.01648835554931
            }
        }, {
            "applicants": [],
            "latitude": 50.00834664175281,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "rMacoII9Brr3kSvuvm1j",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.01648835554931,
            "geolocation": {
                "geohash_7": "y0zh7zt",
                "geohash_6": "y0zh7z",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.00834664175281,
                "geohash_9": "y0zh7ztz9",
                "geohash_8": "y0zh7ztz",
                "longitude": 100.01648835554931
            }
        }, {
            "applicants": [],
            "latitude": 50.00834664175281,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "rMacoII9Brr3kSvuvm1j",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.01648835554931,
            "geolocation": {
                "geohash_7": "y0zh7zt",
                "geohash_6": "y0zh7z",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.00834664175281,
                "geohash_9": "y0zh7ztz9",
                "geohash_8": "y0zh7ztz",
                "longitude": 100.01648835554931
            }
        }, {
            "applicants": [],
            "latitude": 50.00834664175281,
            "description": "This is a test event.",
            "expire_time": "2019-07-06T22:19:37Z",
            "placemark": {
                "zip": "95014",
                "country": "US",
                "city": "Cupertino",
                "google_places_id": "google-inc",
                "name": "GOOGL",
                "street1": "10600 N Tantau Ave",
                "street2": "suit 101",
                "state": "CA"
            },
            "title": "TestEvent - 07/05/2019 15:19:37",
            "host_id": "geotest_user_id",
            "number_of_people": 2,
            "event_type": "INFORMAL",
            "guests": [],
            "id": "rMacoII9Brr3kSvuvm1j",
            "event_time": "2019-07-05T22:19:37Z",
            "is_cancelled": false,
            "longitude": 100.01648835554931,
            "geolocation": {
                "geohash_7": "y0zh7zt",
                "geohash_6": "y0zh7z",
                "geohash_5": "y0zh7",
                "geohash_4": "y0zh",
                "geohash_3": "y0z",
                "geohash_2": "y0",
                "geohash_1": "y",
                "latitude": 50.00834664175281,
                "geohash_9": "y0zh7ztz9",
                "geohash_8": "y0zh7ztz",
                "longitude": 100.01648835554931
            }
        }]
    });
});
```

### Steps to reproduce

Run a firebase emulator using the code above and send a http GET request to path /test.

### Expected behavior

The returned json is partial. Here is the returned json based on the above code:
```json
{"events":[{"applicants":[],"latitude":50.00525403677713,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"BSc0yXZILbaDWgHb0U3o","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":100.01933028798618,"geolocation":{"geohash_7":"y0zh7zp","geohash_6":"y0zh7z","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":50.00525403677713,"geohash_9":"y0zh7zpve","geohash_8":"y0zh7zpv","longitude":100.01933028798618}},{"applicants":[],"latitude":50.01345844676508,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"Hr1FzSbFHXCWQRw9Llbx","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":100.00143075971695,"geolocation":{"geohash_7":"y0zhe8d","geohash_6":"y0zhe8","geohash_5":"y0zhe","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":50.01345844676508,"geohash_9":"y0zhe8dvd","geohash_8":"y0zhe8dv","longitude":100.00143075971695}},{"applicants":[],"latitude":50.01294618070128,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"KUwTov4vU6lfcNm6N38E","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":99.99410144063775,"geolocation":{"geohash_7":"y0zhe2t","geohash_6":"y0zhe2","geohash_5":"y0zhe","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":50.01294618070128,"geohash_9":"y0zhe2t6x","geohash_8":"y0zhe2t6","longitude":99.99410144063775}},{"applicants":[],"latitude":50.00645698648151,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"VPBkHMBOYxrg7TyHYRNu","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":99.98157261550644,"geolocation":{"geohash_7":"y0zh7pk","geohash_6":"y0zh7p","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":50.00645698648151,"geohash_9":"y0zh7pkke","geohash_8":"y0zh7pkk","longitude":99.98157261550644}},{"applicants":[],"latitude":49.98709928565629,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"lp9RwqKLLVcEJsHKMUr1","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":100.00613333202384,"geolocation":{"geohash_7":"y0zh7ey","geohash_6":"y0zh7e","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":49.98709928565629,"geohash_9":"y0zh7ey5z","geohash_8":"y0zh7ey5","longitude":100.00613333202384}},{"applicants":[],"latitude":49.98778668034447,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"m0FWH7RAiGaGyUDAS6lk","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":99.9910899193208,"geolocation":{"geohash_7":"y0zh77g","geohash_6":"y0zh77","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":49.98778668034447,"geohash_9":"y0zh77grc","geohash_8":"y0zh77gr","longitude":99.9910899193208}},{"applicants":[],"latitude":49.98651826765737,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"oQxwxbjDd0F56xyIQRlV","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":100.0007266842588,"geolocation":{"geohash_7":"y0zh7ef","geohash_6":"y0zh7e","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":49.98651826765737,"geohash_9":"y0zh7ef29","geohash_8":"y0zh7ef2","longitude":100.0007266842588}},{"applicants":[],"latitude":49.989803363963425,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"pIjVwrGjdstxmRL2LtRX","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":99.98626132650382,"geolocation":{"geohash_7":"y0zh7hr","geohash_6":"y0zh7h","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":49.989803363963425,"geohash_9":"y0zh7hrg8","geohash_8":"y0zh7hrg","longitude":99.98626132650382}},{"applicants":[],"latitude":50.00834664175281,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"rMacoII9Brr3kSvuvm1j","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":100.01648835554931,"geolocation":{"geohash_7":"y0zh7zt","geohash_6":"y0zh7z","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":50.00834664175281,"geohash_9":"y0zh7ztz9","geohash_8":"y0zh7ztz","longitude":100.01648835554931}},{"applicants":[],"latitude":50.00834664175281,"description":"This is a test event.","expire_time":"2019-07-06T22:19:37Z","placemark":{"zip":"95014","country":"US","city":"Cupertino","google_places_id":"google-inc","name":"GOOGL","street1":"10600 N Tantau Ave","street2":"suit 101","state":"CA"},"title":"TestEvent - 07/05/2019 15:19:37","host_id":"geotest_user_id","number_of_people":2,"event_type":"INFORMAL","guests":[],"id":"rMacoII9Brr3kSvuvm1j","event_time":"2019-07-05T22:19:37Z","is_cancelled":false,"longitude":100.01648835554931,"geolocation":{"geohash_7":"y0zh7zt","geohash_6":"y0zh7z","geohash_5":"y0zh7","geohash_4":"y0zh","geohash_3":"y0z","geohash_2":"y0","geohash_1":"y","latitude":50.00834664175281,"geohash_9":"y0zh7ztz9","geohash_8":"y0zh7ztz","longitude":100.01648835554931}},{"applicants":[],"latitud
```

### Actual behavior

It should return the complete json.

### PR DESCRIPTION
**Pull request by abeisgoat**
We were shutting down the emulator runtime server too quickly which killed the process instead of closing the process after the HTTP server had finished transferring all data. We were also stringifying all incoming data which broke binary data uploading for multi-part uploads

Fixes #1474 
Fixes #1447

### CODE REVIEW

**Comment by samtstern** [comment]
@abeisgoat please add a changelog

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -82,12 +82,12 @@ export class FunctionsEmulator implements EmulatorInstance {
...
-      let data = "";
-      req.on("data", (chunk: any) => {
-        data += chunk;
+      const chunks: Buffer[] = [];
+      req.on("data", (chunk: Buffer) => {
+        chunks.push(chunk);
       });
       req.on("end", () => {
-        (req as RequestWithRawBody).rawBody = data;
+        (req as RequestWithRawBody).rawBody = Buffer.concat(chunks);
```
Comment (samtstern) [inline src/emulator/functionsEmulator.ts]: Does this change `rawBody` from a `string` to `Buffer`?  Is that OK?

Comment (abeisgoat) [reply src/emulator/functionsEmulator.ts]: Yeah it does and that's actually the original mistake. I checked in prod and it's always a buffer and it's explicitly defined as a buffer in [functions-framework](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/invoker.ts#L121)
