### PR TITLE
Tolerate leading/trailing slashes in Firestore paths

### LINKED ISSUE #497: Having a leading "/" in the path will throw an error
### Version info
3.13.1

### Steps to reproduce
1. Create a document inside the collection `/users/` with an id `ViDe80R7HFsCjYq7Dk8k`
2. Run cli command:
```sh
firebase firestore:delete -r "/users/ViDe80R7HFsCjYq7Dk8k"
```

### Expected behavior

Should delete the document @ the path.

### Actual behavior

Throws error
```sh 
Error: Path must not have any empty segments.
```

### Comment
The code that detects empty 'segments' doesn't account for leading or trailing slashes.

https://github.com/firebase/firebase-tools/blob/4535410654cefaf53aec9dbfebec2cdb58045404/lib/firestore/delete.js#L49-L61

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #497

### CODE REVIEW

File: lib/firestore/delete.js [hunk 1]
```diff
@@ -31,6 +31,12 @@ function FirestoreDelete(project, path, options) {
   this.allDescendants = this.recursive;
   this.parent = 'projects/' + project + '/databases/(default)/documents';
 
+  // Remove any leading or trailing slashes from the path
+  if (this.path) {
+    path = path.replace(/^\/+/g, '');
```
Comment (mbleigh) [inline lib/firestore/delete.js]: Nit: this could be one-lined:

    path = path.replace(/(^\/|\/$)/g,'')
