### PR TITLE
Reimplement Storage emulator /internal/setRules

### LINKED ISSUE #5904: /internal/setRules endpoint on the emulator is no longer working for rules unit testing
### [REQUIRED] Environment info

**firebase-tools:** 12.2.1

**Platform:** macOS

### [REQUIRED] Test case

The PR #4902 broke the end point in the `@firebase/rules-unit-testing` package used to setup the storage rules when unit testing ([See broken call](https://github.com/firebase/firebase-js-sdk/blob/df8604e4dada5874ce0513e3376ded130b6231b4/packages/rules-unit-testing/src/impl/rules.ts#L75)).

Therefore this code is no longer working:
```
import {
  initializeTestEnvironment,
} from "@firebase/rules-unit-testing"

beforeAll(async () => {
    testEnv = await initializeTestEnvironment({
      projectId: process.env.GCLOUD_PROJECT,
      storage: {
        rules: fs.readFileSync("../storage.rules", "utf8"),
      },
    })
  })
```

### [REQUIRED] Steps to reproduce

1. Setup the `storage.rules` file
2. Run the test

### [REQUIRED] Expected behavior

Should work like it used to be by loading the `storage.rules` into the emulator using the `/internal/setRules` endpoint.

### [REQUIRED] Actual behavior

```
Not Implemented

      at node_modules/@firebase/rules-unit-testing/src/impl/rules.ts:87:11
      at step (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:74:23)
      at Object.next (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:55:53)
      at fulfilled (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:45:58)
```

### PR DESCRIPTION
**Pull request by tonyjhuang**
### Description

Reimplementing `/internal/setRules` endpoint. Removed in #4902, fixes #5904.

### Scenarios Tested

Tested via https://github.com/aalej/issue-5904

### CODE REVIEW

File: scripts/storage-emulator-integration/internal/tests.ts [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+  beforeEach(async () => {
+    // Reset emulator to default rules.
+    await supertest(STORAGE_EMULATOR_HOST)
+      .put("/internal/setRules")
+      .send({
+        rules: {
+          files: [StorageRulesFiles.readWriteIfAuth],
+        },
+      })
+      .expect(200);
```
Comment (christhompsongoogle) [inline scripts/storage-emulator-integration/internal/tests.ts:35]: In one of the tests can we read the rules back and assert they were set to the expected value?

**Review by christhompsongoogle — APPROVED** [review]
