### PR TITLE
Override Firestore host in emulator runtime

### LINKED ISSUE #2001: firebase-tools used inside emulator callable cloud function deletes production data
### [REQUIRED] Environment info

**firebase-tools:**
7.14.0

**Platform:**
macOS

### [REQUIRED] Test case
See steps below:

### [REQUIRED] Steps to reproduce
Firebase callable function set up as here: https://firebase.google.com/docs/firestore/solutions/delete-collections.

The data present in the emulator was downloaded from production database and imported into the emulator according to the new import/export functionality available in 7.14.0

```ts
import * as tools from "firebase-tools";

export const deleteForever = functions
  .runWith({
    timeoutSeconds: 540,
    memory: "2GB",
  })
  .https.onCall((data, context) => {
     return tools.firestore
       .delete(path, {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        yes: true,
        token: functions.config()?.fb?.token,
    })
    .then(() => path)
}
```
In the browser this is triggered like this:
```ts
firebase.functions.httpsCallable("deleteForever")(item)
```

### [REQUIRED] Expected behavior
Delete item and children in the local firestore emulator database.

### [REQUIRED] Actual behavior
Deletes item and children in the production firestore database. The item is no longer available in the production console.

Basically is there a way to set the `databaseURL` in firebase-tools to point to the local emulator database instead of the production one? (or any other method to force the cli to use the local emulated firestore instance instead of production)

Great job with the new import / export functionality btw. Works really well.

Thank you.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2001 
	 
### Scenarios Tested

I tested the scenario shown in #2001.  It's "fixed" in that no data in prod is affected anymore but it's not fixed because I believe I discovered a bug in the Firestore emulator as a result (https://github.com/firebase/firebase-tools/issues/2010).

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -195,10 +195,10 @@ export class FunctionsEmulator implements EmulatorInstance {
     const bundleTemplate = this.getBaseBundle();
     const runtimeBundle: FunctionsRuntimeBundle = {
       ...bundleTemplate,
-      ports: {
-        firestore: EmulatorRegistry.getPort(Emulators.FIRESTORE),
-        database: EmulatorRegistry.getPort(Emulators.DATABASE),
-        pubsub: EmulatorRegistry.getPort(Emulators.PUBSUB),
+      emulators: {
```
Comment (samtstern) [inline src/emulator/functionsEmulator.ts]: I am now passing host/port info down into the runtime rather than just port.  This was a longstanding bug.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -745,8 +749,18 @@ function initializeEnvironmentalVariables(frb: FunctionsRuntimeBundle): void {
...
 
-  if (frb.ports.pubsub && isFeatureEnabled(frb, "pubsub_emulator")) {
-    const pubsubHost = `localhost:${frb.ports.pubsub}`;
+  // The Firebase CLI is sometimes used as a module within Cloud Functions
+  // for tasks like deleting Firestore data. The CLI has an override system
+  // to change the host for most calls (see api.js)
+  //
+  // TODO(samstern): This should be done for RTDB as well but it's hard
+  // because the convention in prod is subdomain not ?ns=
+  if (frb.emulators.firestore) {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: This is the only behavior change
