### PR TITLE
Fix database emulator rules error parsing. Fix #4454.

### LINKED ISSUE #4454: Realtime Database Emulator crashes with "An unexpected error has occurred." error
## Environment

**Operation System:**
```
$ uname -a
Linux DESKTOP-K3U372K 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Windows: (Host)
```
Edition	Windows 10 Pro
Version	21H1
Installed on	‎19/‎11/‎2020
OS build	19043.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
```

**Browser version:** N/A

**Firebase version:**
```
$ npx firebase --version
10.6.0
$ npm ls firebase
newproject@1.0.0 /home/leonardoraele/Workspace/newproject
├─┬ firebase-tools@10.6.0
│ └── firebase@7.24.0 extraneous
└── firebase@9.6.11
```

**Java:**
```
$ java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)
```

**Firebase Product:** emulators + database

## Problem
Realtime Database Emulator crashes with the error below whenever I make a change to the rules file if there is any error in the json (which always happen as soon as I start typing, unless I paste an already well formated json so that there's no intermidiate state).

```
i  database: Change detected, updating rules for undefined-default-rtdb...

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
```

#### Steps to reproduce:
Here is the sequence of commands executed to reproduce the issue on a new project:
```bash
$ mkdir newproject
$ cd newproject
$ npm init -y
$ npm i -D firebase firebase-tools
$ npx firebase init
? Which Firebase features do you want to set up for this directory? Realtime Database, Emulators
? What file should be used for Realtime Database Security Rules? database.rules.json
? Which Firebase emulators do you want to set up? Press Space to select emulators, then Enter to confirm your choices. Database Emulator
? Which port do you want to use for the database emulator? 9000
? Would you like to enable the Emulator UI? Yes
? Which port do you want to use for the Emulator UI (leave empty to use any available port)? 4000
? Would you like to download the emulators now? Yes
$ npx firebase emulators:start
```

After going through the steps above, the emulator starts running correctly, but it stops with an error when I start making changes to the rules file `database.rules.json` and there's an error in the json.

Example:
```
// This is how the file initially is
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
``` 
```
{
  "rules": {
    ".read": "", // Error: An unexpected error has occurred.
    ".write": "auth != null"
  }
}
```
```
{
  "rules": {
    ".read": "true", // Now it's well formated again, but the emulator is no longer running (I'm not sure which breaks)
    ".write": "auth != null"
  }
}
```

If I try to start the emulator again, there is a port error:
```bash
$ npx firebase emulators:start
i  emulators: Starting emulators: database
i  emulators: Shutting down emulators.
⚠  database: Port 9000 is not open on 127.0.0.1, could not start Database Emulator.
⚠  database: To select a different host/port, specify that host/port in a firebase.json config file:
      {
        // ...
        "emulators": {
          "database": {
            "host": "HOST",
            "port": "PORT"
          }
        }
      }
i  emulators: Shutting down emulators.

Error: Could not start Database Emulator, port taken.
```

**Expected Behavior:** The error should happen, since the file has to go through an intermediary invalid state as I type, but the emulator process should remain running until I finish typing a well formated json.

#### database-debug.log
```
05:55:58.154 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
05:55:58.231 [main] INFO com.firebase.server.forge.App$ - Listening at 127.0.0.1:9000
```

#### firebase-debug.log
```
[debug] [2022-04-18T08:55:56.407Z] ----------------------------------------------------------------------
[debug] [2022-04-18T08:55:56.408Z] Command:       /home/leonardoraele/.nvm/versions/node/v17.6.0/bin/node /home/leonardoraele/Workspace/newproject/node_modules/.bin/firebase emulators:start
[debug] [2022-04-18T08:55:56.408Z] CLI Version:   10.6.0
[debug] [2022-04-18T08:55:56.408Z] Platform:      linux
[debug] [2022-04-18T08:55:56.408Z] Node Version:  v17.6.0
[debug] [2022-04-18T08:55:56.408Z] Time:          Mon Apr 18 2022 05:55:56 GMT-0300 (Brasilia Standard Time)
[debug] [2022-04-18T08:55:56.408Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-04-18T08:55:56.440Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-04-18T08:55:56.441Z] > authorizing via signed-in user (leonardoraele@gmail.com)
[debug] [2022-04-18T08:55:56.464Z] openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)

[debug] [2022-04-18T08:55:56.465Z] OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)

[debug] [2022-04-18T08:55:56.467Z] Parsed Java major version: 17
[info] i  emulators: Starting emulators: database {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: database"}}
[debug] [2022-04-18T08:55:56.470Z] > refreshing access token with scopes: []
[debug] [2022-04-18T08:55:56.471Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2022-04-18T08:55:56.823Z] <<< HTTP RESPONSE 200 {"expires":"Mon, 01 Jan 1990 00:00:00 GMT","date":"Mon, 18 Apr 2022 08:55:57 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2022-04-18T08:55:56.834Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/undefined [none]
[debug] [2022-04-18T08:55:57.552Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/undefined 403
[debug] [2022-04-18T08:55:57.552Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/undefined {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2022-04-18T08:55:57.553Z] HTTP Error: 403, The caller does not have permission
[debug] [2022-04-18T08:55:57.553Z] Failed to retrieve default database instance: {"name":"FirebaseError","children":[],"exit":2,"message":"Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.","original":{"name":"FirebaseError","children":[],"context":{"body":{"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}},"response":{"statusCode":403}},"exit":1,"message":"HTTP Error: 403, The caller does not have permission","status":403},"status":500} {"metadata":{"emulator":{"name":"database"},"message":"Failed to retrieve default database instance: {\"name\":\"FirebaseError\",\"children\":[],\"exit\":2,\"message\":\"Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.\",\"original\":{\"name\":\"FirebaseError\",\"children\":[],\"context\":{\"body\":{\"error\":{\"code\":403,\"message\":\"The caller does not have permission\",\"status\":\"PERMISSION_DENIED\"}},\"response\":{\"statusCode\":403}},\"exit\":1,\"message\":\"HTTP Error: 403, The caller does not have permission\",\"status\":403},\"status\":500}"}}
[debug] [2022-04-18T08:55:57.553Z] database rules config:  [{"instance":"undefined-default-rtdb","rules":"/home/leonardoraele/Workspace/newproject/database.rules.json"}]
[debug] [2022-04-18T08:55:57.556Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"database"},"message":"Ignoring unsupported arg: projectId"}}
[debug] [2022-04-18T08:55:57.556Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"database"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-04-18T08:55:57.556Z] Ignoring unsupported arg: rules {"metadata":{"emulator":{"name":"database"},"message":"Ignoring unsupported arg: rules"}}
[debug] [2022-04-18T08:55:57.556Z] Starting Database Emulator with command {"binary":"java","args":["-Djava.net.preferIPv4Stack=true","-Duser.language=en","-jar","/home/leonardoraele/.cache/firebase/emulators/firebase-database-emulator-v4.7.3.jar","--host","127.0.0.1","--port",9000],"optionalArgs":["port","host","functions_emulator_port","functions_emulator_host"],"joinArgs":false} {"metadata":{"emulator":{"name":"database"},"message":"Starting Database Emulator with command {\"binary\":\"java\",\"args\":[\"-Djava.net.preferIPv4Stack=true\",\"-Duser.language=en\",\"-jar\",\"/home/leonardoraele/.cache/firebase/emulators/firebase-database-emulator-v4.7.3.jar\",\"--host\",\"127.0.0.1\",\"--port\",9000],\"optionalArgs\":[\"port\",\"host\",\"functions_emulator_port\",\"functions_emulator_host\"],\"joinArgs\":false}"}}
[info] i  database: Database Emulator logging to database-debug.log {"metadata":{"emulator":{"name":"database"},"message":"Database Emulator logging to \u001b[1mdatabase-debug.log\u001b[22m"}}
[debug] [2022-04-18T08:55:58.155Z] 05:55:58.154 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
 {"metadata":{"emulator":{"name":"database"},"message":"05:55:58.154 [NamespaceSystem-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started\n"}}
[debug] [2022-04-18T08:55:58.231Z] 05:55:58.231 [main] INFO com.firebase.server.forge.App$ - Listening at 127.0.0.1:9000
 {"metadata":{"emulator":{"name":"database"},"message":"05:55:58.231 [main] INFO com.firebase.server.forge.App$ - Listening at 127.0.0.1:9000\n"}}
[warn] ⚠  emulators: The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag. {"metadata":{"emulator":{"name":"hub"},"message":"The Emulator UI requires a project ID to start. Configure your default project with 'firebase use' or pass the --project flag."}}
[debug] [2022-04-18T08:55:58.318Z] >>> HTTP REQUEST PUT http://127.0.0.1:9000/.settings/rules.json?ns=undefined-default-rtdb  
 {
  "rules": {
    ".read": "true",
    ".write": "auth != null"
  }
}
[debug] [2022-04-18T08:55:58.502Z] <<< HTTP RESPONSE 200 {"content-length":"15","content-type":"application/json; charset=utf-8","access-control-allow-origin":"*","cache-control":"no-cache","x-firebase-project-id":"undefined-default-rtdb","x-firebase-project-number":"123456789","x-firebase-uuid":"1f630beb-087f-4145-8fcd-d013d7ee032d"}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
└─────────────────────────────────────────────────────────────┘

┌──────────┬────────────────┐
│ Emulator │ Host:Port      │
├──────────┼────────────────┤
│ Database │ 127.0.0.1:9000 │
└──────────┴────────────────┘
  Emulator Hub not running.
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 

```

### PR DESCRIPTION
**Pull request by yuchenshi**
### Description

Fix #4454.

### Scenarios Tested

Manually started the emulator with invalid rules, and the CLI now nicely prints the error instead of unknown issue. Then it shuts down all emulators and exit with an error (as before).

Started emulator with valid rules, and edited it to invalid: The CLI now pretty-prints the error correct and won't crash.

Sample valid rules:

```js
{
  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
  "rules": {
    ".read": "true",
    ".write": false
  }
}
```

Sample invalid rules:

```js
{
  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
  1"rules": {  // <-- invalid JSON here
    ".read": "true",
    ".write": false
  }
}
```

```js
{
  /* Visit https://firebase.google.com/docs/database/security to learn more about security rules. */
  "rules": {
    ".read": "", // <-- empty here
    ".write": false
  }
}
```

### Sample Commands

`firebase emulators:start --only database`

### CODE REVIEW

File: src/emulator/databaseEmulator.ts [hunk 1]
```diff
@@ -173,12 +181,41 @@ export class DatabaseEmulator implements EmulatorInstance {
       if (e.context && e.context.body) {
         throw e.context.body.error;
       }
-      throw e.original;
+      if (e.original) {
+        throw e.original;
```
Comment (joehan) [inline src/emulator/databaseEmulator.ts:185]: Nit: Does` throw e.original ?? e` work as I hope it does? If so, i think its slightly more elegant.

File: src/emulator/databaseEmulator.ts [hunk 2]
```diff
@@ -173,12 +181,41 @@ export class DatabaseEmulator implements EmulatorInstance {
...
+      }
+      throw e;
     }
   }
 
-  private prettyPrintRulesError(filePath: string, error: string): string {
+  private prettyPrintRulesError(filePath: string, error: unknown): string {
```
Comment (joehan) [inline src/emulator/databaseEmulator.ts:191]: Optional: This includes some kinda complex type manipulation and casing. If you're up for it, it would be great to add some unit tests for this to make sure if behaves like we expect.

**Review by joehan — APPROVED** [review]
Nits, but LGTM. If you do add unit tests, feel free to rerequest review from me and I'll take another pass

File: src/emulator/databaseEmulator.ts (hunk 1 above)
Comment (yuchenshi) [reply src/emulator/databaseEmulator.ts:185]: https://github.com/firebase/firebase-tools/pull/4490

File: src/emulator/databaseEmulator.ts (hunk 2 above)
Comment (yuchenshi) [reply src/emulator/databaseEmulator.ts:191]: TBH, we don't quite know what RTDB response format looks like so we'd be chasing a moving target anyway. Added a TODO comment though.
