### PR TITLE
Ensure long outputs are written to stdout before exiting process

### LINKED ISSUE #3286: firebase cli --json output is truncated to 64000 bytes when piped to another command
### [REQUIRED] Environment info

**firebase-tools:** 9.10.0

**Platform:** Ubuntu 20.04

### [REQUIRED] Test case

With a project where this outputs more than 64KB, run:

```
firebase ext:list --json | jq
```
This is failing for me, with the output truncating at 64000 bytes

### [REQUIRED] Steps to reproduce

Enable several Firebase extensions in a project
Run a command that pipes the json output to another command, eg:
```firebase ext:list --json | jq```

(or maybe run any firebase cli command that supports --json output, and produces > 64KB).

### [REQUIRED] Expected behavior

Valid json should be piped.

### [REQUIRED] Actual behavior

When piped to another command the JSON seems to be terminated at 64000.

Using the `unbuffer` command seems to workaround this, but ideally this wouldn't be required.

eg, this works as expected:

```
unbuffer firebase ext:list --json | jq
```

### PR DESCRIPTION
**Pull request by joehan**
### Description
A safer take on https://github.com/firebase/firebase-tools/pull/5310 - ensures that we're done writing to stdout before we exit. Fixes #3286

This is necessary due to some slightly unusual behavior of console.log/streams in Node. Writing to stdout (aka calling console.log) can usually be thought of as synchronous action - however, if you write a large enough buffer, it instead behaves asynchronously - https://nodejs.org/docs/v18.17.1/api/stream.html#:~:text=is%20not%20safe.-,Buffering,-%23 lays this out in more detail.

### CODE REVIEW

File: src/command.ts [hunk 1]
```diff
@@ -223,19 +226,25 @@ export class Command {
             );
           }
           process.exit();
+        })
+        .then(async (result) => {
```
Comment (maneesht) [inline src/command.ts:230]: Any reason why this is here?

File: src/command.ts [hunk 2]
```diff
@@ -371,7 +380,7 @@ export class Command {
    * @return an async function that executes the command.
    */
   // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  runner(): (...a: any[]) => Promise<void> {
+  runner(): (...a: any[]) => Promise<any> {
```
Comment (maneesht) [inline src/command.ts:383]: I'm assuming this change is unrelated to the changes above?

File: src/command.ts (hunk 1 above)
Comment (joehan) [reply src/command.ts:230]: Derp, no - remnant of a previous approach I tried that i didn't clean up/

File: src/command.ts (hunk 2 above)
Comment (joehan) [reply src/command.ts:380]: This is actually the 'result' that we're printing out in the main part of this change. 

This was incorrectly typed before - runner() is actually returning whatever is returned by the command's action function.

File: scripts/clean-install.sh [hunk 3]
```diff
@@ -9,6 +9,7 @@ function cleanup() {
 
 trap cleanup EXIT
 
+rm -rf ./clean || true
```
Comment (joehan) [inline scripts/clean-install.sh:12]: This is sort of an unrelated improvement - triggers-end-to-end-test was  sometimes failing because `./clean` already existed when we went to write it, and it was annoying me while I was debugging this.

File: src/command.ts (hunk 2 above)
Comment (maneesht) [reply src/command.ts:380]: Got it. Thanks!

**Review by maneesht — APPROVED** [review]
LGTM
