### PR TITLE
fix Next.js static routes with server actions

### LINKED ISSUE #6653: Nextjs Server Action is not working on hosting
### [REQUIRED] Environment info

**firebase-tools:** 13.0.2

**Platform:** macOS

### [REQUIRED] Test case

Deploying Next js app with form and server actions

### [REQUIRED] Steps to reproduce

- Create an application next js app with npx
- Add React form and Server Action as a form handler(onSubmit)
- Initiate firebase project within the existing next js app
- Deploy to hosting
- Go to the page web.app.mydomain.com/discovery, fill the form and click on submit button

### [REQUIRED] Expected behavior
Should work exactly as in the emulator, i.e. pressing Submit button calls backend function(server action) which does process request.

### [REQUIRED] Actual behavior
Pressing Submit button doesn't call backend function(server action)

### PR DESCRIPTION
**Pull request by leoortizz**
### Description

Fixes #6653

- Require a Cloud Function for static routes with server action
- Skip routes using server action in static routes

### CODE REVIEW

**Review by jamesdaniels — COMMENTED** [review]
LGTM, tackle TODOs. I'll see if `next/index.ts:477-482` is needed or if it's considered a hosting bug. Add changelog.

File: src/frameworks/next/constants.ts [hunk 1]
```diff
@@ -18,5 +18,55 @@ export const PAGES_MANIFEST: typeof PAGES_MANIFEST_TYPE = "pages-manifest.json";
 export const PRERENDER_MANIFEST: typeof PRERENDER_MANIFEST_TYPE = "prerender-manifest.json";
 export const ROUTES_MANIFEST: typeof ROUTES_MANIFEST_TYPE = "routes-manifest.json";
 export const APP_PATHS_MANIFEST: typeof APP_PATHS_MANIFEST_TYPE = "app-paths-manifest.json";
+// TODO: import from next/constants after bumping Next.js dependency
+export const SERVER_REFERENCE_MANIFEST = "server-reference-manifest.json";
 
 export const ESBUILD_VERSION = "0.19.2";
+
+// TODO: import from next/constants after bumping Next.js dependency
```
Comment (leoortizz) [inline src/frameworks/next/constants.ts:26]: @jamesdaniels this depends on #6816

**Review by jamesdaniels — APPROVED** [review]
