### PR TITLE
Tighten up types in firestore delete script

### LINKED ISSUE #3191: Firebase Cloud Functions: Failed to delete documents
### [REQUIRED] Environment info

**firebase-tools: 9.5.0**

**Platform: Firebase Cloud Functions, node 12**

### [REQUIRED] Test case

```
return firestoreTools.delete(path, {
    project: process.env.GCLOUD_PROJECT,
    recursive: true,
    yes: true,
    token: functions.config().fb.token,
  });
```

### [REQUIRED] Steps to reproduce

Trigger the cloud function

### [REQUIRED] Expected behavior

All documents under the given path should be deleted.

### [REQUIRED] Actual behavior

The function call fails without deleting any documents.

### Logs
```
FirebaseError: Failed to delete documents FirebaseError
    at Timeout.<anonymous> (/workspace/node_modules/firebase-tools/lib/firestore/delete.js:266:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) 
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #3191 

The use of `any` in that script meant that some error messages were getting swallowed.

### Scenarios Tested

None, just a types cleanup.

### Sample Commands

N/A

### CODE REVIEW

File: src/firestore/delete.ts [hunk 1]
```diff
@@ -269,22 +278,23 @@ export class FirestoreDelete {
...
       // Return the 'document' property for each element in the response,
       // where it exists.
-      return res.body
-        .filter((x) => {
-          return x.document;
-        })
-        .map((x) => {
-          return x.document;
-        });
+      const docs: Document[] = [];
```
Comment (samtstern) [inline src/firestore/delete.ts:290]: This change is because the compiler couldn't infer the the guarantees on the `.document` field from the `.filter`

File: src/firestore/delete.ts [hunk 2]
```diff
@@ -336,13 +346,13 @@ export class FirestoreDelete {
             queue = queue.concat(docs);
             lastDocName = docs[docs.length - 1].name;
           })
-          .catch((e) => {
+          .catch((e: unknown) => {
             logger.debug("Failed to fetch page after " + lastDocName, e);
             pageIncoming = false;
 
             fetchFailures++;
             if (fetchFailures === 3) {
```
Comment (joehan) [inline src/firestore/delete.ts:354]: Nit: This could be more defensively written as:
```suggestion
            if (fetchFailures >== 3) {
```

**Review by joehan — APPROVED** [review]
LGTM
