### PR TITLE
fix storage targets logic

### LINKED ISSUE #3496: storage deployment to specific target deploy to all targets
When trying to deploy storage rules to a specific target the deployment goes to all targets

### [REQUIRED] Environment info

**firebase-tools:**. 9.13.0

**Platform:** macOS

### [REQUIRED] Test case

"firebase.json":
```
{
...
"storage": [
    {
      "target": "main",
      "rules": "storage.rules"
    },
    {
      "target": "backup",
      "rules": "storage-backup.rules"
    }
  ]
}
```

".firebaserc"
```
{
  "targets": {
    "my-firebase-project": {
      "storage": {
        "backup": [
          "my-firebase-project-backup"
        ],
        "main": [
          "my-firebase-project.appspot.com"
        ]
      }
    }
  }
}
```

### [REQUIRED] Steps to reproduce

deploy only backup target
firebase deploy --only storage:backup

### [REQUIRED] Expected behavior

deploy rules only for the backup target

### [REQUIRED] Actual behavior

i  storage: uploading rules storage.rules...
i  storage: latest version of storage-backup.rules already up to date, skipping upload...
✔  storage: released rules storage-backup.rules to firebase.storage
✔  storage: released rules storage.rules to firebase.storage

### PR DESCRIPTION
**Pull request by bkendall**
### Description

`storage` targets weren't being fully respected. It turned out that while `prepare` was filtering them out, the `release` step was trying to deploy them all anyway. With this update, `release` now looks at an appropriate list for deployment and the only targets are working again.

```
» firebase deploy --only storage

=== Deploying to 'xxx'...

i  deploying storage
i  firebase.storage: checking storage.rules for compilation errors...
i  firebase.storage: checking storage.other.rules for compilation errors...
✔  firebase.storage: rules file storage.other.rules compiled successfully
✔  firebase.storage: rules file storage.rules compiled successfully
i  storage: uploading rules storage.rules...
i  storage: latest version of storage.other.rules already up to date, skipping upload...
✔  storage: released rules storage.other.rules to firebase.storage
✔  storage: released rules storage.rules to firebase.storage

✔  Deploy complete!

Project Console: xxx
» firebase deploy --only storage:storage-other

=== Deploying to 'xxx'...

i  deploying storage
i  firebase.storage: checking storage.other.rules for compilation errors...
✔  firebase.storage: rules file storage.other.rules compiled successfully
i  storage: latest version of storage.other.rules already up to date, skipping upload...
✔  storage: released rules storage.other.rules to firebase.storage

✔  Deploy complete!

Project Console: xxx
```

This completes and...

Fixes #3496

### CODE REVIEW

File: src/deploy/storage/prepare.ts [hunk 1]
```diff
@@ -31,15 +31,12 @@ export default async function (context: any, options: Options): Promise<void> {
     }
   }
 
-  _.set(context, "storage.rules", rulesConfig);
```
Comment (tonyjhuang) [inline src/deploy/storage/prepare.ts:34]: Just out of curiosity, what were these statements doing before?

**Comment by tonyjhuang** [comment]
Thanks for the PR and the cleanup! Are there any tests we can add?

**Review by tonyjhuang — APPROVED** [review]
Thanks for the fix and the tests!
