### PR TITLE
Fix HTTP routing issues

### LINKED ISSUE #1314: Firebase functions emulator does not provide Query params
Request URL and Query params are incorrectly parsed inside functions emulator when the slash **/** is missing at the end of the URL.

### [REQUIRED] Environment info

**firebase-tools:** 6.10.0

**Platform:** macOS 10.14.4

### [REQUIRED] Test case

1. Init functions in the directory with TS enabled.
2. Paste whis code to see the express parsed url or params
```
import * as functions from 'firebase-functions';

export const helloWorld = functions.https.onRequest((request, response) => {
 response.send({
    url: request.url,
    query: request.query
  });
});
```

### [REQUIRED] Steps to reproduce

1. `$ firebase emulators:start`
2. Call the functions with some query params:
a. http://localhost:5001/.../us-central1/helloWorld/?foo=bar&test=string
b. http://localhost:5001/.../us-central1/helloWorld?foo=bar&test=string   (no slash before **?**)

### [REQUIRED] Expected behavior

2. a. => you will get correctly parsed url or query params

### [REQUIRED] Actual behavior

2. b. => url will be "/" and params will be an empty object "{}"

This worked before correctly and it also works when deployed.

### LINKED ISSUE #1325: firebase serve not able to route the `DELETE` http method to the functions
### Environment info

**firebase-tools:** 6.10.0

**Platform:** macOS

### Test case

The functions api has 2 simple test routes, one for `GET` method (just for the sake of proving that the routing is working) and one for the `DELETE` method. APIs are accessed as rewrite from the hosting (http://localhost:5000/**). The test application is available as a git repo at [fbp-issue](https://github.com/anantanandgupta/fbt-issue/tree/master). When we call the `GET` endpoint (http://localhost:5000/api/test-get), it returns the response, whereas the `DELETE` endpoint (http://localhost:5000/api/test-delete) returns the below response:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot DELETE /pg-test-cr/us-central1/api/api/test-delete</pre>
    </body>
</html>
```

### Steps to reproduce

1. clone the above repo in a folder and then install the package dependencies.
2. to run this, you will need to have a firebase project and your cli should have been authenticated (use firebase login or --token $FIREBASE_TOKEN).
3. execute `firebase serve`, and wait for it to host this project locally.
4. use postman or any other tool of your choice to access below:
   - `GET` http://localhost:5000/api/test-get
   - `DELETE` http://localhost:5000/api/test-delete
5. `GET` should be successful whereas the `DELETE` should fail, which is the issue I am trying to report here.

### Expected behavior

the call to the endpoint `DELETE` http://localhost:5000/api/test-delete should return http status 200 with below response body:

```
{
    "ResponseCode": 200,
    "ResponseMessage": "Success",
    "ResponseData": {
        "Message": "This call was successful"
    }
}
```

### Actual behavior

```
[2019-05-21T18:25:35.112Z] ----------------------------------------------------------------------
[2019-05-21T18:25:35.114Z] Command:       /Users/anantanandgupta/.nvm/versions/node/v8.14.0/bin/node /Users/anantanandgupta/.nvm/versions/node/v8.14.0/bin/firebase serve --debug
[2019-05-21T18:25:35.115Z] CLI Version:   6.10.0
[2019-05-21T18:25:35.115Z] Platform:      darwin
[2019-05-21T18:25:35.115Z] Node Version:  v8.14.0
[2019-05-21T18:25:35.116Z] Time:          Tue May 21 2019 23:55:35 GMT+0530 (IST)
[2019-05-21T18:25:35.116Z] ----------------------------------------------------------------------

[2019-05-21T18:25:35.124Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-05-21T18:25:35.124Z] > authorizing via signed-in user
[2019-05-21T18:25:35.124Z] [iam] checking project pg-test-cr for permissions ["firebase.projects.get"]
[2019-05-21T18:25:35.126Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/pg-test-cr:testIamPermissions  
 permissions=[firebase.projects.get]
[2019-05-21T18:25:36.430Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Tue, 21 May 2019 18:25:36 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=1093, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-21T18:25:36.432Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/pg-test-cr  
 
[2019-05-21T18:25:37.723Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Tue, 21 May 2019 18:25:37 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=1160, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked

=== Serving from '/Users/anantanandgupta/Desktop/fbt-issue'...

✔  functions: Using node@8 from host.
[2019-05-21T18:25:37.733Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/964937776990/clients/_:getWebAppConfig  
 
[2019-05-21T18:25:37.734Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/964937776990:getServerAppConfig  
 
[2019-05-21T18:25:38.100Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Tue, 21 May 2019 18:25:38 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
✔  functions: Emulator started at http://localhost:5001
[2019-05-21T18:25:38.344Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Tue, 21 May 2019 18:25:38 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
i  functions: Watching "/Users/anantanandgupta/Desktop/fbt-issue/functions" for Cloud Functions...
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
[2019-05-21T18:25:38.608Z] Functions runtime initialized.
[2019-05-21T18:25:38.608Z] Disabled runtime features: {"functions_config_helper":true,"network_filtering":true,"timeout":true,"memory_limiting":true,"protect_env":true,"admin_stubs":true}
[2019-05-21T18:25:39.024Z] firebase-admin has been stubbed.
i  functions: HTTP trigger initialized at http://localhost:5001/pg-test-cr/us-central1/api
[hosting] Rewriting /api/test-delete to http://localhost:5001/pg-test-cr/us-central1/api for local Function api
127.0.0.1 - - [21/May/2019:18:26:04 +0000] "DELETE /api/test-delete HTTP/1.1" 404 184 "-" "PostmanRuntime/7.13.0"
```

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #1325  (some HTTP methods blocked)
Fixes #1314 (query params lost)

Tested with this simple function:
```js
exports.httpFn = functions.https.onRequest((request, response) => {
    response.send({
        method: request.method,
        path: request.path, 
        query: request.query 
    });
});
```

Simple GET request
```bash
$ http -b GET http://localhost:5001/fir-dumpster/us-central1/httpFn
{
    "method": "GET",
    "path": "/",
    "query": {}
}
```

Simple DELETE request:
```bash
$ http -b DELETE http://localhost:5001/fir-dumpster/us-central1/httpFn
{
    "method": "DELETE",
    "path": "/",
    "query": {}
}
```

GET with query params:
```bash
$ http -b GET "http://localhost:5001/fir-dumpster/us-central1/httpFn?foo=bar&baz=qux"
{
    "method": "GET",
    "path": "/",
    "query": {
        "baz": "qux",
        "foo": "bar"
    }
}
```

GET with query params at subpath:
```bash
$ http -b GET "http://localhost:5001/fir-dumpster/us-central1/httpFn/subpath?foo=bar&baz=qux"
{
    "method": "GET",
    "path": "/subpath",
    "query": {
        "baz": "qux",
        "foo": "bar"
    }
}
```

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -246,9 +244,7 @@ export class FunctionsEmulator implements EmulatorInstance {
     // need to be registered first otherwise the HTTP functions consume
     // all events.
     hub.post(backgroundFunctionRoute, backgroundHandler);
-    hub.post(httpsFunctionRoutes, httpsHandler);
-    hub.get(httpsFunctionRoutes, httpsHandler);
-
+    hub.all(httpsFunctionRoutes, httpsHandler);
```
Comment (abeisgoat) [inline src/emulator/functionsEmulator.ts]: Had no idea this existed, dope.

File: src/test/emulators/functionsEmulatorUtils.spec.ts [hunk 2]
```diff
@@ -93,4 +94,24 @@ describe("FunctionsEmulatorUtils", () => {
       expect(trimSlashes("///a////b//c/")).to.equal("a/b/c");
     });
   });
+
```
Comment (abeisgoat) [inline src/test/emulators/functionsEmulatorUtils.spec.ts]: tests :pray:
