### PR TITLE
Fix issue where projectId and displayName are not getting parsed

### LINKED ISSUE #8634: `firebase projects:create some-project-id` doesn't parse the project ID param
### [REQUIRED] Environment info

**firebase-tools:** v14.4.0

**Platform:** macOS

### [REQUIRED] Test case

```
$ firebase --version
14.4.0
$ firebase projects:create some-project-id
? Please specify a unique project id (warning: cannot be modified afterward) [6-30 characters]:
```

### [REQUIRED] Steps to reproduce

1. Run `firebase projects:create some-project-id`

### [REQUIRED] Expected behavior

The CLI should not prompt for a project ID and the param `some-project-id` should be treated as the project id

Running `$ firebase projects:create --help` shows [projectId] is a valid param
```
Usage: firebase projects:create [options] [projectId]
```

### [REQUIRED] Actual behavior

The CLI prompts for project ID again

### Notes

On v14.2.2, the project id prompt is skipped if the project id param is passed
```
$ firebase --version
14.2.2
$ firebase projects:create some-project-id
? What would you like to call your project? (defaults to your project ID)
```

### PR DESCRIPTION
**Pull request by aalej**
### Description

Fixes #8634

### Scenarios Tested

with [projectId] param
```
$ firebase projects:create some-project-id
? What would you like to call your project? (defaults to your project ID) (some-project-id)
```

```
$ firebase projects:create some-project-id
✔ What would you like to call your project? (defaults to your project ID) some-project-id
✖ Creating Google Cloud Platform project

Error: Failed to create project because there is already a project with ID some-project-id. Please try again with a unique project ID.
```

with [display-name] option
```
$ firebase projects:create some-project-id-0123456 --display-name some-display-name
✔ Creating Google Cloud Platform project
✔ Adding Firebase resources to Google Cloud Platform project

🎉🎉🎉 Your Firebase project is ready! 🎉🎉🎉

Project information:
   - Project ID: some-project-id-0123456
   - Project Name: some-display-name

Firebase console is available at
https://console.firebase.google.com/project/some-project-id-0123456/overview
```

### Sample Commands

`firebase projects:create some-project-id`

### CODE REVIEW

File: src/init/features/project.ts [hunk 1]
```diff
@@ -41,12 +41,12 @@ function toInitProjectInfo(projectMetaData: FirebaseProjectMetadata): InitProjec
   };
 }
 
-async function promptAndCreateNewProject(): Promise<FirebaseProjectMetadata> {
+async function promptAndCreateNewProject(options: any): Promise<FirebaseProjectMetadata> {
```
Comment (joehan) [inline src/init/features/project.ts:44]: this should probably be options: Options, right?

File: src/management/projects.ts [hunk 2]
```diff
@@ -29,35 +29,41 @@ export interface ProjectParentResource {
...
-        return "Project name must be at least 4 characters long";
-      } else if (displayName.length > 30) {
-        return "Project name cannot be longer than 30 characters";
-      } else {
-        return true;
-      }
-    },
-  });
+export async function promptProjectCreation(
+  options: any,
```
Comment (joehan) [inline src/management/projects.ts:33]: Same, probably should use Options as the type here.

**Review by joehan — APPROVED** [review]
LGTM with some type nits.

File: src/init/features/project.ts (hunk 1 above)
Comment (aalej) [reply src/init/features/project.ts:44]: Thanks for the feedback! didn't know we had an `Options` type, will update!
