### PR TITLE
Fix context.auth.uid in callable functions

### LINKED ISSUE #2057: After update to firebase-tools: 7.16.0 emulated callable function context does not includes uid
### Environment info

**firebase-tools:** 7.16.0

**Platform:** macOS

### Test case

1. setup simple WEB project
2. add callable function
3. run callable function in local emulator
4. sign in via phone number on client side
5. call callable function
6. `functions.https.CallableContext` contains `uid` and `token.uid`

### Steps to reproduce

Have firebase-tools 7.16.0
1. setup simple WEB project
2. add callable function
3. run callable function in local emulator
4. sign in via phone number on client side
5. call callable function
-> `functions.https.CallableContext` doesn't contain `uid`. `token` object contains `user_id` but not `uid`.

### Expected behavior

Function context (+ auth token) includes `uid` of signed user.

### Actual behavior

Current `context.auth` looks like:
```
{
    "token": {
        "iss": "https://securetoken.google.com/d21p-dev",
        "aud": "d21p-dev",
        "auth_time": 1585044490,
        "user_id": "ASyoY08brfRoWNxRaBQJVLK4G012",
        "sub": "ASyoY08brfRoWNxRaBQJVLK4G012",
        "iat": 1585044490,
        "exp": 1585048090,
        "phone_number": "+420777123456",
        "firebase": {
            "identities": {
                "phone": [
                    "+420777123456"
                ]
            },
            "sign_in_provider": "phone"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2057

Changes:
  * It turns out that `firebase-functions` manually makes the `uid` field inside the token from the `sub` field, so we have to replicate that behavior.
  * Realized we already had a dependency on `jsonwebtoken` so stopped doing my own parsing.
  * Updated unit tests to use a real token.
	 
### Scenarios Tested

I tested with a local hosting site that calls into the Cloud Functions emulator:

**functions/index.js**
```js
const functions = require('firebase-functions');
const util = require('util');

exports.helloWorld = functions.https.onCall(async (data, context) => {
  console.log("helloWorld", util.inspect(context.auth));
  return {
    auth: context.auth
  };
});
```

**public/index.html**
```html
    <script>
      document.addEventListener('DOMContentLoaded', async function() {
        const auth = firebase.auth();
        firebase.auth().onAuthStateChanged(user => {
          console.log("USER", user);
        });
        await firebase.auth().signInAnonymously();

        firebase.functions().useFunctionsEmulator("http://localhost:5011")
        const helloWorld = firebase.functions().httpsCallable('helloWorld');
        helloWorld({text: "hello"}).then(function(result) {
          console.log(result.data);
        });
      });
    </script>
```

Result in the Chrome debugger:
Screen Shot 2020-03-24 at 9 05 11 AM

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -699,17 +699,18 @@ export class FunctionsEmulator implements EmulatorInstance {
     }
 
     const idToken = match[1];
-    const tokenParts = idToken.split(".");
-
-    if (tokenParts.length < 2) {
-      return;
-    }
+    logger.debug(`ID Token: ${idToken}`);
```
Comment (samtstern) [inline src/emulator/functionsEmulator.ts]: ID tokens expire in an hour so I am not worried about logging this (and it is valuable) but if anyone disagrees I will remove.

File: CHANGELOG.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* Fix issue with `context.auth.uid` in callable Cloud Functions (#2057).
```
Comment (bkendall) [inline CHANGELOG.md]:
```suggestion
* Fixes issue with `context.auth.uid` in callable Cloud Functions for Firebase (#2057).
```

@rachelsaunders will be proud of me.
