### PR TITLE
Make functions:shell respect the port argument

### LINKED ISSUE #1426: functions:shell command does not starts Firestore Emulator with specified port
No matter what port is been set by `--port` argument (even default 5000), the emulator always starts with **given port number plus one**

### [REQUIRED] Environment info

**firebase-tools:** v7.0.1

**Platform:** macOS v10.14.4

### [REQUIRED] Test case

`firebase functions:shell --port 4999`

### [REQUIRED] Steps to reproduce

`firebase functions:shell --port 4999`

### [REQUIRED] Expected behavior

`✔  functions: Emulator started at http://localhost:4999`

### [REQUIRED] Actual behavior

`✔  functions: Emulator started at http://localhost:5000`

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1426
	 
### Scenarios Tested

**New**
```bash
$ npx firebase functions:shell --port 6000
✔  functions: Emulator started at http://localhost:6000
i  functions: Loaded functions: deleteFromFirestore, deleteFromRtdb, writeToFirestore, writeToRtdb, firestoreReaction, rtdbReactio
```

**Old**
```bash
$ npx firebase functions:shell --port 6000
✔  functions: Emulator started at http://localhost:6001
i  functions: Loaded functions: deleteFromFirestore, deleteFromRtdb, writeToFirestore, writeToRtdb, firestoreReaction, rtdbReaction
```

### Sample Commands

N/A

### CODE REVIEW

File: src/serve/functions.ts [hunk 1]
```diff
@@ -31,10 +31,11 @@ module.exports = {
     // we can use the port argument. Otherwise it goes to hosting and
     // we use port + 1.
     if (options.port) {
-      if (options.targets && options.targets.indexOf("hosting") < 0) {
-        args.port = options.port;
-      } else {
+      const hostingRunning = options.targets && options.targets.indexOf("hosting") >= 0;
```
Comment (ryanpbrewster) [inline src/serve/functions.ts]: Under what circumstances is `options.targets` falsey?

Comment (samtstern) [reply src/serve/functions.ts]: hopefully none but `options` is an `any` containing many `any`s and I just sleep better at night like this since `options` is often mutated in random places.

File: package-lock.json [hunk 2]
```diff
@@ -230,7 +230,6 @@
           "resolved": "https://registry.npmjs.org/gaxios/-/gaxios-1.8.4.tgz",
           "integrity": "sha512-BoENMnu1Gav18HcpV9IleMPZ9exM+AvUjrAOV4Mzs/vfz2Lu/ABv451iEXByKiMPn2M140uul1txXCg83sAENw==",
           "dev": true,
-          "optional": true,
```
Comment (ryanpbrewster) [inline package-lock.json]: #npm
