### PR TITLE
Fix Firestore deletion and functions.confg

### LINKED ISSUE #1836: [functions.config()] is EMPTY when running [firebase serve] or [firebase deploy] (using Node.js v10 function environment)
### Related issues
I know some people have complained about this in the past but I can't seem to get this working.

### [REQUIRED] Version info

**node:** v10.15.0

**firebase-functions:** ^3.0.0

**firebase-tools:**

**firebase:** 7.3.2

**firebase-admin:** ^8.0.0

### [REQUIRED] Test case
running **firebase serve** fails to read **functions.config()**

### [REQUIRED] Steps to reproduce

I've tried:
* firebase functions:config:get > .runtimeconfig.json (creates the .json file with my expected config values)
* firebase functions:config:get | ac .runtimeconfig.json (creates the .json with NO config values, just empty .json) - so i have to manually set the file in this case
* I've tried putting the .runtimeconfig.json in the **functions** folder
* I've tried putting the .runtimeconfig.json in the **src** folder
* I've tried putting the .runtimeconfig.json in the **src** & the **functions** folder

### [REQUIRED] Expected behavior
Running **firebase serve** should read **functions.config()**

### [REQUIRED] Actual behavior
**functions.config()** seems to always be empty

This is the location that the code should read **functions.config()** values

 TypeError: Cannot read property 'secret' of undefined
    at Object.<anonymous> (C:\Development\stripe\functions\lib\config.js:13:49)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Development\stripe\functions\lib\source.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

### Were you able to successfully deploy your functions?

No... running **firebase deploy --only functions** gives me the exact same error.
If I replace **functions.config().myValue** with **the actual** value, both **firebase serve** and **firebase deploy** work - but this isn't the intended behavior... I don't want my secret key value exposed in the code 

image

### LINKED ISSUE #2001: firebase-tools used inside emulator callable cloud function deletes production data
### [REQUIRED] Environment info

**firebase-tools:**
7.14.0

**Platform:**
macOS

### [REQUIRED] Test case
See steps below:

### [REQUIRED] Steps to reproduce
Firebase callable function set up as here: https://firebase.google.com/docs/firestore/solutions/delete-collections.

The data present in the emulator was downloaded from production database and imported into the emulator according to the new import/export functionality available in 7.14.0

```ts
import * as tools from "firebase-tools";

export const deleteForever = functions
  .runWith({
    timeoutSeconds: 540,
    memory: "2GB",
  })
  .https.onCall((data, context) => {
     return tools.firestore
       .delete(path, {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        yes: true,
        token: functions.config()?.fb?.token,
    })
    .then(() => path)
}
```
In the browser this is triggered like this:
```ts
firebase.functions.httpsCallable("deleteForever")(item)
```

### [REQUIRED] Expected behavior
Delete item and children in the local firestore emulator database.

### [REQUIRED] Actual behavior
Deletes item and children in the production firestore database. The item is no longer available in the production console.

Basically is there a way to set the `databaseURL` in firebase-tools to point to the local emulator database instead of the production one? (or any other method to force the cli to use the local emulated firestore instance instead of production)

Great job with the new import / export functionality btw. Works really well.

Thank you.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2001
Fixes #1836

### Scenarios Tested

I used the following functions code for testing:
```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp();

const tools = require('firebase-tools');

exports.firestoreDelete = functions.https.onRequest(async (req, res) => {
  console.log("Functions config:", JSON.stringify(functions.config()));
  const db = admin.firestore();

  console.log('Adding');
  for (let i = 0; i < 10; i++) {
    await db.collection('things').add({
      i
    });
  }

  const beforeSnap = await db.collection('things').get();

  console.log('Deleting');
  await tools.firestore.delete('/things', {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        yes: true,
        token: functions.config().fb.token,
  });

  const afterSnap = await db.collection('things').get();
  res.json({
    before: beforeSnap.size,
    after: afterSnap.size
  });
});
```

Here is the test case output:
```bash
$ firebase emulators:exec "http http://localhost:5001/fir-dumpster/us-central1/firestoreDelete" --only functions,firestore
i  emulators: Starting emulators: functions, firestore
✔  hub: emulator hub started at http://localhost:4400
✔  functions: Using node@8 from host.
✔  functions: functions emulator started at http://localhost:5001
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: firestore emulator logging to firestore-debug.log
✔  firestore: firestore emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  functions: Watching "/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.CvrhDdRm/functions" for Cloud Functions...
✔  functions[firestoreDelete]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/firestoreDelete).
i  Running script: http http://localhost:5001/fir-dumpster/us-central1/firestoreDelete
i  functions: Beginning execution of "firestoreDelete"
>  Functions config: {"foo":{"bar":"baz"}}
>  Adding
>  Deleting
⚠  Non-existent functions.config() value requested!
   - Path: "fb.token"
   - Learn more at https://firebase.google.com/docs/functions/local-emulator
⚠  Google API requested!
   - URL: "https://cloudresourcemanager.googleapis.com/v1/projects/fir-dumpster:testIamPermissions"
   - Be careful, this may be a production service.
i  functions: Finished "firestoreDelete" in ~1s
HTTP/1.1 200 OK
connection: keep-alive
content-length: 23
content-type: application/json; charset=utf-8
date: Thu, 19 Mar 2020 14:30:53 GMT
etag: W/"17-+93Ry33n84TmzeDjO+6Fdv3WhfE"
x-powered-by: Express

{
    "after": 0,
    "before": 10
}

✔  Script exited successfully (code 0)
i  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  functions: Stopping functions emulator
i  firestore: Stopping firestore emulator
```

### Sample Commands

N/A

### CODE REVIEW

File: src/api.js [hunk 1]
```diff
@@ -251,12 +251,22 @@ var api = {
     var requestFunction = function() {
       return _request(reqOptions, options.logOptions);
     };
+
+    var secureRequest = true;
```
Comment (samtstern) [inline src/api.js]: This is a fairly large change but IMO safe.  If the options passed to `api.js` include `auth: true` but the resource being accessed is a `http://` endpoint, we don't authorize.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -394,7 +395,7 @@ function initializeNetworkFiltering(frb: FunctionsRuntimeBundle): void {
         .filter((v) => v);
       const href = (hrefs.length && hrefs[0]) || "";
 
-      if (href && !history[href]) {
+      if (href && !history[href] && !href.startsWith("http://localhost")) {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: This prevents logs saying you are accessing an unidentified network resource when you're talking to localhost.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 3]
```diff
@@ -756,7 +769,9 @@ function initializeEnvironmentalVariables(frb: FunctionsRuntimeBundle): void {
   // TODO(samstern): This should be done for RTDB as well but it's hard
   // because the convention in prod is subdomain not ?ns=
   if (frb.emulators.firestore) {
-    process.env.FIRESTORE_URL = `${frb.emulators.firestore.host}:${frb.emulators.firestore.port}`;
+    process.env.FIRESTORE_URL = `http://${frb.emulators.firestore.host}:${
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Not having `http://` here was a straight-up bug but we missed it because we couldn't test this at all until the Firestore emulator's recent token change landed.

File: src/api.js [hunk 4]
```diff
@@ -251,12 +251,22 @@ var api = {
...
+    if (options.origin && options.origin.startsWith("http://")) {
```
Comment (bkendall) [inline src/api.js]: Maybe use the URL module? https://nodejs.org/docs/latest-v8.x/api/url.html#url_constructor_new_url_input_base

You can use `.protocol` to check for `http:`

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (bkendall) [inline src/emulator/functionsEmulatorRuntime.ts]: Maybe use the URL module? https://nodejs.org/docs/latest-v8.x/api/url.html#url_constructor_new_url_input_base

You can get the `.hostname` to check that it's going to `localhost`

File: src/api.js (hunk 4 above)
Comment (samtstern) [reply src/api.js]: Good idea.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: This one I am going to leave because I am actually not sure `href` will always parse nicely and I don't want to risk an error down here.
