### PR TITLE
fix issue with init hosting prompts

### LINKED ISSUE #9403: `firebase init hosting` setup does not prompt for public dir
### [REQUIRED] Environment info

**firebase-tools:** v14.22.0

**Platform:** macOS

### [REQUIRED] Test case

N/A

### [REQUIRED] Steps to reproduce

1. Run `firebase experiments:enable webframeworks`
2. Run `firebase init hosting --project PROJECT_ID`
```
=== Hosting Setup
✔ Do you want to use a web framework? (experimental) No
✔ Set up automatic builds and deploys with GitHub? No
✔  Wrote undefined/404.html
✔  Wrote undefined/index.html

✔  Wrote configuration info to firebase.json
✔  Wrote project information to .firebaserc
✔  Wrote .gitignore

✔  Firebase initialization complete!
```

### [REQUIRED] Expected behavior

The Firebase CLI prompts for the `public` directory and other things related to static hosting

### [REQUIRED] Actual behavior

There are no prompts and the directory set up has folder named `undefined`

Image

### PR DESCRIPTION
**Pull request by aalej**
### Description

Fixes #9403

### Scenarios Tested

Set up on 14.21.0 works, so I'm comparing with that one

#### Plain - blank

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-917b9d7f-7fff-f7ef-45bb-4bbc8d3596f0"><div dir="ltr" style="margin-left:0pt;" align="left">
14.21.0 | Local repo
-- | --
firebase init hosting --project fir-support-testproj | firebase init hosting --project fir-support-testproj
Do you want to use web framework? No | Do you want to use web framework? No
What do you want to use as your public directory? public | What do you want to use as your public directory? public
Configure as single-page app? Yes | Configure as single-page app? Yes
Set up automatic builds and deploys with GitHub? No | Set up automatic builds and deploys with GitHub? No
Directory is setup correctly | Directory is setup correctly

</div></b>

#### Plain - existing

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9d6bfa43-7fff-cfb9-3d07-c2d1ed2ba9a6"><div dir="ltr" style="margin-left:0pt;" align="left">
14.21.0 | Local repo
-- | --
firebase init hosting --project fir-support-testproj | firebase init hosting --project fir-support-testproj
Do you want to use web framework? No | Do you want to use web framework? No
What do you want to use as your public directory? public | What do you want to use as your public directory? public
Configure as single-page app? Yes | Configure as single-page app? Yes
Set up automatic builds and deploys with GitHub? No | File public/index.html already exists. Overwrite? No
File public/index.html already exists. Overwrite? No | Set up automatic builds and deploys with GitHub? No
Directory is setup correctly | Directory is setup correctly

</div></b>

#### WebFramework - blank

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-abe45d07-7fff-4610-517c-3d9b224277dc"><div dir="ltr" style="margin-left:0pt;" align="left">
14.21.0 | Local repo
-- | --
Do you want to use a web framework? Yes | Do you want to use a web framework? (experimental) Yes
What folder would you like to use for your web application's root directory? hosting | What folder would you like to use for your web application's root directory? hosting
Could not determine the web framework in use.Please choose the framework: React | Could not determine the web framework in use.Please choose the framework: React
What language would you like to use? Javascript | In which region would you like to host server-side content, if applicable? us-central1 (Iowa)
In which region would you like to host server-side content, if applicable? us-central1 | What language would you like to use? JavaScript
Set up automatic builds and deploys with GitHub? No | Set up automatic builds and deploys with GitHub? No
Directory is setup correctly | Directory is setup correctly

</div></b>

#### WebFramework - existing

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d1d7efa1-7fff-a9d5-318c-45569fcf35eb"><div dir="ltr" style="margin-left:0pt;" align="left">
14.21.0 | Local repo
-- | --
Do you want to use a web framework? Yes | Do you want to use a web framework? (experimental) Yes
What folder would you like to use for your web application's root directory? hosting | What folder would you like to use for your web application's root directory? hosting
Detected an existing Vite codebase in hosting, should we use this? Yes | Detected an existing Vite codebase in hosting, should we use this? Yes
In which region would you like to host server-side content, if applicable? us-central1 | In which region would you like to host server-side content, if applicable? us-central1 (Iowa)
Set up automatic builds and deploys with GitHub? No | Set up automatic builds and deploys with GitHub? No

</div><br /></b>

### Sample Commands

`firebase init hosting`

### Notes

The arrangements of the prompts are now a little different

Moved he `initGitHub` code to `actuate`
```
if (await confirm("Set up automatic builds and deploys with GitHub?")) {
    return initGitHub(setup);
  }
```
since initGitHub uses `setup.config.hosting` https://github.com/firebase/firebase-tools/blob/be433bc2a18778502b899810aac760c1426669c6/src/init/features/hosting/github.ts#L60-L64

which is only set in the `actuate` method 

https://github.com/firebase/firebase-tools/blob/be433bc2a18778502b899810aac760c1426669c6/src/init/features/hosting/index.ts#L191-L203

----------------

We could also opt for doing

```js
export async function askQuestions(setup: Setup, config: Config, options: Options): Promise<void> {
   ...
   setup.featureInfo.github = await confirm("Set up automatic builds and deploys with GitHub?")
}
```

so we could do 

```js
export async function actuate(setup: Setup, config: Config, options: Options): Promise<void> {
   ...
   if (hostingInfo.github) {
    return initGitHub(setup);
  }
}
```

### CODE REVIEW

File: src/init/features/hosting/index.ts [hunk 1]
```diff
@@ -157,10 +157,6 @@ export async function askQuestions(setup: Setup, config: Config, options: Option
       "Configure as a single-page app (rewrite all urls to /index.html)?",
     );
   }
-  // GitHub Action set up is still structured as doSetup
```
Comment (joehan) [inline src/init/features/hosting/index.ts:160]: I think we still need to keep this in here instead of allowing it into actuate - initGithub includes interactive prompts, and we need actuate to be safe to run noninteractively

Comment (aalej) [reply src/init/features/hosting/index.ts:160]: I'm not sure if can move `initGitHub` into `askQuestions`. `initGitHub` uses `setup.config.hosting` a couple of times, which is only set during `actuate`.

https://github.com/firebase/firebase-tools/blob/be433bc2a18778502b899810aac760c1426669c6/src/init/features/hosting/github.ts#L60-L64

Comment (aalej) [reply src/init/features/hosting/index.ts:160]: Updated, moved `initGitHub` into `askQuestions`.

It looks like the only scenario `Didn't find a Hosting config in firebase.json` will error out is during the setup of a fresh project, otherwise it will correctly pick up the existing config.

During the initial set up with a blank project, I think we can instead use `setup.featureInfo?.hosting` if `setup.config.hosting` does not have values
