### PR TITLE
Fix error message for port conflict

### LINKED ISSUE #1032: Display a dedicated errors when the restPort is already used
### Version info

```
firebase --version
6.1.1
```

### Platform Information
```
OS X
```
### Steps to reproduce

start a server on port 5001
```
http-server . -p 5001
```
and start the firebase `serve` function
```
firebase serve --only functions
```

### Expected behavior

Display an error saying 5001 already in used

https://github.com/firebase/firebase-tools/blob/master/src/functionsEmulator.js#L69

### Actual behavior

```
firebase serve --only functions --debug
[2018-11-23T03:53:25.384Z] ----------------------------------------------------------------------
[2018-11-23T03:53:25.387Z] Command:       /Users/aurelien/.nvm/versions/node/v9.11.2/bin/node /Users/aurelien/.nvm/versions/node/v9.11.2/bin/firebase serve --only functions --debug
[2018-11-23T03:53:25.387Z] CLI Version:   6.1.1
[2018-11-23T03:53:25.387Z] Platform:      darwin
[2018-11-23T03:53:25.387Z] Node Version:  v9.11.2
[2018-11-23T03:53:25.388Z] Time:          Thu Nov 22 2018 22:53:25 GMT-0500 (EST)
[2018-11-23T03:53:25.388Z] ----------------------------------------------------------------------

[2018-11-23T03:53:25.398Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2018-11-23T03:53:25.399Z] > authorizing via signed-in user
[2018-11-23T03:53:25.399Z] [iam] checking project codelab-firebase-b1a97 for permissions ["firebase.projects.get"]
[2018-11-23T03:53:25.400Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/codelab-firebase-b1a97:testIamPermissions
 permissions=[firebase.projects.get]
[2018-11-23T03:53:25.799Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 23 Nov 2018 03:53:25 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-23T03:53:25.801Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/codelab-firebase-b1a97

[2018-11-23T03:53:26.178Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 23 Nov 2018 03:53:26 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close

=== Serving from '/Users/aurelien/Web/nc-firebase/corrections'...

i  functions: Preparing to emulate functions.
[2018-11-23T03:53:26.572Z] Fetching environment
[2018-11-23T03:53:26.576Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/918664590933:getServerAppConfig

[2018-11-23T03:53:26.838Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 23 Nov 2018 03:53:26 GMT, server=ESF, cache-control=private, x-xss-protection=1; mode=block, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="44,43,39,35", accept-ranges=none, connection=close
[2018-11-23T03:53:26.838Z] Starting @google-cloud/functions-emulator
[2018-11-23T03:53:26.871Z] Parsing function triggers
Warning: You're using Node.js v9.11.2 but Google Cloud Functions only supports v6.11.5.
[2018-11-23T03:53:27.007Z] Error while deploying to emulator: TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at Promise (/Users/aurelien/Web/firebase-tools/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:34:42)
    at new Promise (<anonymous>)
    at getService.then (/Users/aurelien/Web/firebase-tools/node_modules/@google-cloud/functions-emulator/src/client/rest-client.js:33:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
⚠  functions: Failed to emulate contributions
```

image

### LINKED ISSUE #1432: Firestore emulator crashes
Hi, 

After updating to version `7.0.1`, the emulator crashes when I try to start Firestore. 

Reproducing: 
`npm i -g firebase-tools@7.0.1`
`firebase serve --only firestore`
Error: 
`Error: firestore: emulator has exited with code: 1`

Any help would be greatly valued😄

Olav

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1432 
Fixes #1032
	 
### Scenarios Tested

**Before**
```bash
$ firebase serve --only firestore
i  firestore: Logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080

Error: firestore: emulator has exited with code: 1
```

**After**
```bash
$ npx firebase serve --only firestore

Error: Port 8080 is not open, could not start firestore emulator.
```

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/registry.ts [hunk 1]
```diff
@@ -16,9 +17,11 @@ export class EmulatorRegistry {
       throw new FirebaseError(`Emulator ${instance.getName()} is already running!`, {});
     }
 
+    // Start the emulator and wait for it to grab its assigned port.
     await instance.start();
-    this.set(instance.getName(), instance);
+    await controller.waitForPortClosed(instance.getInfo().port);
```
Comment (samtstern) [inline src/emulator/registry.ts]: I also moved the `waitForPortClosed()` bit into the registry so that we only mark an emulator as started once it takes its port.
