### PR TITLE
fix: emulator auth_time (#3608)

### LINKED ISSUE #3608: auth_time doesn't match user's lastSignInTime (always matches iat instead)
### [REQUIRED] Describe your environment

- Operating System version: Windows 10 Home Version 20H2, Build 19042.1052
- Browser version: Chrome Version 91.0.4472.164 (64-bit)
- Firebase SDK version: firebase 9.0.0-beta.6
- Firebase Product: Firestore Emulator, Database Emulator, Storage Emulator

### [REQUIRED] Describe the problem

According to the documentation, auth_time should match the user's last sign in time, and iat should match the time this token was issued. This means auth_time should only be updated once, when the user signed in, and iat should change every hour when a new token is issued. This is not the case however. Despite what the documentation says, auth_time changes every hour at the same time as iat. This means auth_time always matches iat, and can't be used in security rules to check the time the user last signed in

https://firebase.google.com/docs/reference/admin/node/admin.auth.DecodedIdToken#auth_time

#### Steps to reproduce:
1. Create the following firestore.rules file
```
rules_version = '2';
service cloud.firestore {
   match /databases/{database}/documents {
    allow read, write: if request.auth != null && request.auth.token.auth_time < request.auth.token.iat;
  }
}
```
2. Use ```npm run serve``` to run the new rules in your local emulators
3. Sign in as a user on your client app.

#### Expected Result:

All reads and writes should fail for about the first hour. But after an hour has passed (and firebase has automatically issued the user a new token) the reads and writes should start succeeding

#### Actual Result:

All reads and writes fail forever. This is because auth_time always changes in lock-step with iat, despite the documentation saying that auth_time should remain stable after login and only iat should change every hour.

### PR DESCRIPTION
**Pull request by lovelle-cardoso**
### Description

Fixes #3608 so that emulator sets auth_time the same way production does (auth_time should match lastLoginAt in seconds)

### Scenarios Tested

Added unit test to src/test/emulators/auth/misc.spec.ts called `"should populate auth_time to match lastLoginAt (in seconds since epoch)"`

This unit test...
1. Registers a user
2. Exchanges a refresh token for a new token
3. Checks that the new token's auth_time matches the user's lastLoginAt in seconds.

### CODE REVIEW

File: src/emulator/auth/operations.ts [hunk 1]
```diff
@@ -1726,7 +1726,11 @@ function generateJwt(
     // This field is only set for anonymous sign-in but not for any other
     // provider (such as email or Google) in production. Let's match that.
     provider_id: signInProvider === "anonymous" ? signInProvider : undefined,
-    auth_time: toUnixTimestamp(new Date()),
+    auth_time: user.lastLoginAt
```
Comment (yuchenshi) [inline src/emulator/auth/operations.ts:1729]:
```suggestion
    auth_time: user.lastLoginAt != null
```

`user.lastLoginAt` may as well be the number zero if it happens at epoch. (This won't happen in real applications, but may happen during tests where we mock out the clock)

File: src/test/emulators/auth/misc.spec.ts [hunk 2]
```diff
@@ -39,6 +44,31 @@ describeAuthEmulator("token refresh", ({ authApi }) => {
...
+    const res = await authApi()
+      .post("/securetoken.googleapis.com/v1/token")
+      .type("form")
+      // snake_case parameters also work, per OAuth 2.0 spec.
+      .send({ refresh_token: refreshToken, grantType: "refresh_token" })
+      .query({ key: "fake-api-key" });
+
+    const idToken = res.body.id_token;
+    const user = await getAccountInfoByIdToken(authApi(), idToken);
+    const lastLoginAtSeconds = user.lastLoginAt
```
Comment (yuchenshi) [inline src/test/emulators/auth/misc.spec.ts:60]: We should add `expect(user.lastLoginAt).not.to.be.undefined` before this -- no need to handle the case where `lastLoginAt` is not set. You can use `new Date(user.lastLoginAt!)` to tell TypeScript it is not null if it complains.

File: src/test/emulators/auth/misc.spec.ts [hunk 3]
```diff
@@ -39,6 +44,31 @@ describeAuthEmulator("token refresh", ({ authApi }) => {
       });
   });
 
+  it("should populate auth_time to match lastLoginAt (in seconds since epoch)", async () => {
+    const emailUser = { email: "alice@example.com", password: "notasecret" };
+    const { refreshToken } = await registerUser(authApi(), emailUser);
+
+    const res = await authApi()
```
Comment (yuchenshi) [inline src/test/emulators/auth/misc.spec.ts:51]: Please advance the mocked clock by a few seconds before this so that we can verify that the auth_time is indeed the login time, not the refresh time. You may use this as an inspiration:

https://github.com/firebase/firebase-tools/blob/66447909ab6f2defd04b257b48193c70d778c7ea/src/test/emulators/auth/oob.spec.ts#L215

**Review by yuchenshi — COMMENTED** [review]
Thanks for the contribution! Looks pretty good to me. A few comments inline for you though. @lisajian will also help with the review

**Review by lisajian — COMMENTED** [review]
Overall, LGTM pending @yuchenshi's feedback. Thank you for the fix!

**Comment by lovelle-cardoso** [comment]
@yuchenshi @lisajian Resolved all 3 comments. I think that's everything! 👍

File: src/test/emulators/auth/misc.spec.ts [hunk 4]
```diff
@@ -39,6 +44,32 @@ describeAuthEmulator("token refresh", ({ authApi }) => {
       });
   });
 
+  it("should populate auth_time to match lastLoginAt (in seconds since epoch)", async () => {
+    const emailUser = { email: "alice@example.com", password: "notasecret" };
+    const { refreshToken } = await registerUser(authApi(), emailUser);
+
+    getClock().tick(2000); // Wait for idToken to be issued in the past.
```
Comment (yuchenshi) [inline src/test/emulators/auth/misc.spec.ts:51]:
```suggestion
    getClock().tick(2000); // Wait 2 seconds before refreshing.
```

File: src/test/emulators/auth/misc.spec.ts [hunk 5]
```diff
@@ -39,6 +44,32 @@ describeAuthEmulator("token refresh", ({ authApi }) => {
...
+    const user = await getAccountInfoByIdToken(authApi(), idToken);
+    expect(user.lastLoginAt).not.to.be.undefined;
+    const lastLoginAtSeconds = toUnixTimestamp(new Date(user.lastLoginAt!));
+    const decoded = decodeJwt(idToken, { complete: true }) as {
+      header: JwtHeader;
+      payload: FirebaseJwtPayload;
+    } | null;
+    expect(decoded, "JWT returned by emulator is invalid").not.to.be.null;
+    expect(decoded!.header.alg).to.eql("none");
+    expect(decoded!.payload.auth_time).to.equal(lastLoginAtSeconds);
```
Comment (yuchenshi) [inline src/test/emulators/auth/misc.spec.ts:70]:
```suggestion
    // This should match login time, not token refresh time.
    expect(decoded!.payload.auth_time).to.equal(lastLoginAtSeconds);
```

**Review by yuchenshi — APPROVED** [review]
LGTM. I'll update the comments and merge after CI passes

**Comment by yuchenshi** [comment]
Apparently linter is not happy about the code formatting, but we'll fix this on our side -- just don't delete your fork branch yet!

**Review by lisajian — APPROVED** [review]

**Comment by yuchenshi** [comment]
This is now merged and will be included in the next release. Thanks again for the help!
