### PR TITLE
Fix #837

### LINKED ISSUE #837: Init wrong rule in firestore.rules file
### Version info

4.0.0

### Platform Information

Ubuntu GNU/Linux (16.04)

### Steps to reproduce

`mkdir [new-dir] && cd $_`
`firebase init`

### Expected behavior

```
service cloud.firestore {...}
```

### Actual behavior

```
service firebase.storage {...}
```

### PR DESCRIPTION
**Pull request by samtstern**
Uses the `releases` API to tell which service we are getting the rules from.

Manual testing (to prove that I can now get either Storage or Firestore rules on demand):

```
samstern@samstern-macbookpro tmp.73XjfHwC
$ echo "Testing with service=firebase.storage"
Testing with service=firebase.storage
samstern@samstern-macbookpro tmp.73XjfHwC
$ ~/Projects/firebase-tools/bin/firebase init firestore

     🔥redacted

You're about to initialize a Firebase project in this directory:

  /private/var/folders/q_/sry2gzmj2tb8xsw3s5x_dz4h00643s/T/tmp.73XjfHwC

Before we get started, keep in mind:

  * You are currently outside your home directory
  * You are initializing in an existing Firebase project directory


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

i  .firebaserc already has a default project, skipping

=== Firestore Setup

Firestore Security Rules allow you to define how and when to allow
requests. You can keep these rules in your project directory
and publish them with firebase deploy.

? What file should be used for Firestore Rules? firestore.rules

Firestore indexes allow you to perform complex queries while
maintaining performance that scales with the size of the result
set. You can keep index definitions in your project directory
and publish them with firebase deploy.

? What file should be used for Firestore indexes? firestore.indexes.json

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
samstern@samstern-macbookpro tmp.73XjfHwC
$ cat firestore.rules
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

```
samstern@samstern-macbookpro tmp.73XjfHwC
$ echo "Testing with service=cloud.firestore"
Testing with service=cloud.firestore
samstern@samstern-macbookpro tmp.73XjfHwC
$ ~/Projects/firebase-tools/bin/firebase init firestore

     🔥redacted

You're about to initialize a Firebase project in this directory:

  /private/var/folders/q_/sry2gzmj2tb8xsw3s5x_dz4h00643s/T/tmp.73XjfHwC

Before we get started, keep in mind:

  * You are currently outside your home directory
  * You are initializing in an existing Firebase project directory


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

i  .firebaserc already has a default project, skipping

=== Firestore Setup

Firestore Security Rules allow you to define how and when to allow
requests. You can keep these rules in your project directory
and publish them with firebase deploy.

? What file should be used for Firestore Rules? firestore.rules

Firestore indexes allow you to perform complex queries while
maintaining performance that scales with the size of the result
set. You can keep index definitions in your project directory
and publish them with firebase deploy.

? What file should be used for Firestore indexes? firestore.indexes.json

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
samstern@samstern-macbookpro tmp.73XjfHwC
$ cat firestore.rules
service cloud.firestore {
  match /databases/{database}/documents {
                match /users/{uid} {
      // Transactions:
      //   read, write -> only the owning user
      match /transactions/{tid} {
        allow read, write: if request.auth.uid == uid;
      }

      // Bills:
      //   read -> only the owning user
      //   write -> only the server
      match /bills/{bid} {
        allow read: if request.auth.uid == uid;
        allow write: if false;
      }
    }
  }
}samstern@samstern-macbookpro tmp.73XjfHwC
$
```

### CODE REVIEW

File: lib/gcp/rules.js [hunk 1]
```diff
@@ -20,24 +21,29 @@ function _handleErrorResponse(response) {
...
-      },
     })
     .then(function(response) {
       if (response.status == 200) {
-        if (response.body.rulesets && response.body.rulesets.length > 0) {
-          return response.body.rulesets[0].name;
+        if (response.body.releases && response.body.releases.length > 0) {
+          var releases = response.body.releases;
+          var prefix = "projects/" + projectId + "/releases/" + service;
+          for (var i = 0; i < releases.length; i++) {
```
Comment (laurenzlong) [inline lib/gcp/rules.js]: use lodash find (https://lodash.com/docs/4.17.10#find). Also, what happens if there are multiple rule releases corresponding to firestore? Is that possible? Are all the previous versions kept around? So then do we need to filter for the latest?

**Comment by samtstern** [comment]
@laurenzlong feedback addressed, thanks!

File: lib/gcp/rules.js [hunk 2]
```diff
@@ -20,24 +23,31 @@ function _handleErrorResponse(response) {
...
+          var releases = _.orderBy(response.body.releases, ["updateTime"], ["desc"]);
 
-        return undefined;
+          var prefix = "projects/" + projectId + "/releases/" + service;
+          var release = _.find(releases, function(r) {
+            return r.name.indexOf(prefix) == 0;
+          });
+
+          if (!release) {
+            throw new FirebaseError("Can't find rules release for service " + service);
```
Comment (laurenzlong) [inline lib/gcp/rules.js]: You don't actually want to throw an error here. If the user doesn't have Firestore rules already, you would want to return null here, so that https://github.com/firebase/firebase-tools/blob/master/lib/init/features/firestore.js#L76 kicks in and the user gets default rules.

**Comment by samtstern** [comment]
@laurenzlong d'oh, good point about the default.  Fixed.
