### PR TITLE
Prefer host from request in storage resumable upload.

### LINKED ISSUE #4374: Storage emulator returning wrong host for upload URL's
### [REQUIRED] Environment info

**firebase-tools:** 10.5.0

**Platform:** macOS

### [REQUIRED] Steps to reproduce

1. create docker contianer with storage emulator in it and make it listen to "host": "0.0.0.0" (so it can be accessed from outside the container)
2. create a second container and try to upload a file to the emulator 

what will happen is that it will try to connect to 0.0.0.0 and it will fail

### [REQUIRED] Expected behavior

the emulator should not return the bind host, instead return the req.hostname

### [REQUIRED] Actual behavior

emulator uses the bing host to determine the host

related issue: https://github.com/googleapis/nodejs-storage/issues/1611

### PR DESCRIPTION
**Pull request by yuchenshi**
### Description

Fixes https://github.com/firebase/firebase-admin-node/issues/1562
Fixes #4374

### Scenarios Tested

See tests added.

### CODE REVIEW

File: src/emulator/auth/utils.ts [hunk 1]
```diff
@@ -170,48 +170,18 @@ export function logError(err: Error): void {
...
-      url.hostname = "[::1]";
-    } else if (info.host.includes(":")) {
-      url.hostname = `[${info.host}]`; // IPv6 addresses need to be quoted using brackets.
-    } else {
-      url.hostname = info.host;
-    }
-    url.port = info.port.toString();
+  if (EmulatorRegistry.getInfo(Emulators.AUTH)) {
+    return EmulatorRegistry.url(Emulators.AUTH);
   } else {
```
Comment (tonyjhuang) [inline src/emulator/auth/utils.ts:182]: unnecessary else

**Review by tonyjhuang — APPROVED** [review]
Thanks for the fix!

File: src/emulator/auth/utils.ts (hunk 1 above)
Comment (yuchenshi) [reply src/emulator/auth/utils.ts:182]: Oops I had automerge on. Next time then...
