### PR TITLE
unset host, if set, before sending proxy cloud run/functions request

### LINKED ISSUE #3012: Firebase serve fails to rewrite URL to containerized app after 8.18.0
### [REQUIRED] Environment info

**firebase-tools:**

$ npx firebase --version
9.1.2

**Platform:**

macOS

### [REQUIRED] Test case

I've create a repo to demonstrate the bug: https://github.com/clarmso/firebase-serve-bug. The repo contains some modified code from examples to demonstrate the bug.

### [REQUIRED] Steps to reproduce

1. Create a firebase project ("firebase-serve-bug") for hosting.
2. Create new project on Google Cloud Platform ("firebase-serve-bug").
3. Clone the repo.
4. cd to `rest-api/`. Enable Cloud Run API, install gcloud beta, containerize the app and deploy the container (See steps 2-3 from https://firebase.google.com/docs/hosting/cloud-run).
5. cd to `ui/`. Run `npm i`.
6. Run `firebase init`. Make sure to select the newly created firebase project in the setup. `.firebaserc` should have the correct project name.
7. Open `.firebase.json`. Ensure the routes to `/api` are rewritten to the Cloud Run service(https://github.com/clarmso/firebase-serve-bug/blob/main/ui/firebase.json#L15). (See step 4 from https://firebase.google.com/docs/hosting/cloud-run)
8. On one terminal, run `npx firebase serve --debug`.
9. On another terminal, run `curl http://localhost:5000/api/v1/hello`.

### [REQUIRED] Expected behavior

v8.18.0 or prior:

curl command is successful:
```
$ curl http://localhost:5000/api/v1/hello
Hello World!
```

Here's the relevant snippet of debug log from firebase:
```
[hosting] Cloud Run rewrite {"source":"/api/**","run":{"serviceId":"firebase-serve-bug","region":"us-central1"}} triggered
[hosting] Looking up Cloud Run service "/v1/projects/firebase-serve-bug-301205/locations/us-central1/services/firebase-serve-bug" for its URL
[2021-01-09T07:22:29.608Z] >>> HTTP REQUEST GET https://run.googleapis.com/v1/projects/firebase-serve-bug-301205/locations/us-central1/services/firebase-serve-bug  
 
[2021-01-09T07:22:29.913Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sat, 09 Jan 2021 07:22:29 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[hosting] Rewriting /api/v1/hello to https://firebase-serve-bug-jg4ma3c3za-uc.a.run.app for Cloud Run service "firebase-serve-bug" for region "us-central1"
[2021-01-09T07:22:29.916Z] >>> [apiv2][query] GET https://firebase-serve-bug-jg4ma3c3za-uc.a.run.app/api/v1/hello 
[2021-01-09T07:22:31.150Z] <<< [apiv2][status] GET https://firebase-serve-bug-jg4ma3c3za-uc.a.run.app/api/v1/hello 200
[2021-01-09T07:22:31.150Z] <<< [apiv2][body] GET https://firebase-serve-bug-jg4ma3c3za-uc.a.run.app/api/v1/hello [stream]
i  hosting: 127.0.0.1 - - [09/Jan/2021:07:22:31 +0000] "GET /api/v1/hello HTTP/1.1" 200 13 "-" "curl/7.64.1" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [09/Jan/2021:07:22:31 +0000] \"GET /api/v1/hello HTTP/1.1\" 200 13 \"-\" \"curl/7.64.1\""}}
```

### [REQUIRED] Actual behavior

curl command failed:
```
$ curl http://localhost:5000/api/v1/hello
An internal error occurred while proxying for Cloud Run service "firebase-serve-bug" for region "us-central1"
```

Here's the relevant snippet of debug log from firebase serve. Note the HTTP 500:
```
[hosting] Cloud Run rewrite {"source":"/api/**","run":{"serviceId":"firebase-serve-bug","region":"us-central1"}} triggered
[hosting] Looking up Cloud Run service "/v1/projects/firebase-serve-bug-301205/locations/us-central1/services/firebase-serve-bug" for its URL
[2021-01-09T07:20:48.695Z] >>> HTTP REQUEST GET https://run.googleapis.com/v1/projects/firebase-serve-bug-301205/locations/us-central1/services/firebase-serve-bug  
 
[2021-01-09T07:20:49.121Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Sat, 09 Jan 2021 07:20:49 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[hosting] Rewriting /api/v1/hello to https://firebase-serve-bug-jg4ma3c3za-uc.a.run.app for Cloud Run service "firebase-serve-bug" for region "us-central1"
[2021-01-09T07:20:49.125Z] >>> [apiv2][query] GET https://firebase-serve-bug-jg4ma3c3za-uc.a.run.app/api/v1/hello 
i  hosting: 127.0.0.1 - - [09/Jan/2021:07:20:49 +0000] "GET /api/v1/hello HTTP/1.1" 500 - "-" "curl/7.64.1" {"metadata":{"emulator":{"name":"hosting"},"message":"127.0.0.1 - - [09/Jan/2021:07:20:49 +0000] \"GET /api/v1/hello HTTP/1.1\" 500 - \"-\" \"curl/7.64.1\""}}
```

### PR DESCRIPTION
**Pull request by bkendall**
### Description

I cannot keep `host` set while proxying as it breaks the outbound request since it won't match the URL we're going for. 

Fixes #3012

### Scenarios Tested

- [x] Proxying to a Cloud Run container.
- [x] Proxying to a Cloud Function.

### CODE REVIEW

File: src/hosting/proxy.ts [hunk 1]
```diff
@@ -68,6 +68,11 @@ export function proxyRequestHandler(url: string, rewriteIdentifier: string): Req
       Cookie: sessionCookie || "",
     });
     for (const key of Object.keys(req.headers)) {
+      // Skip particular header keys:
+      // - using x-forwarded-host, don't need to keep `host` in the headers.
+      if (["host"].includes(key)) {
```
Comment (samtstern) [inline src/hosting/proxy.ts:73]: Why `["host"].includes(key)` and not `key === "host"`?  Was this maybe a longer list at first?

**Review by samtstern — APPROVED** [review]
Approved but please address one comment.

File: src/hosting/proxy.ts (hunk 1 above)
Comment (samtstern) [reply src/hosting/proxy.ts:73]: Then maybe do two lines:
```ts
const headersToDelete = ["host"];

if (headersToDelete.includes(key)) {
```
