### PR TITLE
Preserve Authorization header in callable requests

### LINKED ISSUE #2459: Authorization header is missing from rawRequest in emulator functions.
### Description

Emulator `onCall` functions are missing the Authorization header from the context. Developers may use this header to proxy requests to external services where the user token would be used to verify the user making the call.

### [REQUIRED] Environment info

8.4.3 MacOS

### [REQUIRED] Test case

Use a callable in a client to send a request to an `onCall` function running in the emulator.

### [REQUIRED] Steps to reproduce

1. Create an onCall function that extracts the Authorization header from the context.

`const userToken = context.rawRequest.headers['authorization'].substring(7);`

2. Create a client that sends a request (with signed in user) to the onCall function using callable.
3. Note authorization header is missing from rawRequest

### [REQUIRED] Expected behavior

Authorization header would be available as it is in production.

### [REQUIRED] Actual behavior

Authorization header is missing.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2459 

Basically we stash away the `Authorization` header and restore it just before invoking the handler.

### Scenarios Tested

See unit test.

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -463,6 +463,13 @@ function wrapCallableHandler(handler: CallableHandler): CallableHandler {
       } else {
         logDebug("No callable functions auth found");
       }
+
+      // Restore the original auth header in case the code relies on parsing it (for
+      // example, the code could forward it to another function or server).
+      const originalAuth = context.rawRequest.header(HttpConstants.ORIGINAL_AUTH_HEADER);
+      if (originalAuth) {
+        context.rawRequest.headers["authorization"] = originalAuth;
+      }
```
Comment (yuchenshi) [inline src/emulator/functionsEmulatorRuntime.ts:472]: Please also drop `x-original-auth` so that developers won't rely on that. (Unless production also does that.)

Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts:474]: Good call!
