### PR TITLE
Make serve functions respect the --port flag

### LINKED ISSUE #1265: Serve command does not change Functions Emulator port with --port flag
### [REQUIRED] Environment info

latest : firebase-tools@6.9.1

**firebase-tools:**  6.9.1

**Platform:** macOS

### [REQUIRED] Test case

https://stackoverflow.com/questions/56058087/firebase-functions-admin-firestore-get-throws-auth-error-on-local-serving

### [REQUIRED] Steps to reproduce

I upgraded the tools version to the latest. 
Since then I am not able to set the port number using `firebase serve --only function --port=9000`. 
So started using` firebase emulators:start`.

### [REQUIRED] Expected behavior

Should be able to retrieve the document data from the firestore.

### [REQUIRED] Actual behavior
```
The Cloud Firestore emulator is not running so database operations will fail with a 'default credentials' error.
⚠  Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
>  Auth error:Error: invalid_grant
```
In a bug they had asked to delete application_default_credential.json from ~/.config/gcloud. 
I did that.

After, I got this error:
```
The Cloud Firestore emulator is not running so database operations will fail with a 'default credentials' error. 
⚠ Google API requested! 
- URL: "oauth2.googleapis.com/token" 
- Be careful, this may be a production service. 
> Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See developers.google.com/identity/sign-in/web/devconsole-project.
```
Both the above scenario happens only when get() is used in the firestore collection or document.

Updated serviceaccountkey.json - did not help

----------------------------------------------------------------------
[2019-05-10T04:58:09.087Z] Command:       /usr/local/Cellar/node/11.12.0/bin/node /usr/local/bin/firebase emulators:start --debug
[2019-05-10T04:58:09.087Z] CLI Version:   6.9.1
[2019-05-10T04:58:09.087Z] Platform:      darwin
[2019-05-10T04:58:09.087Z] Node Version:  v11.12.0
[2019-05-10T04:58:09.088Z] Time:          Fri May 10 2019 10:28:09 GMT+0530 (India Standard Time)
[2019-05-10T04:58:09.088Z] ----------------------------------------------------------------------

[2019-05-10T04:58:09.099Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-05-10T04:58:09.099Z] > authorizing via signed-in user
[2019-05-10T04:58:09.101Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[2019-05-10T04:58:09.101Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2019-05-10T04:58:11.290Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 10 May 2019 04:58:11 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-05-10T04:58:11.306Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/travel-wizard-995fa  
 
[2019-05-10T04:58:13.289Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 10 May 2019 04:58:13 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=272, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
i  Starting emulators: ["functions"]
✔  functions: Using node@11 from host.
[2019-05-10T04:58:13.309Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/21058201402:getServerAppConfig  
 
[2019-05-10T04:58:15.296Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Fri, 10 May 2019 04:58:15 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,44,43,39", accept-ranges=none, transfer-encoding=chunked
✔  functions: Emulator started at http://localhost:9000
i  functions: Watching "../gFirebase/functions" for Cloud Functions...
[2019-05-10T04:58:15.654Z] Functions runtime initialized.
[2019-05-10T04:58:15.654Z] Disabled runtime features: undefined
[2019-05-10T04:58:15.987Z] Found google-gax at ../gFirebase/functions/node_modules/google-gax/build/src/index.js
[2019-05-10T04:58:15.987Z] Outgoing network have been stubbed.
[2019-05-10T04:58:16.145Z] Checked functions.config()
[2019-05-10T04:58:16.376Z] firebase-admin has been stubbed.
⚠  Default "firebase-admin" instance created!
i  functions: HTTP trigger initialized at http://localhost:9000/travel-wizard-995fa/us-central1/getUser
i  functions: HTTP trigger initialized at http://localhost:9000/travel-wizard-995fa/us-central1/getTrip
[2019-05-10T04:58:39.964Z] [functions] GET request to function getUser accepted.
[2019-05-10T04:58:39.967Z] [functions] Waiting for runtime to be ready!
[2019-05-10T04:58:40.221Z] Functions runtime initialized.
i  functions: Beginning execution of "getUser"
[2019-05-10T04:58:40.222Z] Disabled runtime features: undefined
[2019-05-10T04:58:40.596Z] Found google-gax at ../gFirebase/functions/node_modules/google-gax/build/src/index.js
[2019-05-10T04:58:40.596Z] Outgoing network have been stubbed.
[2019-05-10T04:58:40.723Z] Checked functions.config()
[2019-05-10T04:58:40.970Z] firebase-admin has been stubbed.
⚠  Default "firebase-admin" instance created!
[2019-05-10T04:58:41.028Z] Trigger "getUser" has been found, beginning invocation!
[2019-05-10T04:58:41.029Z] 
[2019-05-10T04:58:41.029Z] Running getUser in mode HTTPS
[2019-05-10T04:58:41.035Z] {"socketPath":"/var/folders/9v/qyy4ytsj72150lcsmqnj3xc97fzvrl/T/firebase_emulator_invocation_32894.sock"}
[2019-05-10T04:58:41.035Z] [functions] Runtime ready! Sending request! {"socketPath":"/var/folders/9v/qyy4ytsj72150lcsmqnj3xc97fzvrl/T/firebase_emulator_invocation_32894.sock"}
[2019-05-10T04:58:41.041Z] Ephemeral server used!
>  Entered get User - User class
⚠  The Cloud Firestore emulator is not running so database operations will fail with a 'default credentials' error.
⚠  Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
>  Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[2019-05-10T04:58:50.219Z] Ephemeral server survived.
i  functions: Finished "getUser" in ~9s

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #1265 

Test cases:

**firebase serve**
```
$ npx firebase serve

=== Serving from '/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.wuBSDpsc'...

i  functions: Preparing to emulate functions.
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:5000
✔  functions: httpToDbFn: http://localhost:5001/fir-dumpster/us-central1/httpToDbFn
✔  functions: callableFn: http://localhost:5001/fir-dumpster/us-central1/callableFn
✔  functions: httpToFirestoreFn: http://localhost:5001/fir-dumpster/us-central1/httpToFirestoreFn
✔  functions: httpFn: http://localhost:5001/fir-dumpster/us-central1/httpFn
```

**firebase serve --only hosting --port 9000**
```
$ npx firebase serve --only hosting --port 9000

=== Serving from '/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.wuBSDpsc'...

i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:9000
```

**firebase serve --only functions --port 9000**
```
$ npx firebase serve --only functions --port 9000

=== Serving from '/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.wuBSDpsc'...

i  functions: Preparing to emulate functions.
✔  functions: httpFn: http://localhost:9000/fir-dumpster/us-central1/httpFn
✔  functions: httpToFirestoreFn: http://localhost:9000/fir-dumpster/us-central1/httpToFirestoreFn
✔  functions: httpToDbFn: http://localhost:9000/fir-dumpster/us-central1/httpToDbFn
✔  functions: callableFn: http://localhost:9000/fir-dumpster/us-central1/callableFn
```

**firebase serve --port 9000**
```
$ npx firebase serve --port 9000

=== Serving from '/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.wuBSDpsc'...

i  functions: Preparing to emulate functions.
i  hosting: Serving hosting files from: public
✔  hosting: Local server: http://localhost:9000
✔  functions: httpToFirestoreFn: http://localhost:9001/fir-dumpster/us-central1/httpToFirestoreFn
✔  functions: callableFn: http://localhost:9001/fir-dumpster/us-central1/callableFn
✔  functions: httpToDbFn: http://localhost:9001/fir-dumpster/us-central1/httpToDbFn
✔  functions: httpFn: http://localhost:9001/fir-dumpster/us-central1/httpFn
```

### CODE REVIEW

File: src/serve/functions.ts [hunk 1]
```diff
@@ -7,21 +7,32 @@ module.exports = {
...
+    };
+
+    // If hosting emulator is not being served but Functions is,
+    // we can use the port argument. Otherwise it goes to hosting and
+    // we use port + 1.
+    if (this.options.port) {
+      if (this.options.targets && this.options.targets.indexOf("hosting") < 0) {
+        args.port = this.options.port;
+      } else {
+        args.port = this.options.port + 1;
```
Comment (abeisgoat) [inline src/serve/functions.ts]: Is there any chance of this colliding with the port used for another emulator if I did like `--only functions,firestore`?

Comment (samtstern) [reply src/serve/functions.ts]: Only if you choose `8078` or `8079` basically and I think we should stop having people use `serve` for Firestore/RTDB anymore.

Comment (samtstern) [reply src/serve/functions.ts]: Actually it turns out that `--only functions,firestore` never worked correctly (and still doesn't).  It starts Firestore only.  So no.
