### PR TITLE
Fix port issues in WSL

### LINKED ISSUE #1458: `firebase emulators:start` not working on WLS on Windows 10
### [REQUIRED] Environment info

**firebase-tools:**
7.0.2

**Platform:**
WSL on Windows 10

### [REQUIRED] Test case

An empty project with the auto-generated Cloud Functions boilerplate is enough to reproduce it.

### [REQUIRED] Steps to reproduce

Run `firebase emulators:start`

### [REQUIRED] Expected behavior

I should be able to use the local environment.

### [REQUIRED] Actual behavior

It starts the local server at port 5001, if I open it in Chrome I get a `{ "status": "alive" }` response, but after 30 seconds it shuts down by itself because of a "timeout".

```
✔  functions: Emulator started at http://localhost:5001
i  Shutting down emulators.
i  Stopping functions emulator

Error: TIMEOUT: Port 5001 was not active within 30000ms
```

The project works fine when deployed to Google Cloud. I tried to run it with `sudo` also.

If I visit the demo "hello world" endpoint I get an error saying the endpoint is not available.

I tried to run it with `--debug` but no additional information is displayed during the shutdown/timeout

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1458 

I don't know why but `portfinder` always reported all ports as free in WSL which means that we couldn't wait for the port to be occupied.

I used a new library, which also simplified the code because it came with a port-waiting function.
	 
### Scenarios Tested

Tested manually on WSL.

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/controller.ts [hunk 1]
```diff
@@ -1,9 +1,12 @@
 import * as _ from "lodash";
 import * as clc from "cli-color";
 import * as fs from "fs";
-import * as pf from "portfinder";
 import * as path from "path";
 
+// No typings exist for this library.
+// tslint:disable-next-line:no-var-requires
+const tcpport = require("tcp-port-used");
```
Comment (bkendall) [inline src/emulator/controller.ts]: Can you use `@types/tcp-port-used` for the types?

Comment (samtstern) [reply src/emulator/controller.ts]: D'oh

**Comment by samtstern** [comment]
@bkendall portfinder is still used in some places of the CLI.  It does something different, which is find an open port within a range.

I think it's broken on WSL but I don't think it matters for the emulators anymore and I don't want to touch anyone else's code.
