### PR TITLE
Make Extensions TOS calls best effort

### LINKED ISSUE #6060: Deploying Extensions with a Service Account on GH Actions and Locally fails
### [REQUIRED] Environment info

**firebase-tools:12.4.2**

**Platform:macOS**

### [REQUIRED] Test case

I'm trying to deploy Firebase extensions while authorized with a service account on a GH Action workflow and am getting the following error:

```
i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  extensions: ensuring required API secretmanager.googleapis.com is enabled...
✔  extensions: required API secretmanager.googleapis.com is enabled
i  extensions: ensuring required API compute.googleapis.com is enabled...
✔  extensions: required API compute.googleapis.com is enabled
The following extension instances will be configured:
	firestore-bigquery-export (firebase/firestore-bigquery-export@0.1.32)
	firestore-send-email (firebase/firestore-send-email@0.1.26)

i  extensions: By installing an extension instance onto a Firebase project, you accept the Firebase Extensions User Terms of Service: https://firebase.google.com/terms/extensions/user

Error: HTTP Error: 403, Firebase Extensions Terms of Service Private API has not been used in project XXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Error: Process completed with exit code 1.
```

Trying to access <https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=XXX> (with my project id) gives an error: "Failed to load".
I'm not sure why it asks for accepting terms of service, as I accepted the terms while deploying locally with my Google account logged in.

I've also tried deploying extensions locally, which worked when Firebase CLI is logged in with my Google account (Firebase project owner) but fails with the service account with a different error:

```
Error: Errors while reading 'extensions' in 'firebase.json'
- HTTP Error: 403, Your application is authenticating by using local Application Default Credentials. The firebaseextensions.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
- HTTP Error: 403, Your application is authenticating by using local Application Default Credentials. The firebaseextensions.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
```

How can I use a service account to deploy Firebase including extensions?

### [REQUIRED] Steps to reproduce

On GH Actions:

Deploy a firebase project with extensions enabled on GH Actions with a service account:

```
name: Deploy to Firebase Staging
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: w9jds/setup-firebase@v1.0.0
        with:
          tools-version: 12.4.2
          gcp_sa_key: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
      - run: firebase deploy --except hosting --project staging
        working-directory: firebase
```

Locally:

1. Open your firebase project with extensions enabled in terminal.
2. Log out of Firebase CLI: `firebase logout`
3. Authenticate with a service account key: `export GOOGLE_APPLICATION_CREDENTIALS='path/to/key.json'`
4. Run `firebase deploy --only extensions --project staging`

### [REQUIRED] Expected behavior

I would expect the service account to be able to deploy the whole Firebase project including extensions.

### [REQUIRED] Actual behavior

Deploying with service account fails on GH action with:

```
Error: HTTP Error: 403, Firebase Extensions Terms of Service Private API has not been used in project XXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
Error: Process completed with exit code 1.
```

and locally with:

```
Error: Errors while reading 'extensions' in 'firebase.json'
- HTTP Error: 403, Your application is authenticating by using local Application Default Credentials. The firebaseextensions.googleapis.com API requires a quota project, which is not set by default. To learn how to set your quota project, see https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
```

### PR DESCRIPTION
**Pull request by joehan**
### Description
Make calls to check and accept the Extensions TOS best effort. We have backend checks for these in place, so this should be safe.

When users who are authenticated via a service account (ie CI/CD pipelines) try to deploy extensions, calls to the private TOS API end up being done on the service accounts project instead of the CLI's OAuth project. This fails, because this API cannot be enabled on external projects.

Fixes #6060.

### Scenarios Tested
Tested that I can successfully deploy as a service account (and verified that the call was attempted & failed via the debug logs).
Tested that I can successfully deploy as a normal login'd user, and that the TOS check still succeeds and records acceptance.

### CODE REVIEW

File: src/auth.ts [hunk 1]
```diff
@@ -702,8 +702,8 @@ async function refreshTokens(
   }
 }
 
-export async function getAccessToken(refreshToken: string, authScopes: string[]) {
-  if (haveValidTokens(refreshToken, authScopes)) {
+export async function getAccessToken(refreshToken: string, authScopes: string[]): Promise<Tokens> {
```
Comment (joehan) [inline src/auth.ts:705]: The changes to auth.ts and apiv2.ts are somewhat unrelated clean up - i spent a bunch of time poking around these files trying to understand the issue, so I did some tidying up while i was there.
