### PR TITLE
Fix Angular SSR deployment on Windows

### LINKED ISSUE #6543: Angular 17 SSR deployment does not work on windows
### [REQUIRED] Environment info

**firebase-tools:** The current `master` branch with Commit https://github.com/firebase/firebase-tools/commit/721c33015c3b160570a4af1a916da77797e2e991

**Platform:** Windows

### [REQUIRED] Test case

- Generate a new Angular 17 SSR enabled application
- Setup firebase deployment with the web frameworks feature
- Add `"firebase-tools": "firebase/firebase-tools#master",` to your `package.json` and run `npm install` to use the current `master` branch

### [REQUIRED] Steps to reproduce

- Run `npx firebase deploy` on Windows
- Open the browser and access our deployed app

### [REQUIRED] Expected behavior

Running `npx firebase deploy` on Windows generates a valid Angular SSR function.

### [REQUIRED] Actual behavior

Look at the Google Cloud Function Logs and find the following error. Note the slashes are missing. The required module is actually located at `/workspace/dist/your-project-name/server/server.mjs`
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspace/distyour-project-nameserver/server.mjs' imported from /workspace/bootstrap.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:524:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21)
```

To verify this look at the `bootstrap.js` file in the `.firebase/<your-project-id>/functions` and see the path to the `server.mjs` 
 contains backslashes: `./dist\your-project-name\server/server.mjs`

### PR DESCRIPTION
**Pull request by sonallux**
### Description

This PR fixes #6543 by replacing all backslashes in the `serverOutputPath` with normal slashes.

### Scenarios Tested

I have successfully deployed an Angular 17 SSR App with my changes and the Cloud Functions to not error anymore and the path in the generated `bootstrap.js` is correct.

### Sample Commands

None

### CODE REVIEW

File: src/frameworks/angular/index.ts [hunk 1]
```diff
@@ -238,10 +239,11 @@ exports.handle = function(req,res) {
   });
 };\n`;
   } else if (serverOutputPath) {
+    const serverOutputPosixPath = serverOutputPath.split(sep).join(posix.sep);
```
Comment (9kubczas4) [inline src/frameworks/angular/index.ts:242]: I'd suggest setting the values of the correct paths directly in the `getServerConfig` function.
We can adjust both: `serverOutputPath` and `browserOutputPath`.

What do you think?

Comment (sonallux) [reply src/frameworks/angular/index.ts:242]: Yes, I do like this idea 👍

Comment (sonallux) [reply src/frameworks/angular/index.ts]: I have changed it, to correct the paths directly in the `getServerConfig` function.

**Review by 9kubczas4 — APPROVED** [review]
LGTM

**Review by jamesdaniels — CHANGES_REQUESTED** [review]

File: src/frameworks/angular/utils.ts [hunk 2]
```diff
@@ -420,7 +420,7 @@ export async function getServerConfig(sourceDir: string, configuration: string)
   }
   const browserTargetOptions = await architectHost.getOptionsForTarget(buildOrBrowserTarget);
   assertIsString(browserTargetOptions?.outputPath);
-  const browserOutputPath = join(browserTargetOptions.outputPath, buildTarget ? "browser" : "");
+  const browserOutputPath = join(browserTargetOptions.outputPath, buildTarget ? "browser" : "").split(sep).join(posix.sep);
```
[the remark this answers is not in the document]
Comment (sonallux) [reply src/frameworks/angular/utils.ts]: @jamesdaniels I have fixed the linter errors.

**Review by jamesdaniels — APPROVED** [review]
