### PR TITLE
Shorten socket paths

### LINKED ISSUE #1815: firebase-tools serve makes an error
### [REQUIRED] Environment info

**firebase-tools: 7.8.0 (the latest)

**Platform: macOS

### [REQUIRED] Test case

firebase functions
> project
>> functions
>> index.js : exports.posts = functions.https.onRequest(require('./posts')); exports.posts = functions.https.onRequest(require('./accounts'));
>>> posts : index.js : const app = require('express')(); const cors = require('cors'); app.use(cors({ origin: true })); app.get('/', async (req, res) => { });
>>> accounts: index.js : const app = require('express')(); const cors = require('cors'); app.use(cors({ origin: true })); app.get('/', async (req, res) => { });

### [REQUIRED] Steps to reproduce

firebase functions + express get / post methods
request multiple get requests, it makes errors.
it is only made on firebase-tools 7.8.0.
if I run the same codes on firebase-tools 7.7.0., it works fine.

### [REQUIRED] Expected behavior

If I request multiple requests, it accepts well and perform.

### [REQUIRED] Actual behavior

it makes an error

```
i  functions: Beginning execution of "accounts"
[2019-11-19T10:17:42.957Z] [runtime-status]  {"httpsTrigger":{},"name":"accounts","entryPoint":"accounts"}
[2019-11-19T10:17:42.957Z] [runtime-status] Running accounts in mode HTTPS {}
[2019-11-19T10:17:42.962Z] [functions] Runtime ready! Sending request!
[2019-11-19T10:17:42.968Z] [runtime-status] Ephemeral server used! {}
[2019-11-19T10:17:43.003Z] [runtime-status] Ephemeral server survived. {}
[2019-11-19T10:17:43.339Z] Accepted request OPTIONS /~/posts/rT7UgEMG8KhTlLOADE3y/comments --> posts
[2019-11-19T10:17:43.339Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: Assigning socketPath: /var/folders/zp/903b9f055r1czvjktw3fg_7r0000gn/T/firebase_emulator_invocation_3a43686e-d66c-4835-a45e-b4be49366232.sock
[2019-11-19T10:17:43.339Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: BUSY
[2019-11-19T10:17:43.339Z] [runtime-status] Trigger "posts" has been found, beginning invocation! {}
i  functions: Beginning execution of "posts"
[2019-11-19T10:17:43.340Z] [runtime-status]  {"httpsTrigger":{},"name":"posts","entryPoint":"posts"}
[2019-11-19T10:17:43.340Z] [runtime-status] Running posts in mode HTTPS {}
>  events.js:174
>        throw er; // Unhandled 'error' event
>        ^
>  
>  Error: listen EADDRINUSE: address already in use /var/folders/zp/903b9f055r1czvjktw3fg_7r0000gn/T/firebase_emulator_invocation_3a43686e-d66c-4835-a45e-b4be49366232.sock
>      at Server.setupListenHandle [as _listen2] (net.js:1263:19)
>      at listenInCluster (net.js:1328:12)
>      at Server.listen (net.js:1426:5)
>      at Function.listen (/Users/mmj/.npm-global/lib/node_modules/firebase-tools/node_modules/express/lib/application.js:618:24)
>      at Promise (/Users/mmj/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:563:46)
>      at new Promise (<anonymous>)
>      at /Users/mmj/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:528:15
>      at Generator.next (<anonymous>)
>      at /Users/mmj/.npm-global/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
>      at new Promise (<anonymous>)
>  Emitted 'error' event at:
>      at emitErrorNT (net.js:1307:8)
>      at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-11-19T10:17:43.352Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: exited
[2019-11-19T10:17:43.353Z] [worker-posts-3a43686e-d66c-4835-a45e-b4be49366232]: FINISHED
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1815 

This was one of the hardest bugs to find I've ever messed with.  In #1778 we started assigning socket paths like this:
```
/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/firebase_emulator_invocation_5d718fae-4531-49e1-8510-d3c0606adced.sock
```

Then we got strange `EADDRINUSE` errors on the  second invocation.  Well it turns out:
https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections

> On Unix, the local domain is also known as the Unix domain. The path is a filesystem pathname. It gets truncated to a length of sizeof(sockaddr_un.sun_path) - 1, which varies 91 and 107 bytes depending on the operating system. The typical values are 107 on Linux and 103 on macOS.

Our paths were in the ~119 range.  So ... yeah.

### Scenarios Tested

Making Requests:
```
$ http http://localhost:5001/fir-dumpster/us-central1/helloHTTP/1.1 200 OK
connection: keep-alive
content-length: 20
content-type: text/html; charset=utf-8
date: Wed, 20 Nov 2019 00:01:52 GMT
etag: W/"14-z3iZXchEt5DVWZKsMncy8Wl4KSQ"
x-powered-by: Express

Hello from Firebase!

$ http http://localhost:5001/fir-dumpster/us-central1/hello
HTTP/1.1 200 OK
connection: keep-alive
content-length: 20
content-type: text/html; charset=utf-8
date: Wed, 20 Nov 2019 00:01:53 GMT
etag: W/"14-z3iZXchEt5DVWZKsMncy8Wl4KSQ"
x-powered-by: Express

Hello from Firebase!
```

Emulator Logs:
```
i  functions: Beginning execution of "hello"
i  functions: Finished "hello" in ~1s
i  functions: Beginning execution of "hello"
i  functions: Finished "hello" in ~1s
```

Unfortunately I can't easily add a `mocha` test for this because the mocha tests don't re-use  function runtimes.

### Sample Commands

See #1815

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -141,14 +140,14 @@ export class FunctionsEmulator implements EmulatorInstance {
       req: express.Request,
       res: express.Response
     ) => {
-      this.handleBackgroundTrigger(req, res);
+      await this.handleBackgroundTrigger(req, res);
```
Comment (yuchenshi) [inline src/emulator/functionsEmulator.ts]: Why this change? Also, I'll save the bikeshedding about why async/await stuff here is misleading, but you get the idea.

File: src/emulator/functionsEmulatorShared.ts [hunk 2]
```diff
@@ -134,13 +134,13 @@ export function getEmulatedTriggersFromDefinitions(
...
-export function getTemporarySocketPath(id: string, cwd: string): string {
+export function getTemporarySocketPath(pid: number, cwd: string): string {
   // See "net" package docs for information about IPC pipes on Windows
   // https://nodejs.org/api/net.html#net_identifying_paths_for_ipc_connections
   if (process.platform === "win32") {
-    return path.join("\\\\?\\pipe", cwd, id.toString());
+    return path.join("\\\\?\\pipe", cwd, pid.toString());
   } else {
-    return path.join(os.tmpdir(), `firebase_emulator_invocation_${id}.sock`);
+    return path.join(os.tmpdir(), `fire_emu_${pid.toString()}.sock`);
```
Comment (yuchenshi) [inline src/emulator/functionsEmulatorShared.ts]: Please please please do add a comment that the sock must be within x to y characters long or etc. etc. from the PR description.

File: src/emulator/functionsEmulator.ts (hunk 1 above)
Comment (samtstern) [reply src/emulator/functionsEmulator.ts]: Oh yeah I need to revert this.  This was me messing around while investigating.

File: src/emulator/emulatorLogger.ts [hunk 3]
```diff
@@ -84,7 +84,7 @@ export class EmulatorLogger {
         EmulatorLogger.log("USER", `${clc.blackBright("> ")} ${log.text}`);
         break;
       case "DEBUG":
-        if (log.data && log.data !== {}) {
+        if (log.data && Object.keys(log.data).length > 0) {
```
Comment (samtstern) [inline src/emulator/emulatorLogger.ts]: In ES5, if the argument to this method is not an object (a primitive), then it will cause a TypeError. In ES2015, a non-object argument will be coerced to an object.

File: src/emulator/functionsEmulatorShared.ts [hunk 4]
```diff
@@ -134,13 +134,24 @@ export function getEmulatedTriggersFromDefinitions(
...
+  //
+  // As noted in the linked documentation the socket path is truncated at a certain
+  // length:
+  // > On Unix, the local domain is also known as the Unix domain. The path is a filesystem pathname.
+  // > It gets truncated to a length of sizeof(sockaddr_un.sun_path) - 1, which varies 91 and 107 bytes
+  // > depending on the operating system. The typical values are 107 on Linux and 103 on macOS.
+  //
+  // On Mac our socket paths will begin with something like this:
+  //   /var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/{...}.sock
+  // Since the system prefix is about ~50 chargs we only have about ~50 more to work with
```
Comment (yuchenshi) [inline src/emulator/functionsEmulatorShared.ts]:
```suggestion
  // Since the system prefix is about ~50 chars we only have about ~50 more to work with
```
