### PR TITLE
Fix function deploy retry after quota exceeded bug and increase backoff

### LINKED ISSUE #5474: Firebase `deploy --only functions` does not retry deployment after a `quota exceeded` error.
### [REQUIRED] Environment info

**firebase-tools:**
11.20.0

**Platform:**
macOS
### [REQUIRED] Test case

We have a project with 342 functions. After moving to firebase-tools@11.20.0, we can no longer deploy all functions.

### [REQUIRED] Steps to reproduce

run `firebase deploy --only functions`

### [REQUIRED] Expected behavior

deploy succeeds

### [REQUIRED] Actual behavior

The process finished without any errors.
Only some functions have been deployed (~80 out of  342).
There are 'quota exceeded' errors in the logs for missing functions.
There are no signs that these functions were attempted to be redeployed.

This feature worked on firebase-tools@9.10.0.

```
[2023-01-31T12:37:30.061Z] <<< [apiv2][status] PATCH https://cloudfunctions.googleapis.com/v1/projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME 429
[2023-01-31T12:37:30.061Z] <<< [apiv2][body] PATCH https://cloudfunctions.googleapis.com/v1/projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME {"error":{"code":429,"message":"Quota exceeded for quota metric 'Write requests' and limit 'Write requests per minute' of service 'cloudfunctions.googleapis.com' for consumer 'project_number:273276632660'.","status":"RESOURCE_EXHAUSTED","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"RATE_LIMIT_EXCEEDED","domain":"googleapis.com","metadata":{"quota_metric":"cloudfunctions.googleapis.com/write_requests","quota_location":"global","quota_limit":"WriteRequestsPerMinutePerProject","service":"cloudfunctions.googleapis.com","consumer":"projects/273276632660","quota_limit_value":"50"}}]}}
⚠  functions: got "Quota Exceeded" error while trying to update projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME. Waiting to retry...
Failed to update function projects/auction-dev-1985f/locations/us-central1/functions/GROUP-FUNCTION_NAME
```

### PR DESCRIPTION
**Pull request by blidd-google**
On particularly large function deployments (<60 functions), the CLI easily hits the GCF API quota. Some customers were expecting the CLI to retry deployments that had been bounced by the quota, but did not see the retry actually occur.

Turns out that retries were not actually occurring because deploys that failed due to the Quota Exceeded error were throwing errors that were being wrapped in another error with the wrong status code. This PR surfaces the original, correct status code so that the QueueExecutor handler will detect that a deploy failed and retry after a backoff.

The PR also increases the maxBackoff on the throttler settings to give more opportunities to retry deploys.

Fixes #5474.

### CODE REVIEW

File: src/deploy/functions/release/index.ts [hunk 1]
```diff
@@ -59,16 +59,16 @@ export async function release(
...
   }
 
-  const functionExecutor: executor.QueueExecutor = new executor.QueueExecutor({
+  const throttlerOptions = {
     retries: 30,
     backoff: 20000,
     concurrency: 40,
-    maxBackoff: 40000,
-  });
+    maxBackoff: 100000,
```
Comment (colerogers) [inline src/deploy/functions/release/index.ts:66]: Just curious, where did 100k come from?

Comment (blidd-google) [reply src/deploy/functions/release/index.ts:66]: 100000 is still a pretty wishy-washy number, I just noticed that retries were failing pretty often on very large deployments so I gave the maxBackoff a boost to increase retry success rates
