### PR TITLE
Automatic emulator firebase-admin initialization, fixes #1278

### LINKED ISSUE #1278: Emulator fails on "firebase init" template with firebase-admin error.
### [REQUIRED] Environment info

Firebase CLI: 6.9.2
Platform: macos, Windows

(Problem does not exist with CLI 6.8.0.)

### [REQUIRED] Test case

Emulating the given HTTP trigger in a new project.

### [REQUIRED] Steps to reproduce

1. `firebase init` a new project space for Functions
1. Take all the defaults, choose JavaScript
1. Uncomment the code in index.js
1. Emulate with either `firebase emulators:start --only functions` or `firebase serve --only functions`
1. Access the given URL

### [REQUIRED] Expected behavior

"Hello from Firebase!"

### [REQUIRED] Actual behavior

See the message on emulator output:
```
⚠  The Firebase Admin module has not been initialized early enough. Make sure you run "admin.initializeApp()" outside of any function and at the top of your code
```

The function will time out and disconnect as well.  E.g:

```
curl: (52) Empty reply from server
```

### PR DESCRIPTION
**Pull request by abeisgoat**
A small change which enables the emulator to automatically initialize `firebase-admin` for the most basic use cases.

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -537,12 +536,6 @@ async function ProcessHTTPS(frb: FunctionsRuntimeBundle, trigger: EmulatedTrigge
         res.on("finish", () => {
           instance.close();
           resolveEphemeralServer();
-
-          // If we're on a Unix platform, then the pipe is not cleaned up automatically so...
-          if (process.platform !== "win32") {
```
Comment (bkendall) [inline src/emulator/functionsEmulatorRuntime.ts]: Did you mean to remove this? Doesn't seem like it's relevant to the PR...

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -747,8 +740,9 @@ async function main(): Promise<void> {
   new EmulatorLog("DEBUG", "runtime-status", `Running ${frb.triggerId} in mode ${mode}`).log();
 
   if (!app) {
-    new EmulatorLog("SYSTEM", "admin-not-initialized", "").log();
-    return;
+    adminModuleProxy.initializeApp();
+    new EmulatorLog("SYSTEM", "admin-auto-initialized", "").log();
+    throw new Error(JSON.stringify(frb.ports));
```
Comment (bkendall) [inline src/emulator/functionsEmulatorRuntime.ts]: Should this be throwing?!

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 3]
```diff
@@ -137,8 +137,12 @@ describe("FunctionsEmulator-Runtime", () => {
         expect(logs["non-default-admin-app-used"]).to.eq(1);
       }).timeout(TIMEOUT_MED);
 
-      it("should alert when the app is not initialized", async () => {
-        const runtime = InvokeRuntimeWithFunctions(FunctionRuntimeBundles.onCreate, () => {
+      it("should auto-initialize admin when the app is not initialized by user code", async () => {
+        const onCreateCopy = JSON.parse(
+          JSON.stringify(FunctionRuntimeBundles.onRequest)
+        ) as FunctionsRuntimeBundle;
```
Comment (bkendall) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: why the `parse/stringify`? Is this trying to make a copy? use `_.cloneDeep`

File: src/emulator/functionsEmulatorRuntime.ts (hunk 1 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: I did, I just tossed it in there because it was turns out to not actually be needed (it was merged in with another fix this week)

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: def no
