### PR TITLE
Don't start emulators without services initialized

### LINKED ISSUE #2112: Emulator fails to start if functions port is specified,  but functions were not initialized
### [REQUIRED] Environment info

**firebase-tools:** 8.0.2

**Platform:** Mac

### [REQUIRED] Steps to reproduce

```sh
$ firebase init
    # features: database, firestore, hosting
    # emulators: database, firestore, functions
```

```sh
$ cat firebase.json

{
  "database": {
    "rules": "database.rules.json"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "database": {
      "port": 9000
    }
  }
}
```

```
$ find . -type f | grep -v .git/
./firestore.rules
./firebase-debug.log
./.firebase/hosting.cHVibGlj.cache
./.firebaserc
./public/index.html
./.gitignore
./firebase.json
./database.rules.json
./firestore.indexes.json
```

```
$ firebase emulators:start
```

### [REQUIRED] Expected behavior

It should boot ok

### [REQUIRED] Actual behavior

```sh
[info] ✔  hub: emulator hub started at http://localhost:4400
[info] i  emulators: Shutting down emulators.
[info] i  hub: Stopping emulator hub
[debug] [2020-04-07T20:09:10.813Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at Object.<anonymous> (/Users/tstirrat/.npm-packages/lib/node_modules/firebase-tools/lib/emulator/controller.js:163:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tstirrat/.npm-packages/lib/node_modules/firebase-tools/lib/emulator/controller.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2112 and a similar issue with the hosting emulator.

### Scenarios Tested

firebase.json
```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8080
    },
    "hosting": {
      "port": 5005
    }
  }
}
```

```
$ firebase emulators:start
i  emulators: Starting emulators: functions, firestore, hosting
✔  hub: emulator hub started at http://localhost:4400
⚠  functions: The functions emulator is configured but there is no functions source directory. Have you run firebase init functions?
i  firestore: firestore emulator logging to firestore-debug.log
✔  firestore: firestore emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
⚠  hosting: The hosting emulator is configured but there is no hosting configuration. Have you run firebase init hosting?
^Ci  emulators: Shutting down emulators.
i  hub: Stopping emulator hub
i  firestore: Stopping firestore emulator
```

### CODE REVIEW

File: src/emulator/controller.ts [hunk 1]
```diff
@@ -200,7 +221,7 @@ export async function startAll(options: any, noGui: boolean = false): Promise<vo
 
   if (shouldStart(options, Emulators.FUNCTIONS)) {
     const functionsAddr = Constants.getAddress(Emulators.FUNCTIONS, options);
-
+    ``;
```
Comment (bkendall) [inline src/emulator/controller.ts:224]: um. remove?
