### PR TITLE
normalize channel names on hosting:channel:create and remove hashes

### LINKED ISSUE #2783: hosting:channel:deploy partial deployment and 404 error when channel ID contains "#"
If a channel ID contains a `#`, the CLI begins deploying but errors out with a 404 after the "releasing new version..." step. It still creates the preview channel, using the characters before the `#` as the ID, however the resulting link is a "Site Not Found" page.

### [REQUIRED] Environment info

**firebase-tools:** 8.15.0

**Platform:** Manjaro Linux

### [REQUIRED] Test case

```
firebase hosting:channel:deploy test#removed
```

### [REQUIRED] Steps to reproduce

:white_check_mark: This works fine:

```
firebase hosting:channel:deploy test-removed
```

:white_check_mark: This has the expected error:

```
firebase hosting:channel:deploy test@removed

Error: HTTP Error: 400, Channel IDs can only include letters, numbers, underscores, hyphens, and periods.
```

:stop_sign: This errors with a 404:

```
firebase hosting:channel:deploy test#removed

=== Deploying to 'redacted'...

i  deploying hosting
i  hosting[redacted]: beginning deploy...
i  hosting[redacted]: found 51 files in out
✔  hosting[redacted]: file upload complete
i  hosting[redacted]: finalizing version...
✔  hosting[redacted]: version finalized
i  hosting[redacted]: releasing new version...

Error: HTTP Error: 404, Not Found
```

### [REQUIRED] Expected behavior

The CLI should error out explaining why my channel ID is bad.

### [REQUIRED] Actual behavior

The CLI starts deploying and then errors out with `Error: HTTP Error: 404, Not Found`. The partial deploy is seen with `firebase hosting:channel:list` and on the online Firebase console. It uses the characters before the `#` as the ID (i.e. `test#removed` -> `test`). Visiting the link results in the Firebase "Site Not Found" page.

> Run the command with --debug flag, and include the logs below.

```firebase hosting:channel:deploy test#removed --debug``` contains some information I rather not post publicly. I can send privately on request if needed.

### PR DESCRIPTION
**Pull request by bkendall**
### Description

Fixes #2783

`hosting:channel:deploy` does normalizing of the channel ID provided. `:create` was not. Further, the normalization wasn't removing `#` from the provided IDs and causing issues when passed into a URL.

### Scenarios Tested

- `firebase hosting:channel:create test#bar`
- `firebase hosting:channel:deploy test#bar`

### CODE REVIEW

File: src/hosting/api.ts [hunk 1]
```diff
@@ -160,7 +160,7 @@ export interface Version {
  */
 export function normalizeName(s: string): string {
   // Using a regex replaces *all* bad characters.
```
Comment (dahliasalem) [inline src/hosting/api.ts:162]: Maybe not all *bad* comments but specify which characters are being replaced

File: src/hosting/api.ts [hunk 2]
```diff
@@ -160,7 +160,7 @@ export interface Version {
...
-  return s.replace(/[/:_]/g, "-");
+  return s.replace(/[/:_#]/g, "-");
```
Comment (dahliasalem) [inline src/hosting/api.ts:163]: Instead of "*all* bad characters" maybe specify which characters are being replaced

Comment (bkendall) [reply src/hosting/api.ts:163]: The jsdoc comment is now updated to include `#`. But this comment is about using regex to replace the characters rather than another mechanism. I made it more specific.

**Review by dahliasalem — APPROVED** [review]
