### PR TITLE
Don't crash the command if testIamPermissions errors. Fixes #1695

### LINKED ISSUE #1695: Firestore delete hitting Cloud Resource Manager API every call, exceeding quota limit
### [REQUIRED] Environment info

**firebase-tools:** v6.2.2
**Platform:** Cloud functions

### [REQUIRED] Test case

We're using firebase-tools's recursive firestore delete (from [this pattern](https://firebase.google.com/docs/firestore/solutions/delete-collections)) in a cloud function that runs quite often, and we've started to exceed the Cloud Resource Manager API's quota (currently our limit is 1000 calls in 100 seconds, or ~10 rps).

Screen Shot 2019-10-07 at 3 09 41 pm

I think this must be due to the [`requirePermissions`](https://github.com/firebase/firebase-tools/blob/master/src/commands/firestore-delete.js#L73) call running before every recursive delete (which hits the Cloud Resource Manager `testIamPermissions` API).

I'm wondering if it'd be possible to optionally bypass this call? I could request a quota increase, but it feels a bit unnecessary to check that our token has permission before every query, at >10 rps.

### [REQUIRED] Steps to reproduce

Call firestore.delete > 1000 times in 100 seconds

### [REQUIRED] Expected behavior

Able to recursively delete collections without hitting a quota error

### [REQUIRED] Actual behavior

Cloud Resource Manager API quota error

### PR DESCRIPTION
**Pull request by mbleigh**
I've wanted to do this for a while (yay FixIt week!). `requirePermissions` is meant to be a convenience and explainer for users, checking to see if they have the correct permissions to perform a command before doing work that might end with incomprehensible error messages.

However, there are cases where `testIamPermissions` will fail for reasons unrelated to the user not having appropriate permissions (e.g. #1695). In these cases, it is better to proceed with the rest of the command rather than halt everything due to the request error from Cloud Resource Manager.

## Scenarios Tested

1. Still properly allows commands when you have permission
2. Still properly denies commands when the permissions test returns a 200
3. (new) Runs the command if the permissions check fails in another way

### CODE REVIEW

File: src/requirePermissions.js [hunk 1]
```diff
@@ -30,22 +30,25 @@ module.exports = function(options, permissions) {
         origin: api.resourceManagerOrigin,
       });
     })
-    .then((response) => {
-      const allowedPermissions = (response.body.permissions || []).sort();
-      const missingPermissions = _.difference(requiredPermissions, allowedPermissions);
+    .then(
+      (response) => {
+        const allowedPermissions = (response.body.permissions || []).sort();
```
Comment (samtstern) [inline src/requirePermissions.js]: GitHub's diffing algorithm is bad and it  should feel bad.

File: src/requirePermissions.js [hunk 2]
```diff
@@ -30,19 +30,25 @@ module.exports = function(options, permissions) {
...
+              missingPermissions.join("\n  ")
+          );
+        }
 
-      return true;
-    });
+        return true;
+      },
+      (err) => {
+        logger.debug(`[iam] error while checking permissions, command may fail: ${err.message}`);
```
Comment (bkendall) [inline src/requirePermissions.js]: Should this be `debug`, or something more visible? (I'm not actually sure)

I'd also just say go ahead and print the entire error if we're going to leave it in `debug` (`may fail: ${err}`)

**Comment by mbleigh** [comment]
Rerequesting review for TypeScript version.
