### PR TITLE
Fix issue where tester.groups can be undefined

### LINKED ISSUE #8191: Error on firebase appdistribution:testers:list
### [REQUIRED] Environment info

**firebase-tools:** 13.30.0

**Platform:** Ubuntu. macOS

### [REQUIRED] Test case

The problem appears only when there is a tester added to a Firebase project that is not assigned to any test group.
Run the following commands in the terminal:

### [REQUIRED] Steps to reproduce

export GOOGLE_APPLICATION_CREDENTIALS="service_account.json"
firebase appdistribution:testers:list --project "$PROJECT_ID"

### [REQUIRED] Expected behavior

Testers are listed 

### [REQUIRED] Actual behavior

There is an error: 
```
✔ Preparing the list of your App Distribution testers

Error: An unexpected error has occurred.

Having trouble? Try again or contact support with contents of firebase-debug.log
```

In logs:
```
[debug] [2025-02-10T11:06:52.834Z] TypeError: Cannot read properties of undefined (reading 'map')
    at printTestersTable (/Users/praca/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/commands/appdistribution-testers-list.js:48:14)
    at Command.actionFn (/Users/praca/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/commands/appdistribution-testers-list.js:34:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[error] 
[error] Error: An unexpected error has occurred.
```

### PR DESCRIPTION
**Pull request by aalej**
### Description

Fixes #8191 

Checking API explorer in https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.testers/list. Executing the method returns a JSON response of:

```json
{
  "testers": [
    {
      "name": "projects/PROJECT_NUMBER/testers/tester_0@google.com",
      "groups": [
        "projects/PROJECT_NUMBER/groups/qa",
        "projects/PROJECT_NUMBER/groups/developers"
      ],
      "lastActivityTime": "2024-11-14T13:10:19.256962Z"
    },
    {
      "name": "projects/PROJECT_NUMBER/testers/tester_1@gmail.com",
      "lastActivityTime": "2025-01-30T14:03:28.146030Z"
    }
  ]
}
```

It looks like testers not part of any groups return a [Tester](https://firebase.google.com/docs/reference/app-distribution/rest/v1/projects.testers#Tester) object that does not have a `groups` field

### Scenarios Tested

Run `firebase appdistribution:testers:list --project PROJECT_ID`
```
$ firebase appdistribution:testers:list --project PROJECT_ID
(node:29657) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Preparing the list of your App Distribution testers
┌───────────────────────────┬──────────────┬──────────────────────────────────────────────────────────────┬───────────────┐
│ Name                      │ Display Name │ Last Activity Time                                           │ Groups        │
├───────────────────────────┼──────────────┼──────────────────────────────────────────────────────────────┼───────────────┤
│ tester_0@google.com │              │ Thu Nov 14 2024 21:10:19 GMT+0800 (Philippine Standard Time) │ developers;qa │
├───────────────────────────┼──────────────┼──────────────────────────────────────────────────────────────┼───────────────┤
│ tester_1@gmail.com      │              │ Thu Jan 30 2025 22:03:28 GMT+0800 (Philippine Standard Time) │               │
└───────────────────────────┴──────────────┴──────────────────────────────────────────────────────────────┴───────────────┘
✔  Testers listed successfully
```

### CODE REVIEW

File: src/commands/appdistribution-testers-list.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ function printTestersTable(testers: Tester[]): void {
 
   for (const tester of testers) {
     const name = tester.name.split("/").pop();
-    const groups = tester.groups
+    const groups = (tester.groups || [])
```
Comment (joehan) [inline src/commands/appdistribution-testers-list.ts:50]: Nit: Prefer ?? when adding a fallback for undefined cases
```suggestion
    const groups = (tester.groups ?? [])
```

**Review by joehan — APPROVED** [review]
Thanks for the quick fix!
