### PR TITLE
Fixing unsafe array spreads on Hosting deploys

### LINKED ISSUE #6712: Can't deploy project due to ...res.body.versions undefined
### [REQUIRED] Environment info

**firebase-tools:**
"13.0.2"

**Platform:**
Windows

### [REQUIRED] Test case

I just run `firebase deploy` on my project

### [REQUIRED] Steps to reproduce

- build a project
- deploy a project

### [REQUIRED] Expected behavior

the project is deployed

### [REQUIRED] Actual behavior

```
[debug] [2024-01-23T10:24:51.358Z] TypeError: res.body.versions is not iterable (cannot read property undefined)
    at Object.listVersions (C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\hosting\api.js:113:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async Object.gcTagsForServices (C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\hosting\runTags.js:14:31)
    at async Object.setRewriteTags (C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\hosting\runTags.js:77:9)
    at async convertConfig (C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\deploy\hosting\convertConfig.js:160:9)
    at async C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\deploy\hosting\release.js:21:21
    at async Promise.all (index 0)
    at async release (C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\deploy\hosting\release.js:14:5)
    at async chain (C:\Users\feder\Repository\anyx_mono_frontend\node_modules\firebase-tools\lib\deploy\index.js:38:9)
    ```
    
    so here
    
    ```
    async function listVersions(site) {
    let pageToken = undefined;
    const versions = [];
    do {
        const queryParams = {};
        if (pageToken) {
            queryParams.pageToken = pageToken;
        }
        const res = await apiClient.get(`projects/-/sites/${site}/versions`, {
            queryParams,
        });
        versions.push(...res.body.versions);
        pageToken = res.body.nextPageToken;
    } while (pageToken);
    return versions;
}
exports.listVersions = listVersions;
```

This issue appeared overnight.

### PR DESCRIPTION
**Pull request by joehan**
### Description
Fixing some unsafe array spreads in the Hosting API client. This was inspired by #6172 - I'm not sure why the backend is not returning versions there (and we might wanna look into that more), but either way we should not blow up there.
Fixes #6712

### CODE REVIEW

File: src/hosting/api.ts [hunk 1]
```diff
@@ -449,8 +449,8 @@ export async function listVersions(site: string): Promise<Version[]> {
     const res = await apiClient.get<ListVersionsResponse>(`projects/-/sites/${site}/versions`, {
       queryParams,
     });
-    versions.push(...res.body.versions);
-    pageToken = res.body.nextPageToken;
+    versions.push(...(res.body?.versions || []));
```
Comment (bkendall) [inline src/hosting/api.ts:452]: Body isn't the problem, it's the lack of `versions`.

I'd suggest changing `ListVersionsResponse` to have `versions?: Version[]`, then do `versions.push(...(res.body.versions ?? []));` here.

Similar to the `sites` response, if you really want to do that too.

Please add tests.

**Review by bkendall — CHANGES_REQUESTED** [review]

File: src/hosting/api.ts (hunk 1 above)
Comment (bkendall) [reply src/hosting/api.ts]: Yeah, okay. I just did it. haha

**Review by bkendall — APPROVED** [review]
