### PR TITLE
Fixed .graphqlrc path generation for Windows devices

### LINKED ISSUE #8177: Firebase Data Connect VS Code Extension: Request textDocument/hover failed
### [REQUIRED] Environment info

**firebase-tools:** 13.30.0

**Platform:** Windows 11 Pro

### [REQUIRED] Test case

I am using the **Firebase Data Connect** extension in **VS Code** on **Windows 11 Pro**. The same repository and setup works fine on **macOS** and **idx**, but on Windows, hovering over anything (schema types, queries and mutations) does not show documentation.
Tested also with the example schema, query and mutation created by the extension after pressing the button **Run firebase init**.

### [REQUIRED] Steps to reproduce

1. Install the **Firebase Data Connect** extension in VS Code on **Windows 11 Pro**.
2. Click the **Run firebase init** button in the extension and initialize a default project of dataconnect.
3. Hover over any GraphQL field or type.
4. The expected hover documentation does not appear, and the error is logged in the output.

### [REQUIRED] Expected behavior

Hovering over a GraphQL field should display documentation or schema information.

### [REQUIRED] Actual behavior

```
Firebase GraphQL Language Server started!
[Info  - 11:31:39 PM] {"type":"usage","messageType":"initialize"}
Firebase GraphQL Language Server restarted
[Error - 11:31:39 PM] WARNING: graphql-config error, only highlighting is enabled:

      Unable to find any GraphQL type definitions for the following pointers:
        
          - ../c:\Users\name\projects\my-project-firebase\dataconnect/schema/**/*.gql
          ,
          - ../c:\Users\name\projects\my-project-firebase\dataconnect/.dataconnect/**/*.gql
          
for more information on using 'graphql-config' with 'graphql-language-service-server', 
see the documentation at https://www.npmjs.com/package/graphql-language-service-server#user-content-graphql-configuration-file
{"type":"usage","messageType":"textDocument/documentSymbol","fileName":"file:///c%3A/Users/name/projects/my-project-firebase/dataconnect/connector/queries.gql"}
[Error - 11:31:43 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - ../c:\Users\name\projects\my-project-firebase\dataconnect/schema/**/*.gql
          ,
          - ../c:\Users\name\projects\my-project-firebase\dataconnect/.dataconnect/**/*.gql
          
  Code: -32603 
{"type":"usage","messageType":"textDocument/didClose","projectName":"default","fileName":"file:///c%3A/Users/name/projects/my-project-firebase/dataconnect/connector/queries.gql"}
```

### PR DESCRIPTION
**Pull request by hlshen**
Fix generation of paths to schema and operation files. Fixes GQL Language server support for Windows devices. 

Fixes #8177 

Verified on Windows VM.

### CODE REVIEW

File: firebase-vscode/src/data-connect/language-client.ts [hunk 1]
```diff
@@ -95,14 +95,30 @@ export function setupLanguageClient(
     // TODO: Expand to multiple services
     const config = configs.values[0];
     const generatedPath = ".dataconnect";
-    const schemaPaths = [
+
+    let schemaPaths = [
```
Comment (joehan) [inline firebase-vscode/src/data-connect/language-client.ts:99]: Ahhh, I should have caught this in a previous review, but we should be using [path.join](https://nodejs.org/api/path.html#pathjoinpaths) whenever we create paths to avoid issues like this where we have to manually replace the delimiter.

**Review by joehan — CHANGES_REQUESTED** [review]

**Review by joehan — APPROVED** [review]
