### PR TITLE
Import/export download tokens

### LINKED ISSUE #3414: Emulator does not restore firebaseStorageDownloadTokens on import
### [REQUIRED] Environment info

**firebase-tools:** 9.12.0

**Platform:** Windows 10

### [REQUIRED] Test case

```javascript
import { getStorage, useStorageEmulator, ref, getDownloadURL } from '@firebase/storage'

const storage = getStorage()
useStorageEmulator(storage, '127.0.0.1', 9199)

async function getMyFile () {
  const reference = ref(storage, 'myfile')
  return await getDownloadURL(reference)
}
```

### [REQUIRED] Steps to reproduce

1. Run the emulators (including storage): `firebase emulators:start --import data --export-on-exit`
2. Upload a test file `myfile` to Storage using the Emulator UI
3. Call the `getMyFile()` function from Javascript - works as expected, can fetch the file
4. `Ctrl+C` to shut down the emulator. `myfile` is exported to `data/`
5. Note that `data/storage_export/metadata/<bucket>/myfile.json` doesn't contain anything in `customMetadata` or `downloadTokens` properties? (This seems unexpected)
6. Start the emulators again: `firebase emulators:start --import data --export-on-exit`
7. Call the `getMyFile()` function from Javascript - receive error:
`FirebaseError: Firebase Storage: The given file does not have any download URLs. (storage/no-download-url)`

### [REQUIRED] Expected behavior

Download tokens are exported and imported between emulator runs.

### [REQUIRED] Actual behavior

Download tokens are not exported/imported by the storage emulator.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #3414

### Scenarios Tested

Expanded unit test

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/storage/metadata.ts [hunk 1]
```diff
@@ -132,10 +132,15 @@ export class StoredFileMetadata {
...
 
   private setDownloadTokensFromCustomMetadata() {
-    if (!this.customMetadata) return;
+    if (!this.customMetadata) {
+      return;
+    }
 
     if (this.customMetadata.firebaseStorageDownloadTokens) {
-      this.downloadTokens = this.customMetadata.firebaseStorageDownloadTokens.split(",");
+      this.downloadTokens = [
```
Comment (samtstern) [inline src/emulator/storage/metadata.ts:140]: This is the part I am unsure about ... but it feels right to me.

Comment (abeisgoat) [reply src/emulator/storage/metadata.ts:140]: seens very reasonable to me, we must have just missed this when I made the tweaks to download token logic last week

**Review by abeisgoat — APPROVED** [review]
