### PR TITLE
Fix credentials issue when not all emulators are running

### LINKED ISSUE #1448: `firebase serve` fails with false negative "Error: The default Firebase app already exists"
### [REQUIRED] Environment info

**firebase-tools:** 7.0.2

**Platform:** macOS

### [REQUIRED] Test case

When imported as default:

```ts
import admin from 'firebase-admin'
admin.initializeApp()
```

...`initializeApp` throws:

```
Error: The default Firebase app already exists. This means you called initializeApp() more than once without providing an app name as the second argument. In most cases you only need to call initializeApp() once. But if you do want to initialize multiple apps, pass a second argument to initializeApp() to give each app a unique name.
  at FirebaseAppError.FirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:42:28)
  at FirebaseAppError.PrefixedFirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:88:28)
  at new FirebaseAppError (node_modules/firebase-admin/lib/utils/error.js:122:28)
  at FirebaseNamespaceInternals.initializeApp (node_modules/firebase-admin/lib/firebase-namespace.js:68:23)
  at FirebaseNamespace.initializeApp (node_modules/firebase-admin/lib/firebase-namespace.js:392:30)
  at Proxy.<anonymous> (node_modules/firebase-tools/src/emulator/functionsEmulatorRuntime.ts:543:31)
  at node_modules/firebase-tools/src/emulator/functionsEmulatorRuntime.ts:918:22
  at Generator.next (<anonymous>)
  at fulfilled (node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:4:58)
  at <anonymous>
```

When `initializeApp` is commened out:

```ts
import admin from 'firebase-admin'
// admin.initializeApp()
```

...it throws:

```
Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
  at FirebaseAppError.FirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:42:28)
  at FirebaseAppError.PrefixedFirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:88:28)
  at new FirebaseAppError (node_modules/firebase-admin/lib/utils/error.js:122:28)
  at FirebaseNamespaceInternals.app (node_modules/firebase-admin/lib/firebase-namespace.js:101:19)
  at FirebaseNamespace.app (node_modules/firebase-admin/lib/firebase-namespace.js:402:30)
  at FirebaseNamespace.ensureApp (node_modules/firebase-admin/lib/firebase-namespace.js:418:24)
  at FirebaseNamespace.fn (node_modules/firebase-admin/lib/firebase-namespace.js:327:30)
  at Object../GECK/firebase/firestore/adaptor/node.ts (build/development/server/webpack:/GECK/firebase/firestore/adaptor/node.ts:16:21)
  at __webpack_require__ (build/development/server/webpack:/webpack/bootstrap:19:1)
  at Object../GECK/firebase/firestore/index.ts (build/development/server/webpack:/GECK/firebase/firestore/index.ts:1:1)
```

But it works fine when import as `*`:

```ts
import * as admin from 'firebase-admin'
admin.initializeApp()
```

### [REQUIRED] Steps to reproduce

1. Import admin as default `import admin from 'firebase-admin'`
2. Initialize the app `admin.initializeApp()`
3. Start `firebase serve`

### [REQUIRED] Expected behavior

It should simply work or throw an error with a clear explanation of what's wrong. Right now it's confusing.

### [REQUIRED] Actual behavior

It fails in a mysterious way that is extremely difficult to debug.

### LINKED ISSUE #1451: "Error: The incoming JSON object does not contain a client_email field" after upgrading to 7.0.2
### [REQUIRED] Environment info

**firebase-tools:** 7.0.2

**Platform:** Oracle Linux Server 7.6, Node 10.15

### [REQUIRED] Test case

emulate https function with "firebase-admin": "^8.2.0", "firebase-functions": "^3.0.2"

### [REQUIRED] Steps to reproduce

run any https function with firebase functions:shell

### [REQUIRED] Expected behavior

no error (firebase-tools 7.0.0 throws no error)

### [REQUIRED] Actual behavior

Sent request to function.
```
firebase > ⚠  Error: The incoming JSON object does not contain a client_email field
    at JWT.fromJSON (/riderequest/functions/node_modules/google-auth-library/build/src/auth/jwtclient.js:165:19)
    at GoogleAuth.fromJSON (/riderequest/functions/node_modules/google-auth-library/build/src/auth/googleauth.js:294:16)
    at GoogleAuth.getClient (/riderequest/functions/node_modules/google-auth-library/build/src/auth/googleauth.js:476:52)
    at GrpcClient._getCredentials (/riderequest/functions/node_modules/google-gax/build/src/grpc.js:107:40)
    at GrpcClient.createStub (/riderequest/functions/node_modules/google-gax/build/src/grpc.js:223:34)
    at new FirestoreClient (/riderequest/functions/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:128:39)
    at ClientPool.Firestore._clientPool.pool_1.ClientPool [as clientFactory] (/riderequest/functions/node_modules/@google-cloud/firestore/build/src/index.js:315:26)
    at ClientPool.acquire (/riderequest/functions/node_modules/@google-cloud/firestore/build/src/pool.js:61:35)
    at ClientPool.run (/riderequest/functions/node_modules/@google-cloud/firestore/build/src/pool.js:114:29)
    at Firestore.request (/riderequest/functions/node_modules/@google-cloud/firestore/build/src/index.js:957:33)
⚠  Your function was killed because it raised an unhandled error.
```

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1451
Fixes #1448 

Behavior changes:

  * No longer auto-calls `admin.initializeApp()` if the user forgets to (matching CF3 behavior).
  * If the Firestore emulator is not running, firestore calls **go to prod**.
  * If the Database emulator is not running, database calls **go to prod**.

Other changes:

  * When trying to add a test I discovered a ton of repeated code inside the runtime tests, so I made a helper method and replaced all of the instances.
	 
### Scenarios Tested

Unit-tested and manual tested all combinations of emulators running/not running and made sure operations went to prod or the emulator as expected.

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -382,7 +382,10 @@ function InitializeNetworkFiltering(frb: FunctionsRuntimeBundle): void {
         if (bundle.name === "google-gax") {
           const cs = newed.constructSettings;
           newed.constructSettings = (...csArgs: any[]) => {
-            (csArgs[3] as any).authorization = "Bearer owner";
+            const headers = (csArgs[3] as any);
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Without this you can get:
```
⚠  Error: Getting metadata from plugin failed with error: Header field "authorization" must only have a single value
    at Http2CallStream.call.on (/tmp/tmp.tkVh7jwr4l/functions/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/tmp/tmp.tkVh7jwr4l/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -515,7 +518,7 @@ async function InitializeFirebaseAdminStubs(frb: FunctionsRuntimeBundle): Promis
         "WARN",
         "runtime-status",
         "The Cloud Firestore emulator is not running so database operations will fail with a " +
-          "'default credentials' error."
+          "credentials error."
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: This message is no longer true if we go forward.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 3]
```diff
@@ -404,7 +410,13 @@ function InitializeNetworkFiltering(frb: FunctionsRuntimeBundle): void {
         if (bundle.name === "google-gax") {
           const cs = newed.constructSettings;
           newed.constructSettings = (...csArgs: any[]) => {
-            (csArgs[3] as any).authorization = "Bearer owner";
+            // TODO: It doesn't seem like we need this anymore ... but maybe we do
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: cc @abeisgoat what do you think about this?  Everything works for me without this.

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 4]
```diff
@@ -39,9 +39,41 @@ function InvokeRuntimeWithFunctions(
   });
 }
 
-function _is_verbose(runtime: FunctionsRuntimeInstance): void {
-  runtime.events.on("log", (el: EmulatorLog) => {
-    process.stdout.write(el.toPrettyString() + "\n");
+function CallHTTPSFunction(
```
Comment (samtstern) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: This removes a lot of the repeat test code.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 5]
```diff
@@ -498,99 +496,141 @@ async function getGRPCInsecureCredential(frb: FunctionsRuntimeBundle): Promise<a
...
+/**
+ * This stub is the most important and one of the only non - optional stubs.This feature redirects
+ * writes from the admin SDK back into emulated resources.
+ *
+ * To do this, we replace initializeApp so it drops the developers config options and returns a restricted,
+ * unauthenticated app.
+ *
+ * We also mock out.settings() so we can merge the emulator settings with the developer's.
+ */
+async function InitializeFirebaseAdminStubs(frb: FunctionsRuntimeBundle): Promise<void> {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: There are a lot of behavior changes here.

**Comment by samtstern** [comment]
@abeisgoat I would love to get your review of the general approach before I go through and finish all of the polishing and add a few more tests.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 6]
```diff
@@ -967,11 +1021,6 @@ async function main(): Promise<void> {
 
   logDebug(`Running ${frb.triggerId} in mode ${mode}`);
 
-  if (!defaultApp) {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: No longer doing this.

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 7]
```diff
@@ -233,54 +254,134 @@ describe("FunctionsEmulator-Runtime", () => {
         expect(logs["set-firestore-settings"]).to.eq(1);
       }).timeout(TIMEOUT_MED);
 
-      it("should redirect Firestore write to emulator", async () => {
-        const onRequestCopy = _.cloneDeep(
-          FunctionRuntimeBundles.onRequest
-        ) as FunctionsRuntimeBundle;
+      it("should provide the same stubs through admin-global or through the default app", async () => {
```
Comment (samtstern) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: There are 5 new tests here, 1 old test deleted, and then the rest are just refactored to remove boilerplate.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 8]
```diff
@@ -100,6 +107,36 @@ interface ProxyTarget extends Object {
   obj.incremented == 2;
    */
 class Proxied<T extends ProxyTarget> {
+  /**
+   * Gets a property from the original object.
+   */
+  static getOriginal(target: any, key: string): any {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: The only change here is to make some methods `static` since they were not using the instance at all.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 9]
```diff
@@ -401,14 +408,6 @@ function InitializeNetworkFiltering(frb: FunctionsRuntimeBundle): void {
         return original(...args);
       } catch (e) {
         const newed = new original(...args);
-        if (bundle.name === "google-gax") {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: We no longer need this bit since we now require `firebase-admin` v8+ and therefore we have a version of Firestore where we can pass the `Bearer owner` header in through the settings constructor.  So this was just unnecessary complexity.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 10]
```diff
@@ -498,99 +497,142 @@ async function getGRPCInsecureCredential(frb: FunctionsRuntimeBundle): Promise<a
...
-      // do anything.
-      const adminFirestoreProxy = new Proxied<typeof admin.firestore>(
-        adminModuleTarget.firestore
-      ).applied(() => {
-        return defaultApp.firestore();
-      });
-
-      return adminFirestoreProxy.finalize();
+    .when("firestore", (target) => {
+      if (frb.ports.firestore) {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Here's the core of the behavior change: when emulators are running we talk to them.  When they are not, we use prod.

Comment (yuchenshi) [reply src/emulator/functionsEmulatorRuntime.ts]: This seems to me like duplicate logic to `appProxy` below. Can we reuse the logic, for example, by delegating to `defaultApp.firestore()` and `databaseApp.database()`?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 11]
```diff
@@ -498,99 +497,142 @@ async function getGRPCInsecureCredential(frb: FunctionsRuntimeBundle): Promise<a
...
+    .finalize();
+}
+
+async function makeProxiedFirestore(
+  frb: FunctionsRuntimeBundle,
+  target: any
+): Promise<typeof admin.firestore> {
+  // If we can't get sslCreds that means either grpc or grpc-js doesn't exist. If this is the save,
+  // then there's probably something really wrong (like a failed node-gyp build). If that's the case
+  // we should silently fail here and allow the error to raise in user-code so they can debug appropriately.
```
Comment (yuchenshi) [inline src/emulator/functionsEmulatorRuntime.ts]: nit: `silent fail` => `swallow error`? I think that may explain the idea a little better.

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 12]
```diff
@@ -42,10 +42,52 @@ function InvokeRuntimeWithFunctions(
...
+ *   3) Wait for the runtime to exit
+ */
+async function CallHTTPSFunction(
+  runtime: FunctionsRuntimeInstance,
+  frb: FunctionsRuntimeBundle,
+  options: any = {},
+  requestData?: string
+): Promise<string> {
+  await runtime.ready;
+  const dataPromise = new Promise<string>((resolve, reject) => {
```
Comment (yuchenshi) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: Shall we just use the `request` module instead? It's already in `dependencies` and it provides a nicer callback of `function (err, response, body)` so you don't have to do the manual string concat stuff here.

P.S. The current implementation fails to propagate errors reading the body (a.k.a. `res.on("error", reject)` on stream).

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 13]
```diff
@@ -191,18 +210,19 @@ describe("FunctionsEmulator-Runtime", () => {
         expect(logs["function-log"]).to.eq(1);
       }).timeout(TIMEOUT_MED);
 
-      it("should provide a stubbed Firestore through admin.firestore()", async () => {
+      it("should provide a stubbed Firestore through ADMIN.firestore()", async () => {
```
Comment (yuchenshi) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: Huh? Why this change?

File: src/emulator/functionsEmulatorRuntime.ts (hunk 10 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: The difference is that `admin.firestore` does double duty as a function (`admin.firestore().doc(...)`) and a namespace (`admin.firestore.FieldValue`) whereas the one on the default app does not, so we need this duplication.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 14]
```diff
@@ -606,41 +648,53 @@ function proxyFirebaseApp(
...
+  const firestoreProxy = new Proxied<typeof admin.firestore>(target.firestore);
+  return firestoreProxy
+    .applied(() => {
+      return new Proxied(target.firestore())
+        .when("settings", (firestoreTarget) => {
+          return (settings: any) => {
+            initializeFirestoreSettings(firestoreTarget, settings);
+          };
+        })
+        .any((firestoreTarget, field) => {
```
Comment (yuchenshi) [inline src/emulator/functionsEmulatorRuntime.ts]: Would `admin.firestore.FieldValue` also trigger this? Is it working as intended?

File: src/test/emulators/functionsEmulatorRuntime.spec.ts (hunk 12 above)
Comment (samtstern) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: Good idea!
