### PR TITLE
fix use of normalizedHostingConfigs when it is called repeatedly

### LINKED ISSUE #2746: hosting:channel:deploy: Hosting configs should only include either "site" or \"target\", not both.
I have a multisite config with targets. Using `npx firebase-tools deploy --only hosting` or `npx firebase-tools deploy --only hosting:bbbb` works fine. But if I use the new GitHub action, it fails on the line:

```
 /usr/local/bin/npx firebase-tools hosting:channel:deploy pr22-blah --expires 30d --project blah-dev --json
```

Running the same thing locally fails in the same way.  The error is:

```sh
$ npx firebase-tools hosting:channel:deploy pr22-blah --only bbb --expires 30d --project blah-dev --json
{
  "status": "error",
  "error": "Hosting configs should only include either \"site\" or \"target\", not both."
}
```

Note that the command I used there adds `--only bbb`. The command fails the same way with or without that.

Also note that my `firebase.json` does NOT list `"site"` at all. See below:

.firebaserc:
```json
{
  "projects": {
    "default": "blah-dev",
    "dev": "blah-dev",
    "prod": "blah-io"
  },
  "targets": {
    "blah-io": {
      "hosting": {
        "aaa": [
          "blah-aaa"
        ],
        "boilerplate": [
          "blah-boilerplate"
        ],
        "bbb": [
          "blah-bingo"
        ]
      }
    },
    "blah-dev": {
      "hosting": {
        "aaa": [
          "blah-aaa-dev"
        ],
        "boilerplate": [
          "blah-boilerplate-dev"
        ],
        "bbb": [
          "blah-bbb-dev"
        ]
      }
    }
  }
}
```

firebase.json
```json
{
  "firestore": {...},
  "database": {...},
  "functions": {...},
  "hosting": [
    {
      "target": "aaa",
      "public": "packages/aaa/build",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    },
    {
      "target": "boilerplate",
      "public": "packages/boilerplate/build",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    },
    {
      "target": "bbb",
      "public": "packages/bbb/build",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ]
    }
  ],
  "emulators": {...}
}

```

### [REQUIRED] Environment info

**firebase-tools:**. `npx firebase-tools --version` -> `8.14.0`

**Platform:** OSX, but also GitHub Actions default image

### [REQUIRED] Test case

See above.

### [REQUIRED] Steps to reproduce

See above. Run the hosting:channel:deploy command

### [REQUIRED] Expected behavior

It deploys

### [REQUIRED] Actual behavior

```
{
  "status": "error",
  "error": "Hosting configs should only include either \"site\" or \"target\", not both."
}
```

(`--debug` flag adds a lot of HTTP logging noise at the front, but it's all 200s.)

### PR DESCRIPTION
**Pull request by bkendall**
### Description

Fixes #2746

The `hosting:channel:deploy` path normalizes the configs once before going through the normal deploy path. Unfortunately, the normalizing process modified the underlying config which ended up causing issues when the normalize method was called a second time. Deep cloning the config fixes this issue.

Also, added some functional tests for deploying to a target and deploying to a channel!

### CODE REVIEW

File: scripts/hosting-tests/run.sh [hunk 1]
```diff
@@ -42,7 +42,7 @@ EOM
 mkdir "public"
 touch "public/${TARGET_FILE}"
 echo "${DATE}" > "public/${TARGET_FILE}"
-echo "Initalized temp directory."
+echo "Initialized temp directory."
```
Comment (samtstern) [inline scripts/hosting-tests/run.sh:45]: Initalize me cap'n!

**Review by samtstern — APPROVED** [review]
