### PR TITLE
Fully support RTDB functions and use firebase-functions 3.x

### LINKED ISSUE #1417: Firestore triggers broken in emulator
### [REQUIRED] Version info

**node:** 10.15.3

**firebase-functions:** 3.0.0

**firebase-tools:** 7.0.0

**firebase-admin:** 8.0.0

### [REQUIRED] Test case

https://github.com/aputinski/firebase-functions-test-case

### [REQUIRED] Steps to reproduce

See README in repo above

### [REQUIRED] Expected behavior

```
functions: Beginning execution of "onWrite"
functions: Finished "onWrite" in ~1s
```

### [REQUIRED] Actual behavior

```
TypeError: Cannot read property 'eventType' of undefined
```

It looks like the data and context are being combined into the first argument

https://github.com/firebase/firebase-functions/blob/master/src/cloud-functions.ts#L242

### Were you able to successfully deploy your functions?

N/A

### PR DESCRIPTION
**Pull request by samtstern**
### Changes
- Update dependencies so that we use the same function definitions as `firebase-functions` 3.x (fixes #1417)
- Make RTDB functions talk to the local RTDB emulator by default (fixes https://github.com/firebase/quickstart-nodejs/issues/77)

### Questions

- Is it ok to force the update to `firebase-admin:8` and `firebase-functions:3`?  Specifically it will be a huge pain to allow `firebase-functions` to exist at two version.
- Why do we have to do a `resource => resource.name` transformation?  This smells to me like our emulation is missing a layer that prod has.

### Testing

```js
const admin = require("firebase-admin");
const functions = require("firebase-functions");

admin.initializeApp();

exports.deleteFromFirestore = functions.https.onRequest(async (req, res) => {
    await admin.firestore().doc("info/test").delete();
    res.json({ deleted: true });
});

exports.deleteFromRtdb = functions.https.onRequest(async (req, res) => {
    await admin.database().ref('info/test').remove();
    res.json({ deleted: true });
});

exports.writeToFirestore = functions.https.onRequest(async (req, res) => {
    const ref = admin.firestore().doc("info/test");

    await ref.set({ hello: (new Date().toISOString()) });
    ref.get().then((snap) => {
        res.json({ data: snap.data() });
    });
});

exports.writeToRtdb = functions.https.onRequest(async (req, res) => {
    const ref = admin.database().ref('info/test');

    await ref.set({ hello: (new Date().toISOString()) });
    ref.once('value', (snap) => {
        res.json({ data: snap });
    });
});

exports.firestoreReaction = functions.firestore.document('info/test').onWrite(async (change, ctx) => {
    console.log('========== FIRESTORE FUNCTION ==========');
    console.log(`Change: ${JSON.stringify(change)}`);
    return true;
});

exports.rtdbReaction = functions.database.ref('info/test').onWrite(async (change, ctx) => {
    console.log('========== RTDB FUNCTION ==========');
    console.log(`Change: ${JSON.stringify(change)}`);
    return true;
});
```

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -495,17 +572,18 @@ function ProtectEnvironmentalVariables(): void {
...
+
   process.env.GCLOUD_PROJECT = projectId;
   process.env.FUNCTIONS_EMULATOR = "true";
-  /*
-    Do our best to provide reasonable FIREBASE_CONFIG, based on firebase-functions implementation
-    https://github.com/firebase/firebase-functions/blob/master/src/index.ts#L70
-   */
+
+  // Do our best to provide reasonable FIREBASE_CONFIG, based on firebase-functions implementation
+  // https://github.com/firebase/firebase-functions/blob/master/src/index.ts#L70
```
Comment (IanWyszynski) [inline src/emulator/functionsEmulatorRuntime.ts]: It's unclear to me what this comment (specifically the link into firebase-functions) means.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -647,6 +727,19 @@ async function ProcessBackground(
     }
   }
 
+  if (service === "firebaseio.com") {
```
Comment (IanWyszynski) [inline src/emulator/functionsEmulatorRuntime.ts]: nit: we could use the service constants here: https://github.com/firebase/firebase-tools/blob/master/src/emulator/constants.ts#L15-L16

File: src/emulator/functionsEmulatorRuntime.ts [hunk 3]
```diff
@@ -148,52 +178,66 @@ class Proxied<T> {
   }
 }
 
+async function resolveDeveloperNodeModule(
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: I ended up refactoring some of this module resolution stuff when I was originally trying to support `firebase-functions` 2.x and 3.x but I determined that was not feasible.

Still the refactoring remains because I think I made the code more maintainable.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 4]
```diff
@@ -148,52 +178,66 @@ class Proxied<T> {
...
+  let pkg = requirePackageJson(frb);
+  if (!pkg) {
     new EmulatorLog("SYSTEM", "missing-package-json", "").log();
     return false;
   }
 
   const modBundles = [
-    { name: "firebase-admin", isDev: false, minVersion: 7 },
-    { name: "firebase-functions", isDev: false, minVersion: 2 },
+    { name: "firebase-admin", isDev: false, minVersion: 8 },
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: This could be considered a breaking change.  IMO we should consider the emulators in "beta" like we do with some of our SDKs and not make firebase-tools take major version changes all the time as we try to get things right.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 5]
```diff
@@ -448,9 +525,19 @@ async function InitializeFirebaseAdminStubs(frb: FunctionsRuntimeBundle): Promis
         return adminModuleTarget.initializeApp(opts, appName);
       }
 
-      new EmulatorLog("SYSTEM", "default-admin-app-used", "").log();
+      const config = JSON.parse(process.env.FIREBASE_CONFIG || "{}");
+      new EmulatorLog("SYSTEM", `default-admin-app-used, config=${config}`, "").log();
+
+      // TODO: Is there any possible harm in this?
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Anyone wanna tell me how this could go wrong?  Seems to be required to make RTDB work and not affect Firestore.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 1 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Good call, updated the link to something better (and used a permalink this time)

File: src/emulator/functionsEmulatorRuntime.ts [hunk 6]
```diff
@@ -495,17 +586,18 @@ function ProtectEnvironmentalVariables(): void {
...
-    https://github.com/firebase/firebase-functions/blob/master/src/index.ts#L70
-   */
+
+  // Do our best to provide reasonable FIREBASE_CONFIG, based on firebase-functions implementation
+  // https://github.com/firebase/firebase-functions/blob/59d6a7e056a7244e700dc7b6a180e25b38b647fd/src/setup.ts#L45
   process.env.FIREBASE_CONFIG = JSON.stringify({
     databaseURL: process.env.DATABASE_URL || `https://${process.env.GCLOUD_PROJECT}.firebaseio.com`,
     storageBucket: process.env.STORAGE_BUCKET_URL || `${process.env.GCLOUD_PROJECT}.appspot.com`,
-    projectId: process.env.GCLOUD_PROJECT,
+    projectId: projectId || process.env.GCLOUD_PROJECT,
```
Comment (joehan) [inline src/emulator/functionsEmulatorRuntime.ts]: Is this redundant with line 592, since projectId and GCLOUD_PROJECT should be equal ?
