### PR TITLE
Read name from metadata as backup for gcs upload

### LINKED ISSUE #3953: Storage Emulator does not match Google Cloud Storage library API
### [REQUIRED] Environment info

**firebase-tools:** 
9.23.0

**Platform:**
Windows 10

### [REQUIRED] Test case
Using the Google Cloud Storage Python library which follows the [Google Cloud Storage JSON API spec](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) upload a file
```
blob = blob_from_path(path)
blob.metadata = metadata
blob.upload_from_string(content, content_type, num_retries=3)
```

### [REQUIRED] Steps to reproduce
Any GCS Client library which puts name inside the body of the "file" metadata of the upload and doesn't put name as a query parameter. (Again as per [Google Cloud Storage JSON API spec](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) upload a file)

### [REQUIRED] Expected behavior
The emulator should get the name of the file from the metadata passed by the client library. Then the file should be uploaded and file metadata returned in a 200 response.

### [REQUIRED] Actual behavior
Returns 400 because name is not found in the query (even though name is in the metadata)

**The Problem**
The problems stems from the emulator/storage/apis/gcloud.js implementation
```
gcloudStorageAPI.post("/upload/storage/v1/b/:bucketId/o", (req, res) => {
        if (!req.query.name) {
            res.sendStatus(400);
            return;
        }
        let name = req.query.name.toString();
        if (name.startsWith("/")) {
            name = name.slice(1);
        }
```
The POST handler is checking for a name parameter but the spec says it is optional and may be instead passed via metadata which is in the metadata section of a multipart upload or in the body for a resumable upload.

I just thought it might be worthy of fixing.

### PR DESCRIPTION
**Pull request by Yuangwang**
### Description

Uses metadata.name as a backup to query.name in gcs uploads, this makes the storage emulator compliant with gcs api spec, fixes #3953 
### Scenarios Tested
Tested via the python gcs sdk and also by adding two new integration tests here.

### CODE REVIEW

File: scripts/storage-emulator-integration/tests.ts [hunk 1]
```diff
@@ -226,6 +226,46 @@ describe("Storage emulator", () => {
...
+            .send({ name: fileName })
+            .set({
+              Authorization: "Bearer owner",
+            })
+            .expect(200)
+            .then((res) => new URL(res.header["location"]));
+          expect(uploadURL.searchParams?.get("name")).to.equal(fileName);
+        });
+
+        it.only("should handle multipart upload with name only in metadata", async () => {
```
Comment (tonyjhuang) [inline scripts/storage-emulator-integration/tests.ts:242]: remove `only`

File: scripts/storage-emulator-integration/tests.ts [hunk 2]
```diff
@@ -226,6 +226,46 @@ describe("Storage emulator", () => {
...
+          const contentTypeHeader =
```
Comment (tonyjhuang) [inline scripts/storage-emulator-integration/tests.ts:243]: inline?

File: src/emulator/storage/apis/gcloud.ts [hunk 3]
```diff
@@ -219,6 +209,11 @@ export function createCloudEndpoints(emulator: StorageEmulator): Router {
       if (emulatorInfo === undefined) {
         return res.sendStatus(500);
       }
+      const name = getValidName(req.query, req.body);
+      if (name == null) {
```
Comment (tonyjhuang) [inline src/emulator/storage/apis/gcloud.ts:213]: go/js-style#features-equality-checks, please use ===

File: src/emulator/storage/apis/gcloud.ts [hunk 4]
```diff
@@ -237,11 +232,17 @@ export function createCloudEndpoints(emulator: StorageEmulator): Router {
...
     let metadataRaw: string;
     let dataRaw: Buffer;
+    let name: string | undefined;
     try {
       ({ metadataRaw, dataRaw } = parseObjectUploadMultipartRequest(
         contentTypeHeader!,
         await reqBodyToBuffer(req)
       ));
+      name = getValidName(req.query, JSON.parse(metadataRaw));
+      if (name == null) {
```
Comment (tonyjhuang) [inline src/emulator/storage/apis/gcloud.ts:242]: would this ever be true? name is `string | undefined`, I don't see null as an option above

File: src/emulator/storage/apis/gcloud.ts (hunk 3 above)
Comment (Yuangwang) [reply src/emulator/storage/apis/gcloud.ts:213]: The goal is to catch null and undefined with this check I think its an exception to the rule, go/js-style#features-equality-checks-exceptions

File: scripts/storage-emulator-integration/tests.ts (hunk 1 above)
Comment (Yuangwang) [reply scripts/storage-emulator-integration/tests.ts:242]: good catch!

File: src/emulator/storage/apis/gcloud.ts (hunk 4 above)
Comment (Yuangwang) [reply src/emulator/storage/apis/gcloud.ts:242]: this check should catch undefined and null. I can change it to name=== undefined too, but I think this is a bit cleaner in my eyes if anyone ever introduces a null state in the future. Lmk what you think

File: src/emulator/storage/apis/gcloud.ts [hunk 5]
```diff
@@ -237,11 +232,17 @@ export function createCloudEndpoints(emulator: StorageEmulator): Router {
     // Multipart upload
     let metadataRaw: string;
     let dataRaw: Buffer;
+    let name: string | undefined;
     try {
       ({ metadataRaw, dataRaw } = parseObjectUploadMultipartRequest(
         contentTypeHeader!,
         await reqBodyToBuffer(req)
       ));
+      name = getValidName(req.query, JSON.parse(metadataRaw));
```
Comment (tonyjhuang) [inline src/emulator/storage/apis/gcloud.ts:241]: why is this in the try catch?

File: src/emulator/storage/apis/gcloud.ts (hunk 4 above)
Comment (tonyjhuang) [reply src/emulator/storage/apis/gcloud.ts:242]: you still need to declare the type on L235 as nullable. In general I would prefer we avoid any type coercion if we can in typescript since it's fraught with unexpected behavior, see https://www.youtube.com/watch?v=et8xNAc2ic8

What about just using `string | null` as opposed to `string | undefined | null` if you want to keep it to a single equality check?

File: src/emulator/storage/apis/gcloud.ts (hunk 3 above)
Comment (tonyjhuang) [reply src/emulator/storage/apis/gcloud.ts:213]: See comments below, since `getValidName` returns `string | undefined`, you should only need `name === undefined` here since `getValidName` can't return null

File: src/emulator/storage/apis/gcloud.ts [hunk 6]
```diff
@@ -411,3 +412,8 @@ function sendObjectNotFound(req: Request, res: Response): void {
     });
   }
 }
+
+function getValidName(query: Query, metadata: IncomingMetadata): string | undefined {
```
Comment (tonyjhuang) [inline src/emulator/storage/apis/gcloud.ts:416]: tiniest of nits, would also prefer a more descriptive name, go/java-practices/naming#method-name-expectations

What is a valid name? In what contexts should you use this? Something like `getIncomingFileNameFromRequest` is a little easier to parse esp if we're not adding a comment

File: src/emulator/storage/apis/gcloud.ts (hunk 3 above)
Comment (Yuangwang) [reply src/emulator/storage/apis/gcloud.ts:213]: yeah thats fair, I'll swap it to name === undefined

File: src/emulator/storage/apis/gcloud.ts (hunk 4 above)
Comment (Yuangwang) [reply src/emulator/storage/apis/gcloud.ts:242]: yeah thats a fair point about the type coercion, I'll swap this out to name === undefined since name can only be `string | undefined` as you mentioned

File: src/emulator/storage/apis/gcloud.ts (hunk 5 above)
Comment (Yuangwang) [reply src/emulator/storage/apis/gcloud.ts:241]: Good catch, I'll move it out

File: src/emulator/storage/apis/gcloud.ts (hunk 6 above)
Comment (Yuangwang) [reply src/emulator/storage/apis/gcloud.ts:416]: Makes sense, thanks for the suggestion too! I'll add it in

File: scripts/storage-emulator-integration/tests.ts [hunk 7]
```diff
@@ -225,10 +225,14 @@ describe("Storage emulator", () => {
 
           expect(fileMetadata).to.deep.include(metadata);
         });
-
+        // TODO(b/241151246): Fix conformance tests.
         it("should handle resumable upload with name only in metadata", async () => {
+          const expectedHost = TEST_CONFIG.useProductionServers
```
Comment (tonyjhuang) [inline scripts/storage-emulator-integration/tests.ts:230]: You can probably extract this to the top level `describe` to save yourself from having to declare this in every test case

**Review by tonyjhuang — APPROVED** [review]
Thanks for the fix!
