### PR TITLE
Fix issue 1346

### LINKED ISSUE #1346: Functions Runtime process hangs when invoked for an RTDB emulator trigger
### [REQUIRED] Environment info

6.10.0

**firebase-tools:**

6.10.0

**Platform:**

Debian (glinux)

### Test case/Steps to Reproduce

I started a functions emulator with the following function:

```
const functions = require('firebase-functions');
const admin = require('firebase-admin');
const firebase = require('firebase');

admin.initializeApp();

exports.helloWorld = functions.database.instance('fake-server').ref('/hello').onWrite((snapshot, context) => {
  console.log("snapshot: " + require('util').inspect(snapshot));
  console.log("context: " + require('util').inspect(context));
  return Promise.resolve();
});
```

And sent the following event to it with curl:
```
curl -X POST http://localhost:5001/functions/prver/triggers/helloWorld -d '{"name":"projects/wyszynski-test/locations/_/functions/helloWorld","eventType":"providers/google.firebase.database/eventTypes/ref.write","params":{},"auth":{"admin":true},"data":{"data":{"hello":"other"},"delta":{"hello":"oth"}},"resource":"projects/_/instances/fake-server/refs/hello","timestamp":"2019-05-30T00:45:48.069Z","eventId":"pXCmJp0rxL7JunkX0TxdAGoiiHQ="}'
```

This mocks the request that the RTDB emulators and results in the emulator blocking [here](https://github.com/firebase/firebase-tools/blob/master/src/emulator/functionsEmulator.ts#L133). It appears that something is causes the runtime's event loop to stall, which prevents the runtime process from exiting.

### Expected behavior

I think the expected behavior is that the runtime process exits and an acknowledgement is sent from the functions emulator hub to the client.

### Actual behavior

The runtime process stalls and the client hangs.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1346 
	 
### Scenarios Tested

```js
exports.rtdbReaction = functions.database.ref('info/test').onWrite(async (change, ctx) => {
    console.log('========== RTDB FUNCTION ==========');
    console.log(`Change: ${JSON.stringify(change)}`);
    return true;
});
```

```bash
$ http PUT http://localhost:9000/info/test.json?ns=fir-dumpster "Authorization:Bearer owner" sam=stern3
```

I observed no errors.  I also tried writing the same function but have it throw an error and everything went as expected.

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -870,8 +870,12 @@ async function main(): Promise<void> {
 }
 
 if (require.main === module) {
-  main().catch((err) => {
-    new EmulatorLog("FATAL", "runtime-error", err.stack ? err.stack : err).log();
-    process.exit();
-  });
+  main()
```
Comment (bkendall) [inline src/emulator/functionsEmulatorRuntime.ts]: Not required, but, couldn't this be written:

```typescript
try {
  await main();
} catch (err) {
  new EmulatorLog...
  process.exit(1);
}
// I don't know if you'd _really_ need this, but probably wouldn't hurt:
process.exit(0);
```

Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Nah because we can't have top-level `await` :-(
