### PR TITLE
Make functions serve respect the host argument

### LINKED ISSUE #1398: firebase serve only binds to localhost
### [REQUIRED] Environment info

**firebase-tools:** 6.12.0

**Platform:** All

### [REQUIRED] Test case

See below

### [REQUIRED] Steps to reproduce

```
firebase serve -o 192.168.1.212 -p 3100 --only functions
```

### [REQUIRED] Expected behavior

Functions serving from `192.168.1.212:3100`

### [REQUIRED] Actual behavior

Functions serving from `localhost:3100`

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1398 

### Scenarios Tested

Just a simple one:

```
$ npx firebase serve -o 0.0.0.0 -p 3100 --only functions
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://0.0.0.0:3100
i  functions: Watching "/private/var/folders/xl/6lkrzp7j07581mw8_4dlt3b000643s/T/tmp.CHfsZ1kp/functions" for Cloud Functions...
i  functions: HTTP trigger initialized at http://0.0.0.0:3100/fir-dumpster/us-central1/helloWorld
```

Not sure what other scenarios are interesting.

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -435,8 +441,10 @@ You can probably fix this by running "npm install ${
     // TODO: This call requires authentication, which we should remove eventually
     this.firebaseConfig = await functionsConfig.getFirebaseConfig(this.options);
 
+    const host = this.getInfo().host;
     this.server = FunctionsEmulator.createHubServer(this.bundleTemplate, this.nodeBinary).listen(
-      this.port
+      this.port,
```
Comment (mbleigh) [inline src/emulator/functionsEmulator.ts]: Should this now be `getInfo().port`?

Also maybe just do `const {host, port} = this.getInfo();`?

**Comment by samtstern** [comment]
The fix for this issue is available in version 7.0.1
