### PR TITLE
Use public APIs where possible, address service account gaps.

### LINKED ISSUE #787: ADC Auth error: Scopes are required for this request
Hi, I’m trying to automate the deployment of firebase functions. When I run something like “GOOGLE_APPLICATION_CREDENTIALS=<path_to_json> firebase use <project_id> --non-interactive --debug” I’ve the following below error

### Version info

3.18.5

### Platform Information

container node:6.14-alpine

### Steps to reproduce

/usr/bin/docker run --rm -v /workspace:/workspace -e GOOGLE_APPLICATION_CREDENTIALS=<path_json> node:6.14-alpine node_modules/firebase-tools/bin/firebase use <project_id> --debug

### Expected behavior

To be authenticated

### Actual behavior

[2018-05-29T15:57:32.507Z] > command requires scopes: [“email”,“openid”,“https://www.googleapis.com/auth/cloudplatformprojects.readonly“,”https://www.googleapis.com/auth/firebase”]
[2018-05-29T15:57:32.507Z] > attempting to authenticate via app default credentials
[2018-05-29T15:57:32.547Z] ! auto-auth error: Scopes are required for this request.
[2018-05-29T15:57:32.547Z] > no credentials could be found or automatically retrieved

Do you have some suggestions?

### PR DESCRIPTION
**Pull request by mbleigh**
This PR attempts to address a number of gaps that prevented it from being straightforward to use a service account to authenticate for certain kinds of actions. Namely, this PR does two things:

1. Prefers `firebase.googleapis.com` public endpoints to the legacy things we had in place.
2. Prefers `cloudusage.googleapis.com` public endpoints to the semi-public things we had in place.

It also has some cleanup here and there. I think this might close #787 for most cases.

### CODE REVIEW

File: src/ensureCloudResourceLocation.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ export function ensureLocationSet(location: string, feature: string): void {
     throw new FirebaseError(
       `Cloud resource location is not set for this project but the operation ` +
         `you are attempting to perform in ${feature} requires it. ` +
-        `Please see this documentation for more details: https://firebase.google.com/docs/projects/locations.`
+        `Please see this documentation for more details: https://firebase.google.com/docs/projects/locations`
```
Comment (mbleigh) [inline src/ensureCloudResourceLocation.ts]: Removed the period here because autolinking from my terminal caused the period to be appended to the URL.

File: src/api.js [hunk 2]
```diff
@@ -135,6 +135,10 @@ var api = {
     "https://firebasehosting.googleapis.com"
   ),
   cloudRunApiOrigin: utils.envOverride("CLOUD_RUN_API_URL", "https://run.googleapis.com"),
+  serviceUsageOrigin: utils.envOverride(
```
Comment (bkendall) [inline src/api.js]: If this is what we should be using over something else, can we mark the others as deprecated with a comment?

Comment (mbleigh) [reply src/api.js]: It's what we're using instead of the previously inlined `servicemanagement.googleapis.com` origin. Nothing to comment out from that perspective.
