### PR TITLE
Fix emulator warnings

### LINKED ISSUE #1530: Firestore emulator: False negative warning about affecting production when running tests
### [REQUIRED] Environment info

**firebase-tools:** master (dad143c42445056014f6f48cc9dfa13156e3c186)

**Platform:** macOS

### [REQUIRED] Test case

Discovered while testing out the fix for: #1451.

Please note I'm not familiar with javascript nor typescript so it's very likely there is something wrong with my setup. Happy to be told that's the case.

src/index.ts:
```typescript
import * as admin from 'firebase-admin';

admin.initializeApp();

export * from './debug'
```

src/debug.ts:
```typescript
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import Timestamp = admin.firestore.Timestamp;

export const foo = functions.https.onRequest(async (req, resp) => {
    const firestore = admin.firestore();
    await firestore.doc('/users/foo/').set({
        time: Timestamp.now(),
        enabled: true,
    });
    resp.sendStatus(200);
});
```

test/index.test.ts:
```typescript
import * as assert from 'assert';

import('../src/index');

describe('Cloud Functions', () => {

    describe('foo', () => {
        it('bar', () => {
            assert.strictEqual(true, true);
        });
    });
});
```

test/mocha.opts:
```
--ui mocha-typescript
--require ts-node/register test/**/*.ts
--recursive test
```

package.json:
```json
{
  "name": "functions",
  "scripts": {
    "lint": "tslint --project tsconfig.json",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "emulators": "npm run build && firebase emulators:start",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log",
    "format": "prettier --write **/*.ts",
    "pretest": "tsc",
    "test": "mocha"
  },
  "engines": {
    "node": "8"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^8.2.0",
    "firebase-functions": "^3.1.0"
  },
  "devDependencies": {
    "@types/mocha": "^5.2.7",
    "mocha": "^6.1.4",
    "mocha-typescript": "^1.1.17",
    "prettier": "^1.18.2",
    "ts-node": "^8.3.0",
    "tslint": "^5.12.0",
    "typescript": "^3.5.2"
  },
  "private": true
}
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2015",
    "typeRoots" : ["./node_modules/@types", "./typings"]
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```
### [REQUIRED] Steps to reproduce

Run `npm run build`. Then run `firebase emulators:exec "npm run test"`.

### [REQUIRED] Expected behavior

No warning.

### [REQUIRED] Actual behavior

Shows this warning:
`⚠  The Cloud Firestore emulator is not running, so calls to Firestore will affect production.`

Logs from running with `--debug` [debug.txt](https://github.com/firebase/firebase-tools/files/3412896/debug.txt)

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1530 
	 
### Scenarios Tested

1. Tested code which has `const Timestamp = admin.firestore.Timestamp` at the top.  Previously this would print a false log about the Firestore emulator not running because our "diagnostic" run didn't include port information.   This is no longer the case.
2. Tested that `emulators:start --only functions,database` still sends RTDB traffic to the local emulator and triggers reaction functions properly, but lets Firestore traffic go to prod (and warns about it)

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -698,6 +689,19 @@ You can probably fix this by running "npm install ${
     return this.triggers;
   }
 
+  getBaseBundle(): FunctionsRuntimeBundle {
```
Comment (samtstern) [inline src/emulator/functionsEmulator.ts]: This change allows us to continually check for the port information.  So during `start()` this is the same as before but now during `connect()` we know which other emulators are running and send that info to the runtime properly.

Comment (abeisgoat) [reply src/emulator/functionsEmulator.ts]: neat
