### PR TITLE
Properly mock https.onCall

### LINKED ISSUE #2059: context.auth is undefined in callable function using emulator
### [REQUIRED] Environment info

firebase-tools: 7.16.0

**firebase-tools:**
7.16.0

**Platform:**
macOS

### [REQUIRED] Test case

Callable function: 

```ts
import * as admin from "firebase-admin";
import * as functions from "firebase-functions";
import * as tools from "firebase-tools";

admin.initializeApp();

/**
 * Deletes a book and all its children forever.
 */
export const deleteBookForever = functions
  .runWith({
    timeoutSeconds: 540,
    memory: "1GB",
  })
  .https.onCall((data, context) => {
    const path = data.path;
    console.log("Context auth ", context.auth); // undefined
    if (
      !context.auth ||
      !context.auth.uid ||
      context.auth.uid !== data.userUid
    ) {
      return Promise.reject("Forbidden. The user could not be authenticated.");
    }
    return tools.firestore
      .delete(path, {
        project: process.env.GCLOUD_PROJECT,
        recursive: true,
        yes: true,
        token: functions.config()?.fb?.token,
      })
      .then(() => path)
      .catch(err => {
        console.error("Delete ERROR:", err.message);
      });
  });
```
Emulator setup client side:

```ts
if (window.location.hostname === "localhost") {
   app.firestore().settings({
        host: "localhost:8081",
        ssl: false,
      });
  app.functions().useFunctionsEmulator("http://localhost:5001");
}
```

### [REQUIRED] Expected behavior

`context.auth.uid` should be defined with the uid of the currently signed in user

### [REQUIRED] Actual behavior
`context.auth` is undefined

`console.log(context.rawRequest.headers["x-callable-context-auth"])` outputs:

```ts
{
    req: {
      token: {
        name: "maierson",
        iss: "https://securetoken.google.com/<project-id>",
        aud: "<project-id>",
        auth_time: 1583853288,
        user_id: "<my-user-id>",
        sub: "<my-user-id>",
        iat: 1585058399,
        exp: 1585061999,
        email: "<my-email>",
        email_verified: false,
        firebase: {
          identities: { email: ["<my-email>"] },
          sign_in_provider: "password",
        },
      },
    },
  };
```

Note. The authenticated user is obtained from the production system (no emulator). All the substituted placeholders are correct (<my-project>, <my-user-id> and <my-email>) as per the production environment.

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2059

The way we were mocking before didn't work if a `.runWith` call was chained in.  This is much more resilient.
	 
### Scenarios Tested

Used the exact setup in #2059

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { EmulatorLog } from "./types";
-import { CloudFunction, DeploymentOptions } from "firebase-functions";
+import { CloudFunction, DeploymentOptions, https } from "firebase-functions";
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: @abeisgoat any issue with this import?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -446,61 +450,72 @@ async function initializeFirebaseFunctionsStubs(frb: FunctionsRuntimeBundle): Pr
...
+  if (compareVersionStrings(firebaseFunctionsResolution.version, "3.1.0") >= 0) {
+    onCallInnerMethodName = "_onCallWithOptions";
+  }
+  const onCallMethodOriginal = httpsProvider[onCallInnerMethodName];
 
-      return handler(data, context);
-    };
+  httpsProvider[onCallInnerMethodName] = (handler: CallableHandler, opts: DeploymentOptions) => {
+    const wrapped = wrapCallableHandler(handler);
+    const cf = onCallMethodOriginal(wrapped, opts);
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: @abeisgoat I didn't do the `__emulator_func` thing here as that was not compatible with `onCall`.  Just want to double check that's ok.

File: CHANGELOG.md [hunk 3]
```diff
@@ -0,0 +1 @@
+* Fixes an auth issue with `https.onCall` functions when rurntime options (`runWith`) are specified (#2059).
```
Comment (bkendall) [inline CHANGELOG.md]:
```suggestion
* Fixes an auth issue with `https.onCall` functions when runtime options (`runWith`) are specified (#2059).
```

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: yeah so `__emulator_func` was a hack to get around our implementation of pure HTTPS functions to never returning the result of the user function (because it was wrapped in `(req, res):void => {}`) so since onCall methods support promises natively (like other background functions) then you shouldn't need it, so as long as you verify that returning a long-lived promise works as intended then you should be good to drop it.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 1 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: What issue do you think this may cause?

Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: I don't think anything, I just wanted to double-check as I know deps in this file are super sensitive.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: OK I will give that a try.

Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Tested with this function, worked as expected:
```js
exports.onCallPromise = functions.runWith({
  timeoutSeconds: 60,
  memory: "1GB"
}).https.onCall((data, context) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({ 
        status: 'waited, cool beans',
        auth: context.auth,
      });
    }, 3000);
  });
});
```
