### PR TITLE
Fixing invalid version error when emulating functions

### LINKED ISSUE #4403: Functions Emulator Getting `TypeError: Invalid Version:` when updating to anything above  `10.2.1`
### [REQUIRED] Environment info

**firebase-tools:** `10.2.1` -> `10.2.2` or higher

**Platform:** Windows

### [REQUIRED] Steps to reproduce

I start my emulator using the following `firebase.json` file.

```
{
    "database": {
        "rules": "database.rules.json"
    },
    "firestore": {
        "rules": "firestore.rules",
        "indexes": "firestore.indexes.json"
    },
    "functions": {
        "source": "projects/cloud-functions"
    },
    "hosting": [
        {
            "target": "api",
            "rewrites": [
                {
                    "source": "**",
                    "function": "api"
                }
            ]
        }
    ],
    "storage": {
        "rules": "storage.rules"
    },
    "emulators": {
        "auth": {
            "port": 9099,
            "host": "0.0.0.0"
        },
        "functions": {
            "port": 5001,
            "host": "0.0.0.0"
        },
        "firestore": {
            "port": 8080,
            "host": "0.0.0.0"
        },
        "database": {
            "port": 9000,
            "host": "0.0.0.0"
        },
        "hosting": {
            "port": 5000,
            "host": "0.0.0.0"
        },
        "storage": {
            "port": 9199,
            "host": "0.0.0.0"
        },
        "ui": {
            "enabled": true,
            "port": 4090,
            "host": "0.0.0.0"
        }
    }
}
```

### [REQUIRED] Expected behavior
When I update my firebase-tools I expect that the emulator still works. 

### [REQUIRED] Actual behavior
When I update to anything higher then  `10.2.1`  I'm getting a `TypeError: Invalid Version:` error. 

Here is the full stack 
```
[debug] [2022-04-05T13:52:26.132Z] TypeError: Invalid Version: 
    at new SemVer (C:\Users\j\development\AmI\node_modules\firebase-tools\node_modules\semver\semver.js:323:11)
    at compare (C:\Users\j\development\AmI\node_modules\firebase-tools\node_modules\semver\semver.js:614:10)
    at Function.lt (C:\Users\j\development\AmI\node_modules\firebase-tools\node_modules\semver\semver.js:648:10)
    at Delegate.discoverSpec (C:\Users\j\development\AmI\node_modules\firebase-tools\lib\deploy\functions\runtimes\node\index.js:87:24)
    at FunctionsEmulator.loadTriggers (C:\Users\j\development\AmI\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:272:61)
    at async Promise.all (index 0)
    at async FunctionsEmulator.connect (C:\Users\j\development\AmI\node_modules\firebase-tools\lib\emulator\functionsEmulator.js:231:9)
    at async Object.startAll (C:\Users\j\development\AmI\node_modules\firebase-tools\lib\emulator\controller.js:487:13)
    at async Command.actionFn (C:\Users\j\development\AmI\node_modules\firebase-tools\lib\commands\emulators-start.js:28:35)
[error] 
[error] Error: An unexpected error has occurred.
```

### PR DESCRIPTION
**Pull request by joehan**
### Description
When unable to identify the version of firebase-functions in use, we were throwing `TypeError: Invalid Version:` errors due to trying to parse "" into Semver. This should fix #4403, where some users are experiencing this when trying to emulate functions.

### CODE REVIEW

File: src/deploy/functions/runtimes/node/index.ts [hunk 1]
```diff
@@ -129,6 +129,18 @@ export class Delegate {
     env: backend.EnvironmentVariables
   ): Promise<backend.Backend> {
     if (previews.functionsv2) {
+      if (semver.valid(this.sdkVersion)) {
```
Comment (taeold) [inline src/deploy/functions/runtimes/node/index.ts:132]: Should this be

```js
if (!semver.valid(this.sdkVersion))
```

instead?

Comment (joehan) [reply src/deploy/functions/runtimes/node/index.ts]: Good catch, that's what i get for moving too quickly.

**Review by taeold — APPROVED** [review]
