### PR TITLE
App Hosting Emulator bug - apphosting emulator info is not complete when env vars for emulators are set

### LINKED ISSUE #8224: TypeError while emulators:start apphosting
### [REQUIRED] Environment info
firebase --version
13.31.1

Windows 11

### [REQUIRED] Test case
0.- Upgrade to 13.31.1
1.- Run firebase emulators:start with apphosting configuration

### [REQUIRED] Steps to reproduce
1.- firebase emulators:start
firebase.json
  "emulators": {
    "apphosting": {
      "port": 4200,
      "rootDirectory": "./frontend",
      "startCommand": "npm run start"
    },

package.json
"scripts": {
    "start": "nx serve --configuration=development",

The same apphosting configuration was running ok with lower firebase-tools version, I think it was 13.28.0

even using the default startcommand : "startCommand": "npm run dev" 

### [REQUIRED] Expected behavior

Emulator of apphosting should start 

### [REQUIRED] Actual behavior

firebase emulators:start --debug
[2025-02-18T01:36:53.865Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2025-02-18T01:36:53.866Z] > authorizing via signed-in user (haptie@gmail.com)
[2025-02-18T01:36:53.942Z] java version "17.0.12" 2024-07-16 LTS

[2025-02-18T01:36:53.943Z] Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)

[2025-02-18T01:36:53.967Z] Parsed Java major version: 17
i  emulators: Starting emulators: apphosting, auth, functions, firestore, pubsub, storage, eventarc, tasks, extensions {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: apphosting, auth, functions, firestore, pubsub, storage, eventarc, tasks, extensions"}}
[2025-02-18T01:36:53.968Z] Checked if tokens are valid: true, expires at: 1739844288527
[2025-02-18T01:36:53.969Z] Checked if tokens are valid: true, expires at: 1739844288527
[2025-02-18T01:36:53.970Z] >>> [apiv2][query] GET https://cloudresourcemanager.googleapis.com/v1/projects/weddly-stg [none]
[2025-02-18T01:36:54.270Z] <<< [apiv2][status] GET https://cloudresourcemanager.googleapis.com/v1/projects/weddly-stg 200
[2025-02-18T01:36:54.270Z] <<< [apiv2][body] GET https://cloudresourcemanager.googleapis.com/v1/projects/weddly-stg {"projectNumber":"322472806197","projectId":"weddly-stg","lifecycleState":"ACTIVE","name":"weddly-stg","labels":{"firebase":"enabled","firebase-core":"disabled"},"createTime":"2024-12-07T06:41:29.620937Z"}
[2025-02-18T01:36:54.283Z] [logging] Logging Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.283Z] [apphosting] App Hosting Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.283Z] [auth] Authentication Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.283Z] [firestore] Firestore Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.284Z] [firestore.websocket] websocket server for firestore only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.284Z] [pubsub] Pub/Sub Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.284Z] [storage] Storage Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.284Z] assigned listening specs for emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4000},{"address":"::1","family":"IPv6","port":4000}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"apphosting":[{"address":"127.0.0.1","family":"IPv4","port":4200}],"auth":[{"address":"127.0.0.1","family":"IPv4","port":9099}],"firestore":[{"address":"127.0.0.1","family":"IPv4","port":8080}],"firestore.websocket":[{"address":"127.0.0.1","family":"IPv4","port":9150}],"pubsub":[{"address":"127.0.0.1","family":"IPv4","port":8085}],"storage":[{"address":"127.0.0.1","family":"IPv4","port":9199}]},"metadata":{"message":"assigned listening specs for emulators"}}
!  emulators: It seems that you are running multiple instances of the emulator suite for project weddly-stg. This may result in unexpected behavior. 
[2025-02-18T01:36:54.289Z] [hub] writing locator at C:\Users\hapti\AppData\Local\Temp\hub-weddly-stg.json
[2025-02-18T01:36:54.296Z] [Extensions] Started Extensions emulator, this is a noop.
[2025-02-18T01:36:54.300Z] [functions] Functions Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.301Z] [eventarc] Eventarc Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.301Z] [tasks] Cloud Tasks Emulator only supports listening on one address (127.0.0.1). Not listening on ::1
[2025-02-18T01:36:54.301Z] late-assigned ports for functions and eventarc emulators {"user":{"hub":[{"address":"127.0.0.1","family":"IPv4","port":4400},{"address":"::1","family":"IPv6","port":4400}],"ui":[{"address":"127.0.0.1","family":"IPv4","port":4000},{"address":"::1","family":"IPv6","port":4000}],"logging":[{"address":"127.0.0.1","family":"IPv4","port":4500}],"apphosting":[{"address":"127.0.0.1","family":"IPv4","port":4200}],"auth":[{"address":"127.0.0.1","family":"IPv4","port":9099}],"firestore":[{"address":"127.0.0.1","family":"IPv4","port":8080}],"firestore.websocket":[{"address":"127.0.0.1","family":"IPv4","port":9150}],"pubsub":[{"address":"127.0.0.1","family":"IPv4","port":8085}],"storage":[{"address":"127.0.0.1","family":"IPv4","port":9199}],"functions":[{"address":"127.0.0.1","family":"IPv4","port":5001}],"eventarc":[{"address":"127.0.0.1","family":"IPv4","port":9299}],"tasks":[{"address":"127.0.0.1","family":"IPv4","port":9499}]},"metadata":{"message":"late-assigned ports for functions and eventarc emulators"}}
!  functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: database, hosting, dataconnect {"metadata":{"emulator":{"name":"functions"},"message":"The following emulators are not running, calls to these services from the Functions emulator will affect production: \u001b[1mdatabase, hosting, dataconnect\u001b[22m"}}
[2025-02-18T01:36:54.305Z] defaultcredentials: writing to file C:\Users\hapti\AppData\Roaming\firebase\haptie_gmail_com_application_default_credentials.json
[2025-02-18T01:36:54.308Z] Setting GAC to C:\Users\hapti\AppData\Roaming\firebase\haptie_gmail_com_application_default_credentials.json {"metadata":{"emulator":{"name":"functions"},"message":"Setting GAC to C:\\Users\\hapti\\AppData\\Roaming\\firebase\\haptie_gmail_com_application_default_credentials.json"}}
[2025-02-18T01:36:54.308Z] Checked if tokens are valid: true, expires at: 1739844288527
[2025-02-18T01:36:54.308Z] Checked if tokens are valid: true, expires at: 1739844288527
[2025-02-18T01:36:54.308Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/weddly-stg/adminSdkConfig [none]
[2025-02-18T01:36:54.688Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/weddly-stg/adminSdkConfig 200
[2025-02-18T01:36:54.689Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/weddly-stg/adminSdkConfig {"projectId":"weddly-stg","storageBucket":"weddly-stg.firebasestorage.app"}
[2025-02-18T01:36:54.714Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: auto_download"}}
[2025-02-18T01:36:54.714Z] Ignoring unsupported arg: single_project_mode_error {"metadata":{"emulator":{"name":"firestore"},"message":"Ignoring unsupported arg: single_project_mode_error"}}
[2025-02-18T01:36:54.715Z] Starting Firestore Emulator with command {"binary":"java","args":["-Dgoogle.cloud_firestore.debug_log_level=FINE","-Duser.language=en","-jar","C:\\Users\\hapti\\.cache\\firebase\\emulators\\cloud-firestore-emulator-v1.19.8.jar","--host","127.0.0.1","--port",8080,"--websocket_port",9150,"--project_id","weddly-stg","--rules","C:\\Users\\hapti\\WebstormProjects\\weddly\\firestore.rules","--single_project_mode",true,"--functions_emulator","127.0.0.1:5001"],"optionalArgs":["port","webchannel_port","host","rules","websocket_port","functions_emulator","seed_from_export","project_id","single_project_mode"],"joinArgs":false,"shell":false,"port":8080} {"metadata":{"emulator":{"name":"firestore"},"message":"Starting Firestore Emulator with command {\"binary\":\"java\",\"args\":[\"-Dgoogle.cloud_firestore.debug_log_level=FINE\",\"-Duser.language=en\",\"-jar\",\"C:\\\\Users\\\\hapti\\\\.cache\\\\firebase\\\\emulators\\\\cloud-firestore-emulator-v1.19.8.jar\",\"--host\",\"127.0.0.1\",\"--port\",8080,\"--websocket_port\",9150,\"--project_id\",\"weddly-stg\",\"--rules\",\"C:\\\\Users\\\\hapti\\\\WebstormProjects\\\\weddly\\\\firestore.rules\",\"--single_project_mode\",true,\"--functions_emulator\",\"127.0.0.1:5001\"],\"optionalArgs\":[\"port\",\"webchannel_port\",\"host\",\"rules\",\"websocket_port\",\"functions_emulator\",\"seed_from_export\",\"project_id\",\"single_project_mode\"],\"joinArgs\":false,\"shell\":false,\"port\":8080}"}}
i  firestore: Firestore Emulator logging to firestore-debug.log {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator logging to \u001b[1mfirestore-debug.log\u001b[22m"}}
+  firestore: Firestore Emulator UI websocket is running on 9150. {"metadata":{"emulator":{"name":"firestore"},"message":"Firestore Emulator UI websocket is running on 9150."}}
[2025-02-18T01:37:01.766Z] Ignoring unsupported arg: projectId {"metadata":{"emulator":{"name":"pubsub"},"message":"Ignoring unsupported arg: projectId"}}
[2025-02-18T01:37:01.767Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"pubsub"},"message":"Ignoring unsupported arg: auto_download"}}
[2025-02-18T01:37:01.767Z] Starting Pub/Sub Emulator with command {"binary":"C:\\Users\\hapti\\.cache\\firebase\\emulators\\pubsub-emulator-0.8.14\\pubsub-emulator\\bin\\cloud-pubsub-emulator.bat","args":["--host=127.0.0.1","--port=8085"],"optionalArgs":["port","host"],"joinArgs":true,"shell":true,"port":8085} {"metadata":{"emulator":{"name":"pubsub"},"message":"Starting Pub/Sub Emulator with command {\"binary\":\"C:\\\\Users\\\\hapti\\\\.cache\\\\firebase\\\\emulators\\\\pubsub-emulator-0.8.14\\\\pubsub-emulator\\\\bin\\\\cloud-pubsub-emulator.bat\",\"args\":[\"--host=127.0.0.1\",\"--port=8085\"],\"optionalArgs\":[\"port\",\"host\"],\"joinArgs\":true,\"shell\":true,\"port\":8085}"}}
i  pubsub: Pub/Sub Emulator logging to pubsub-debug.log {"metadata":{"emulator":{"name":"pubsub"},"message":"Pub/Sub Emulator logging to \u001b[1mpubsub-debug.log\u001b[22m"}}
[2025-02-18T01:37:01.787Z] 
C:\Users\hapti\WebstormProjects\weddly>if "Windows_NT" == "Windows_NT" setlocal
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>if \"Windows_NT\" == \"Windows_NT\" setlocal\r\n"}}
[2025-02-18T01:37:01.788Z] 
C:\Users\hapti\WebstormProjects\weddly>set DIRNAME=C:\Users\hapti\.cache\firebase\emulators\pubsub-emulator-0.8.14\pubsub-emulator\bin\ 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set DIRNAME=C:\\Users\\hapti\\.cache\\firebase\\emulators\\pubsub-emulator-0.8.14\\pubsub-emulator\\bin\\ \r\n"}}
[2025-02-18T01:37:01.789Z] 
C:\Users\hapti\WebstormProjects\weddly>if "C:\Users\hapti\.cache\firebase\emulators\pubsub-emulator-0.8.14\pubsub-emulator\bin\" == "" set DIRNAME=. 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>if \"C:\\Users\\hapti\\.cache\\firebase\\emulators\\pubsub-emulator-0.8.14\\pubsub-emulator\\bin\\\" == \"\" set DIRNAME=. \r\n"}}
[2025-02-18T01:37:01.789Z] 
C:\Users\hapti\WebstormProjects\weddly>set APP_BASE_NAME=cloud-pubsub-emulator 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set APP_BASE_NAME=cloud-pubsub-emulator \r\n"}}
[2025-02-18T01:37:01.789Z] 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\n"}}
[2025-02-18T01:37:01.790Z] C:\Users\hapti\WebstormProjects\weddly>set APP_HOME=C:\Users\hapti\.cache\firebase\emulators\pubsub-emulator-0.8.14\pubsub-emulator\bin\.. 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"C:\\Users\\hapti\\WebstormProjects\\weddly>set APP_HOME=C:\\Users\\hapti\\.cache\\firebase\\emulators\\pubsub-emulator-0.8.14\\pubsub-emulator\\bin\\.. \r\n"}}
[2025-02-18T01:37:01.790Z] 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\n"}}
[2025-02-18T01:37:01.790Z] C:\Users\hapti\WebstormProjects\weddly>set DEFAULT_JVM_OPTS= 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"C:\\Users\\hapti\\WebstormProjects\\weddly>set DEFAULT_JVM_OPTS= \r\n"}}
[2025-02-18T01:37:01.791Z] 
C:\Users\hapti\WebstormProjects\weddly>if defined JAVA_HOME  {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>if defined JAVA_HOME "}}
[2025-02-18T01:37:01.791Z] goto findJavaFromJavaHome 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"goto findJavaFromJavaHome \r\n"}}
[2025-02-18T01:37:01.791Z] 
C:\Users\hapti\WebstormProjects\weddly>set JAVA_HOME=C:\Program Files\Java\jdk-17 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set JAVA_HOME=C:\\Program Files\\Java\\jdk-17 \r\n"}}
[2025-02-18T01:37:01.792Z] 
C:\Users\hapti\WebstormProjects\weddly>set JAVA_EXE=C:\Program Files\Java\jdk-17/bin/java.exe 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set JAVA_EXE=C:\\Program Files\\Java\\jdk-17/bin/java.exe \r\n"}}
[2025-02-18T01:37:01.792Z] 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\n"}}
[2025-02-18T01:37:01.792Z] C:\Users\hapti\WebstormProjects\weddly>if exist "C:\Program Files\Java\jdk-17/bin/java.exe" goto init 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"C:\\Users\\hapti\\WebstormProjects\\weddly>if exist \"C:\\Program Files\\Java\\jdk-17/bin/java.exe\" goto init \r\n"}}
[2025-02-18T01:37:01.793Z] 
C:\Users\hapti\WebstormProjects\weddly>if not "Windows_NT" == "Windows_NT" goto win9xME_args 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>if not \"Windows_NT\" == \"Windows_NT\" goto win9xME_args \r\n"}}
[2025-02-18T01:37:01.793Z] 
C:\Users\hapti\WebstormProjects\weddly>set CMD_LINE_ARGS= 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set CMD_LINE_ARGS= \r\n"}}
[2025-02-18T01:37:01.794Z] 
C:\Users\hapti\WebstormProjects\weddly>set _SKIP=2 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set _SKIP=2 \r\n"}}
[2025-02-18T01:37:01.794Z] 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\n"}}
[2025-02-18T01:37:01.794Z] C:\Users\hapti\WebstormProjects\weddly>if "x--host" == "x" goto execute 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"C:\\Users\\hapti\\WebstormProjects\\weddly>if \"x--host\" == \"x\" goto execute \r\n"}}
[2025-02-18T01:37:01.794Z] 
C:\Users\hapti\WebstormProjects\weddly>set CMD_LINE_ARGS=--host=127.0.0.1 --port=8085 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set CMD_LINE_ARGS=--host=127.0.0.1 --port=8085 \r\n"}}
[2025-02-18T01:37:01.795Z] 
C:\Users\hapti\WebstormProjects\weddly>set CLASSPATH=C:\Users\hapti\.cache\firebase\emulators\pubsub-emulator-0.8.14\pubsub-emulator\bin\..\lib\cloud-pubsub-emulator-0.8.14-all.jar 
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>set CLASSPATH=C:\\Users\\hapti\\.cache\\firebase\\emulators\\pubsub-emulator-0.8.14\\pubsub-emulator\\bin\\..\\lib\\cloud-pubsub-emulator-0.8.14-all.jar \r\n"}}
[2025-02-18T01:37:01.796Z] 
C:\Users\hapti\WebstormProjects\weddly>"C:\Program Files\Java\jdk-17/bin/java.exe"     -jar "C:\Users\hapti\.cache\firebase\emulators\pubsub-emulator-0.8.14\pubsub-emulator\bin\..\lib\cloud-pubsub-emulator-0.8.14-all.jar" --host=127.0.0.1 --port=8085
 {"metadata":{"emulator":{"name":"pubsub"},"message":"\r\nC:\\Users\\hapti\\WebstormProjects\\weddly>\"C:\\Program Files\\Java\\jdk-17/bin/java.exe\"     -jar \"C:\\Users\\hapti\\.cache\\firebase\\emulators\\pubsub-emulator-0.8.14\\pubsub-emulator\\bin\\..\\lib\\cloud-pubsub-emulator-0.8.14-all.jar\" --host=127.0.0.1 --port=8085 \r\n"}}
[2025-02-18T01:37:03.018Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"storage"},"message":"Ignoring unsupported arg: port"}}
[2025-02-18T01:37:03.748Z] Temp file directory for storage emulator: C:\Users\hapti\AppData\Local\Temp/firebase/storage/blobs {"metadata":{"emulator":{"name":"storage"},"message":"Temp file directory for storage emulator: C:\\Users\\hapti\\AppData\\Local\\Temp/firebase/storage/blobs"}}
[2025-02-18T01:37:03.756Z] TypeError: Cannot read properties of undefined (reading 'includes')
    at formatHost (C:\Users\hapti\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\functionsEmulatorShared.js:284:14)
    at setEnvVarsForEmulators (C:\Users\hapti\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\env.js:9:63)
    at getEmulatorEnvs (C:\Users\hapti\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\apphosting\serve.js:55:38)
    at serve (C:\Users\hapti\AppData\Roaming\npm\node_modules\firebase-tools\lib\emulator\apphosting\serve.js:35:88)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Error: An unexpected error has occurred.

### PR DESCRIPTION
**Pull request by mathu97**
Fixes #8224.

The issue was that the App Hosting emulator info (port / host) is not ready when the environment variables for emulators are being set here: https://github.com/firebase/firebase-tools/blob/5b04f7d375bdd97d806253bb03d2a1988aeae567/src/emulator/apphosting/serve.ts#L60C8-L60C23. But we don't need to set the apphosting emulator's port/host (not needed for apphosting= emulator autoinit).

### CODE REVIEW

**Review by annajowang — APPROVED** [review]

File: src/emulator/apphosting/serve.ts [hunk 1]
```diff
@@ -85,9 +85,15 @@ function availablePort(host: string, port: number): Promise<boolean> {
...
-function getEmulatorEnvs(): Record<string, string> {
+/**
+ * Exported for unit tests
+ */
+export function getEmulatorEnvs(): Record<string, string> {
   const envs: Record<string, string> = {};
-  const emulatorInfos = EmulatorRegistry.listRunningWithInfo();
+  // No need to set envs for the apphosting emulator itself.
+  const emulatorInfos = EmulatorRegistry.listRunningWithInfo().filter(
+    (emulator) => emulator.name !== "apphosting",
```
Comment (taeold) [inline src/emulator/apphosting/serve.ts:95]: should we be using enums instead?

https://github.com/firebase/firebase-tools/blob/5b04f7d375bdd97d806253bb03d2a1988aeae567/src/emulator/types.ts#L11

File: src/emulator/apphosting/serve.ts [hunk 2]
```diff
@@ -85,9 +85,15 @@ function availablePort(host: string, port: number): Promise<boolean> {
...
 }
 
-function getEmulatorEnvs(): Record<string, string> {
+/**
+ * Exported for unit tests
+ */
+export function getEmulatorEnvs(): Record<string, string> {
   const envs: Record<string, string> = {};
-  const emulatorInfos = EmulatorRegistry.listRunningWithInfo();
+  // No need to set envs for the apphosting emulator itself.
```
Comment (taeold) [inline src/emulator/apphosting/serve.ts:93]: nit* maybe this comment belongs to the filter condtion

**Review by taeold — APPROVED** [review]
