### PR TITLE
Correctly set FUNCTION_TARGET for grouped functions

### LINKED ISSUE #6408: Grouping functions doesn't work anymore in firebase-tools 12.6.0 with TS
### [REQUIRED] Environment info

**firebase-tools:** 12.6.0

**Platform:** : Ubuntu

### [REQUIRED] Test case

Grouping functions doesn't work anymore in firebase-tools 12.6.0

### [REQUIRED] Steps to reproduce

Init a firebase project with Typescript.

```firebase.json
{
  "functions": [
    {
      "source": "functions",
      "codebase": "default",
      "ignore": [
        "node_modules",
        ".git",
        "firebase-debug.log",
        "firebase-debug.*.log"
      ],
      "predeploy": [
        "npm --prefix \"$RESOURCE_DIR\" run build"
      ]
    }
  ]
}
```

Write index.ts:
```ts
import { onRequest } from 'firebase-functions/v2/https'

export const Hello = {
  world: onRequest((req, res) => {
    res.send('Hello World')
  })
}
```

### [REQUIRED] Expected behavior

Install firebase-tools@12.5.4
```bash
npm install -g firebase-tools@12.5.4
```

Deploy the function `firebase deploy --only functions`

It works:
```
✔  functions: functions folder uploaded successfully
i  functions: creating Node.js 20 (2nd Gen) function Hello-world(us-central1)...
✔  functions[Hello-world(us-central1)] Successful create operation.
Function URL (Hello-world(us-central1)): https://hello-world-nknfuqmg3q-uc.a.run.app
i  functions: cleaning up build files...

✔  Deploy complete!
```

### [REQUIRED] Actual behavior

Install firebase-tools@12.6.0
```bash
npm install -g firebase-tools@12.6.0
```

Deploy the function `firebase deploy --only functions`

It fail:
```
i  functions: creating Node.js 20 (2nd Gen) function Hello-world(us-central1)...
Could not create or update Cloud Run service hello-world, Container Healthcheck failed. Revision 'hello-world-00001-pav' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.

Logs URL: https://console.cloud.google.com/logs/viewer?project=nomnomnest&resource=cloud_run_revision/service_name/hello-world/revision_name/hello-world-00001-pav&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22hello-world%22%0Aresource.labels.revision_name%3D%22hello-world-00001-pav%22 
For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start

Functions deploy had errors with the following functions:
        Hello-world(us-central1)
i  functions: cleaning up build files...

Error: There was an error deploying functions
```

CloudRun Logs:
image

### PR DESCRIPTION
**Pull request by joehan**
### Description
Fixed an issue where we were setting the wrong FUNCTION_TARGET for grouped functions. Fixes #6408

### Scenarios Tested

I was able to repro the original issue & confirmed that the fix worked, using this following steps: 

Steps to reproduce the issue:
1. Run `firebase init functions --project <project_id>`
2. Select “Typescript”
3. Copy the code snippet provided by author to `index.ts` file:
```ts
import { onRequest } from 'firebase-functions/v2/https'

export const Hello = {
  world: onRequest((req, res) => {
    res.send('Hello World')
  })
}
```
4. Run `firebase deploy --only functions`

### CODE REVIEW

**Review by blidd-google — APPROVED** [review]

File: src/gcp/cloudfunctionsv2.ts [hunk 1]
```diff
@@ -331,7 +331,7 @@ export async function createFunction(cloudFunction: InputCloudFunction): Promise
 
   cloudFunction.serviceConfig.environmentVariables = {
     ...cloudFunction.serviceConfig.environmentVariables,
-    FUNCTION_TARGET: functionId,
+    FUNCTION_TARGET: functionId.replace("-", "."),
```
Comment (mortenbekditlevsen) [inline src/gcp/cloudfunctionsv2.ts:334]: 'replace' only replaces first instance of the search string. It should be using 'replaceAll'.

File: src/gcp/cloudfunctionsv2.ts [hunk 2]
```diff
@@ -439,7 +439,7 @@ export async function updateFunction(cloudFunction: InputCloudFunction): Promise
...
```
Comment (mortenbekditlevsen) [inline src/gcp/cloudfunctionsv2.ts:442]: 'replace' only replaces first instance of the search string. It should be using 'replaceAll'.
