### PR TITLE
Fix NaN when using Emulator UI defaut port

### LINKED ISSUE #2627: Emulator UI port shows as NaN on firebase init emulators
### [REQUIRED] Environment info

Latest `firebase-tools` GitHub master

**firebase-tools:** 8.10.0

**Platform:** ALL

### [REQUIRED] Test case

Use a new project that does not have 

### [REQUIRED] Steps to reproduce

1. `firebase init emulators`
2. Enable Emulator UI (default)
3. Do not select a port (default)

### [REQUIRED] Expected behavior

It displays "port" as empty or "(automatic)" after confirming a port selection

### [REQUIRED] Actual behavior

It shows "NaN" as the port number, which looks broken and tricks me into thinking something went wrong ("should I have selected a port?")

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #2627 

### Scenarios Tested

  * Init with empty port
  * Init with custom port
  * Init with invalid port

### Sample Commands

N/A

### CODE REVIEW

File: src/init/features/emulators.ts [hunk 1]
```diff
@@ -79,13 +79,18 @@ export async function doSetup(setup: any, config: any) {
...
               uiDesc
             )} (leave empty to use any available port)?`,
           },
         ]);
+
+        // Parse the input as a number
+        const portNum = Number.parseInt(ui.port);
+        ui.port = isNaN(portNum) ? undefined : portNum;
+
         if (!ui.port) {
```
Comment (yuchenshi) [inline src/init/features/emulators.ts:94]: We can drop this now

**Review by yuchenshi — APPROVED** [review]
