### PR TITLE
Fixes #1320, #1322, #1364, and #1312

### LINKED ISSUE #1312: HTTP functions path prefix differences between emulated and deployed functions
**For Posterity**

This stems from a conversation https://github.com/firebase/firebase-tools/issues/1279

[@christiannaths commented](https://github.com/firebase/firebase-tools/issues/1279#issuecomment-493181822)

> As far as I can tell, there is now no way to get the actual request path when running functions in the emulator.

> For example, I need to generate an oauth callback url for the google OAuth2Client. I managed this before by using a combination of request.protocol, request.headers.host, and request.path. After this change–given that request.path no longer reflects the actual path, and the actual path is not stored anywhere–I'm at a loss as to how I can accomplish this without some hackery.

[@abeisgoat commented](https://github.com/firebase/firebase-tools/issues/1279#issuecomment-493548486)

> @christiannaths Thanks for your input, this is a great question and if I'm understanding correctly, you aren't saying that the old emulator handled this well, just that the new one (with the change to match the old one) now breaks you?

> If this is the case, then I think this will be a prime candidate to introduce into emulators:start so serve will have the same bug as the old emulator and emulators:start will make the prefix available in some way (along with some other IS_FIREBASE_EMULATOR type env.)

> That being said, since the original issue that @tmcf reported is now fixed, @christiannaths can you open a new issue with your thoughts? Feel free to just copy/paste what you said here, I just want to keep things organized.

### [REQUIRED] Environment info

**firebase-tools:** 6.9.2

**Platform:** macOS

### [REQUIRED] Test case

**Public repo:** https://github.com/christiannaths/fbfn-path-prefix-example
**Deployed function**: https://us-central1-christiannaths-com.cloudfunctions.net/fnEcho

```js
const functions = require("firebase-functions");
const admin = require("firebase-admin");
const { pick, omitBy } = require("lodash");

admin.initializeApp();

exports.echoFn = functions.https.onRequest((req, res) => {
  const request = pick(req, [
    "domain",
    "headers",
    "url",
    "method",
    "baseUrl",
    "originalUrl",
    "params"
  ]);

  const env = omitBy(process.env, (value, key) => key.startsWith("npm_"));

  res.send({ request, env });
});
```

### [REQUIRED] Steps to reproduce

Run above test function in a new project, once locally in the emulator, and once deployed. Observe the response from each scenario. (see _Actual behavior_ below for a sample)

### [REQUIRED] Expected behavior

I expect the paths to be exactly the same in the emulator as they are once deployed, or at least be able to reason about the differences.

I see three ways to solve this:

1. Do away with the prefix entirely (best)
1. Single out and expose just the function path prefix somewhere, if it exists.
1. Let me know that the function is being run in the emulator (worst)

To be perfectly honest, I strongly feel that having a prefix in the emulator at all is unexpected behavior, though I do understand the behaviour exists for legacy support.

As a suggestion, perhaps the newer `firebase emulators:start` could serve the functions without the prefix, and legacy behaviour could be supported with `firebase serve`.

#### Emulated

```
functions: HTTP trigger initialized at http://localhost:5001/christiannaths-com/us-central1/fnEcho
```

<details><summary>response</summary>

```json
{
  "request": {
    "domain": null,
    "headers": {
      "host": "localhost:5001",
      "connection": "keep-alive",
      "cache-control": "max-age=0",
      "upgrade-insecure-requests": "1",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36",
      "dnt": "1",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.9"
    },
    "url": "/christiannaths-com/us-central1/fnEcho",
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/christiannaths-com/us-central1/fnEcho",
    "params": {
      "0": "christiannaths-com/us-central1/fnEcho"
    }
  },
  "env": {
    "...note": "A few non-relevant env vars have been removed",
    "NODE": "/Users/christiannaths/.n/bin/node",
    "INIT_CWD": "/Users/christiannaths/Desktop/firebase-functions-path-prefix-example/functions",
    "TMPDIR": "/var/folders/d3/nflw9g251rb3v09s0ymcc3v80000gn/T/",
    "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.UAAe7tnG6D/Listeners",
    "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x52",
    "_": "/usr/local/bin/firebase",
    "PWD": "/Users/christiannaths/Desktop/firebase-functions-path-prefix-example/functions",
    "GCLOUD_PROJECT": "christiannaths-com",
    "FIREBASE_CONFIG": "{\"databaseURL\":\"https://christiannaths-com.firebaseio.com\",\"storageBucket\":\"christiannaths-com.appspot.com\",\"projectId\":\"christiannaths-com\"}"
  }
}
```

</details>

#### Deployed

```
Function URL (fnEcho): https://us-central1-christiannaths-com.cloudfunctions.net/fnEcho
```

<details><summary>response</summary>

```json
{
  "request": {
    "domain": null,
    "headers": {
      "host": "us-central1-christiannaths-com.cloudfunctions.net",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36",
      "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en-US,en;q=0.9",
      "cache-control": "no-cache",
      "dnt": "1",
      "forwarded": "for=\"187.237.217.18\";proto=https",
      "function-execution-id": "zx1mppz9po8n",
      "pragma": "no-cache",
      "upgrade-insecure-requests": "1",
      "x-appengine-api-ticket": "[redacted]",
      "x-appengine-city": "[redacted]",
      "x-appengine-citylatlong": "[redacted]",
      "x-appengine-country": "[redacted]",
      "x-appengine-default-version-hostname": "[redacted]",
      "x-appengine-https": "[redacted]",
      "x-appengine-region": "[redacted]",
      "x-appengine-request-log-id": "[redacted]",
      "x-appengine-user-ip": "[redacted]",
      "x-cloud-trace-context": "[redacted]",
      "x-forwarded-for": "[redacted]",
      "x-forwarded-proto": "https",
      "connection": "close"
    },
    "url": "/",
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/",
    "params": {
      "0": ""
    }
  },
  "env": {
    "X_GOOGLE_FUNCTION_TIMEOUT_SEC": "60",
    "NO_UPDATE_NOTIFIER": "true",
    "X_GOOGLE_FUNCTION_MEMORY_MB": "256",
    "FUNCTION_TIMEOUT_SEC": "60",
    "FUNCTION_MEMORY_MB": "256",
    "X_GOOGLE_LOAD_ON_START": "false",
    "X_GOOGLE_FUNCTION_TRIGGER_TYPE": "HTTP_TRIGGER",
    "PORT": "8080",
    "ENTRY_POINT": "fnEcho",
    "HOME": "/tmp",
    "X_GOOGLE_SUPERVISOR_HOSTNAME": "169.254.8.129",
    "FUNCTION_TRIGGER_TYPE": "HTTP_TRIGGER",
    "X_GOOGLE_GCLOUD_PROJECT": "christiannaths-com",
    "X_GOOGLE_FUNCTION_NAME": "fnEcho",
    "FUNCTION_NAME": "fnEcho",
    "SUPERVISOR_INTERNAL_PORT": "8081",
    "X_GOOGLE_GCP_PROJECT": "christiannaths-com",
    "X_GOOGLE_FUNCTION_REGION": "us-central1",
    "X_GOOGLE_ENTRY_POINT": "fnEcho",
    "FUNCTION_REGION": "us-central1",
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "X_GOOGLE_WORKER_PORT": "8091",
    "CODE_LOCATION": "/srv",
    "WORKER_PORT": "8091",
    "SUPERVISOR_HOSTNAME": "169.254.8.129",
    "DEBIAN_FRONTEND": "noninteractive",
    "X_GOOGLE_FUNCTION_IDENTITY": "christiannaths-com@appspot.gserviceaccount.com",
    "X_GOOGLE_CONTAINER_LOGGING_ENABLED": "false",
    "GCLOUD_PROJECT": "christiannaths-com",
    "FUNCTION_IDENTITY": "christiannaths-com@appspot.gserviceaccount.com",
    "X_GOOGLE_CODE_LOCATION": "/srv",
    "PWD": "/srv",
    "GCP_PROJECT": "christiannaths-com",
    "X_GOOGLE_SUPERVISOR_INTERNAL_PORT": "8081",
    "X_GOOGLE_FUNCTION_VERSION": "1",
    "X_GOOGLE_NEW_FUNCTION_SIGNATURE": "true",
    "NODE_ENV": "production",
    "FIREBASE_CONFIG": "{\"projectId\":\"christiannaths-com\",\"databaseURL\":\"https://christiannaths-com.firebaseio.com\",\"storageBucket\":\"christiannaths-com.appspot.com\",\"cloudResourceLocation\":\"us-central\"}"
  }
}
```

</details>

### LINKED ISSUE #1320: verifyDeveloperNodeModules() does not properly detected uninstalled modules
### [REQUIRED] Environment info

firebase-tools: 6.10.0
Ubuntu 18.04.2 LTS

### [REQUIRED] Steps to reproduce

I just upgrade from `firebase-tools 6.8.0` to `6.10.0`
and when try to run `firebase serve --only functions,hosting`
I get this error
```
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at verifyDeveloperNodeModules (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:120:32)
    at /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:435:26
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:3:12)

```
### [REQUIRED] Expected behavior
It should run normally
**This is not happening with version `6.8.0`**

### [REQUIRED] Actual behavior
It throws an error

For now I just downgraded back to `6.8.0`

### LINKED ISSUE #1322: rawBody is empty when using the functions emulator
`req.rawBody` is not available when using the functions emulator. It is available to deployed functions.

### Environment info

**firebase-tools:** 6.10.0
**Platform:** Manjaro

### Test case

```
exports.test = functions.https.onRequest((req, res) => {
  res.send(req.rawBody);
})
```

### Steps to reproduce

Check returned function response with `curl`:
```
curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST https://app/test
```

If running the function with the functions emulator:
```
firebase emulators:start --only functions
```
POSTing to the function will return an empty response.

POSTing to the deployed function will return:
```
{"key1":"value1", "key2":"value2"}
```

### Expected behavior

When running the function in the emulator, `req.rawBody` should contain the raw request body.

### Actual behavior

`req.rawBody` is empty when using the emulator.

### Related issues:

* https://github.com/googlearchive/cloud-functions-emulator/issues/161
* https://github.com/googlearchive/cloud-functions-emulator/issues/167
* https://github.com/firebase/firebase-functions/issues/417

### LINKED ISSUE #1364: Add ability to detect when function code is running in emulator
We should add `FUNCTIONS_EMULATOR` so devs can easily change behavior for the emulator.

### PR DESCRIPTION
**Pull request by abeisgoat**
Many emulator fixes / improvements!

Fixes #1320
Fixes #1322 
Fixes #1364
Fixes #1312

### CODE REVIEW

File: src/emulator/functionsEmulator.ts [hunk 1]
```diff
@@ -169,7 +168,7 @@ export class FunctionsEmulator implements EmulatorInstance {
       const runtimeReq = http.request(
         {
           method,
-          path: "/" + trimFunctionPath(req.url),
+          path: req.url || "/",
```
Comment (samtstern) [inline src/emulator/functionsEmulator.ts]: This change was just made (by me) to fix a different bug.  Aren't we un-fixing it now?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 2]
```diff
@@ -55,7 +55,33 @@ function slowRequireResolve(moduleName: string, cwd?: string): string {
...
 
-  return result.stdout.toString().trim();
+  const resolution = result.stdout.toString().trim();
+  if (resolution === "") {
+    throw new Error(`Could not resolve module "${moduleName}"`);
+  }
+  return resolution;
+}
+
+const cachedResolutions: { [id: string]: any } = {};
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: should this be `CachedModuleMetadata` not `any`?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 3]
```diff
@@ -55,7 +55,33 @@ function slowRequireResolve(moduleName: string, cwd?: string): string {
...
+interface CachedModuleMetadata {
+  path?: any;
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Isn't this `path?: string` ?

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Nit: put this global state higher up in the file, above all function definitions with the other fields.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 4]
```diff
@@ -172,7 +198,7 @@ function verifyDeveloperNodeModules(frb: FunctionsRuntimeBundle): boolean {
   }
 
   const modBundles = [
-    { name: "firebase-admin", isDev: false, minVersion: 7 },
+    { name: "firebase-admin", isDev: false, minVersion: 8 },
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Do we have to drop support for `firebase-admin` 7?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 5]
```diff
@@ -312,16 +315,7 @@ function InitializeNetworkFiltering(frb: FunctionsRuntimeBundle): void {
       try {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: This `try` and `catch` are the same ... that can't be right.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 6]
```diff
@@ -384,9 +381,9 @@ function InitializeFirebaseFunctionsStubs(functionsDir: string): void {
     failing in some way and admin is attempting to access prod resources. This error isn't pretty,
     but it's hard to catch and better than accidentally talking to prod.
    */
-function InitializeFirebaseAdminStubs(frb: FunctionsRuntimeBundle): typeof admin {
-  const adminResolution = slowRequireResolve("firebase-admin", frb.cwd);
-  const grpc = require(slowRequireResolve("grpc", frb.cwd));
+async function InitializeFirebaseAdminStubs(frb: FunctionsRuntimeBundle): Promise<typeof admin> {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: One day I will be a big boi who knows JavaScript and will understand this `typeof` thing.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 7]
```diff
@@ -545,13 +556,17 @@ async function ProcessHTTPS(frb: FunctionsRuntimeBundle, trigger: EmulatedTrigge
...
-    ephemeralServer.use(bodyParser.raw({ type: "*/*" }));
+    functionRouter.use(bodyParser.json({ verify: rawBodySaver }));
+    functionRouter.use(bodyParser.text({ verify: rawBodySaver }));
+    functionRouter.use(bodyParser.urlencoded({ extended: true, verify: rawBodySaver }));
+    functionRouter.use(bodyParser.raw({ type: "*/*", verify: rawBodySaver }));
 
-    ephemeralServer.all("/*", handler);
+    functionRouter.all("*", handler);
 
+    ephemeralServer.use(
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: I think the '/*' is better, since it guarantees we don't drop anyone's express subpaths.  This server is short-lived and created by us so we don't need to worry about path abuse.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 4 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: Hopefully we can support both. I'll see.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 5 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: False. One is `return original()` and one is `return new original()`

File: src/emulator/functionsEmulator.ts (hunk 1 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulator.ts]: False. Your fix allowed `req.path` to equal the last chunks of the path, dropping the `trigger_id`, `project_id` and `region`. In order to provide this information into the function runtime (and eventually `req.baseUrl` and `req.mountpoint`) we need to preserve this data and allow the runtime to do the split. The new system (implemented near `ephemeralApp`) uses a sub-router which automatically slices the path for us and sets `req.baseUrl` so we don't need this hack since the router takes care of it.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 2 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: True.

Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: True

File: src/emulator/functionsEmulatorRuntime.ts (hunk 3 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: True

File: src/emulator/functionsEmulator.ts (hunk 1 above)
Comment (samtstern) [reply src/emulator/functionsEmulator.ts]: Specifically that was fixed here:
https://github.com/firebase/firebase-tools/pull/1332

File: src/emulator/functionsEmulatorRuntime.ts (hunk 6 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: False.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 7 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: False (I think?). I believe the actual functionality in production is that a request to `blah.cloudfunctions.net/myFunc` should work. I believe including the `/` will break this, but we should verify, Also I have no idea what you mean by path abuse.

File: src/emulator/functionsEmulator.ts (hunk 1 above)
Comment (samtstern) [reply src/emulator/functionsEmulator.ts]: OK you'll need to hand-hold me here.  What will they see if they run a function like this:
```js
exports.httpFn = functions.https.onRequest((request, response) => {
    response.send({
        method: request.method,
        path: request.path, 
        query: request.query 
    });
});
```

As of #1332 it matches prod, will that change?

File: src/emulator/functionsEmulatorRuntime.ts (hunk 4 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: So True or False?

File: src/emulator/functionsEmulatorRuntime.ts (hunk 7 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: I mean since we are the only caller we don't need to worry about anyone else hitting this server at a path we can't support.  So supporting `/*` is not opening ourselves up to any trouble.

File: src/emulator/functionsEmulator.ts (hunk 1 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulator.ts]: It will still match prod, as defined by [this test](https://github.com/firebase/firebase-tools/blob/master/src/test/emulators/functionsEmulator.spec.ts#L57). Please examine [`functionsEmulatorRuntime.ts#566`](https://github.com/firebase/firebase-tools/blob/ah-speedhax/src/emulator/functionsEmulatorRuntime.ts#L566) where we provide the new router. The chunks matched in the array passed to `use` will be dropped when the sub-router is called, the result should be the same as what you implemented, but now with `baseUrl` and `mountpoint` provided to the developer.

Comment (samtstern) [reply src/emulator/functionsEmulator.ts]: Ok now I get it, thanks!

File: src/emulator/functionsEmulatorRuntime.ts (hunk 7 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Just to be clear, in prod these all route to the same function:
```
blah.cloudfunctions.net/myFunc
blah.cloudfunctions.net/myFunc/foo
blah.cloudfunctions.net/myFunc/foo/bar
```

They all go to `myFunc`.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 4 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: I responded to this before I decided to start being a jerk, so no True / False decision yet lol. I'll give you a boolean answer once I look into it haha.

File: package.json [hunk 8]
```diff
@@ -134,7 +134,7 @@
     "coveralls": "^3.0.1",
     "eslint": "^5.7.0",
     "eslint-plugin-prettier": "^3.0.0",
-    "firebase-admin": "^7.3.0",
+    "firebase-admin": "^8.0.0",
```
Comment (bkendall) [inline package.json]: `firebase-admin@8` does not support Node 6. (This should not be merged in for a `firebase-tools@6.x.y` release)

(Really making this note so I don't forget about it - I see y'all are working on a fix for this already)

Comment (abeisgoat) [reply package.json]: Yeah these changes are intended for firebase-tools@7

File: src/emulator/functionsEmulatorRuntime.ts (hunk 7 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: I just added [some tests](https://github.com/firebase/firebase-tools/pull/1366/commits/94cf934fcb46be207789a383b2db04d50a6ee534) to describe this, can you verify that these are(n't) correct?

File: src/test/emulators/functionsEmulator.spec.ts [hunk 9]
```diff
@@ -54,6 +54,50 @@ describe("FunctionsEmulator-Hub", () => {
       });
   }).timeout(TIMEOUT_LONG);
 
+  it("should route requests to /:project_id/:region/:trigger_id/ to HTTPS Function", async () => {
+    UseFunctions(() => {
+      require("firebase-admin").initializeApp();
+      return {
+        function_id: require("firebase-functions").https.onRequest(
+          (req: express.Request, res: express.Response) => {
+            res.json({ hello: "world" });
```
Comment (samtstern) [inline src/test/emulators/functionsEmulator.spec.ts]: In these two tests instead of hello world let's return:
```
res.json({ path: req.path })
```

And then assert that the function gets the `path` value we expect.  So `/` in this case and ``/a/b` in the next.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 7 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Commented over there.

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 10]
```diff
@@ -355,7 +356,7 @@ describe("FunctionsEmulator-Runtime", () => {
           request(
             {
               socketPath: runtime.metadata.socketPath,
-              path: "/",
+              path: `/${frb.projectId}/${frb.triggerId}/`,
```
Comment (samtstern) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: Where's the region (here and in all cases)?

File: src/test/emulators/functionsEmulator.spec.ts [hunk 11]
```diff
@@ -54,7 +54,51 @@ describe("FunctionsEmulator-Hub", () => {
...
+          }
+        ),
+      };
+    });
+
+    await supertest(
```
Comment (samtstern) [inline src/test/emulators/functionsEmulator.spec.ts]: Not your fault but while you're in here could we have tests to make sure that:

  * The HTTP method is preserved
  * Query params are preserved

File: src/test/emulators/functionsEmulatorRuntime.spec.ts (hunk 10 above)
Comment (abeisgoat) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: Are we not supposed to support region-less paths?

Comment (samtstern) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: No I don't think we do/should.

File: src/test/emulators/functionsEmulator.spec.ts (hunk 11 above)
Comment (abeisgoat) [reply src/test/emulators/functionsEmulator.spec.ts]: We already have a test for query params, do you think we need to check that in every test?

Comment (samtstern) [reply src/test/emulators/functionsEmulator.spec.ts]: Whoops sorry didn't know we already had that test.

Comment (samtstern) [reply src/test/emulators/functionsEmulator.spec.ts]: Was it failing back when we were dropping query params?  Because that's a pretty recent fix.

Comment (abeisgoat) [reply src/test/emulators/functionsEmulator.spec.ts]: I believe the test was added after that fix so we should be good.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 4 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: 7 support has been restored.

**Comment by abeisgoat** [comment]
Alright, @samtstern if you can give me another pass, we should be pretty much gucci to go

File: src/emulator/functionsEmulatorRuntime.ts [hunk 12]
```diff
@@ -12,52 +12,53 @@ import {
...
-function slowRequireResolve(moduleName: string, cwd?: string): string {
-  const resolver = `console.log(require.resolve("${moduleName}"))`;
-  const result = spawnSync(process.execPath, ["-e", resolver], {
-    cwd: path.resolve(cwd || process.cwd()),
-  });
+interface CachedModuleMetadata {
+  path: string;
+  resolved?: boolean;
+}
+const cachedResolutions: { [id: string]: CachedModuleMetadata } = {};
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: super small nit: newlines between definitions:

```
interface Foo {

} 

const bar

async function
```

File: src/emulator/functionsEmulatorRuntime.ts [hunk 13]
```diff
@@ -12,52 +12,53 @@ import {
...
+      meta.resolved = false;
+    }
+    cachedResolutions[id] = meta;
+  }
 
-  return result.stdout.toString().trim();
+  return cachedResolutions[id];
 }
 
+const isFeatureEnabled = (frb: FunctionsRuntimeBundle, feature: keyof FunctionsRuntimeFeatures) =>
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: Is there a reason these functions are defined as `const name = implementation` and not `function name() { }`?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 14]
```diff
@@ -12,52 +12,53 @@ import {
...
-  const resolver = `console.log(require.resolve("${moduleName}"))`;
-  const result = spawnSync(process.execPath, ["-e", resolver], {
-    cwd: path.resolve(cwd || process.cwd()),
-  });
+interface CachedModuleMetadata {
+  path: string;
+  resolved?: boolean;
+}
+const cachedResolutions: { [id: string]: CachedModuleMetadata } = {};
+async function cachedRequireResolve(
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: What makes this function `async`?  I don't see it using `await` anywhere or any promises within it.

If it's *not* actually `async` then you can un-change all the downstream callers to be normal functions again.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 15]
```diff
@@ -638,11 +678,31 @@ async function RunHTTPS(
...
+  This method attempts to help a developer whose code can't be loaded by suggesting
+  possible fixes based on the files in their functions directory.
+ */
+async function moduleResolutionDetective(frb: FunctionsRuntimeBundle): Promise<void> {
+  /*
+  These files could all potentially exist, if they don't then the value in the map will be
+  falsey, so we just catch to keep from throwing.
+   */
+  const clues = {
+    tsconfigJSON: await requireAsync("./tsconfig.json", { paths: [frb.cwd] }).catch(NoOp),
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: why `await requireAsync` instead of just `require`?

File: src/test/emulators/functionsEmulatorRuntime.spec.ts [hunk 16]
```diff
@@ -221,7 +221,7 @@ describe("FunctionsEmulator-Runtime", () => {
           request(
             {
               socketPath: runtime.metadata.socketPath,
-              path: "/",
+              path: `/${onRequestCopy.projectId}/us-central-1f/${onRequestCopy.triggerId}`,
```
Comment (samtstern) [inline src/test/emulators/functionsEmulatorRuntime.spec.ts]: Uh you're using `1f` all over the place but that's not a valid region.  I think it's `us-central-1a`

**Comment by samtstern** [comment]
@abeisgoat this should target the `next` branch, right?

File: src/test/emulators/functionsEmulatorRuntime.spec.ts (hunk 16 above)
Comment (abeisgoat) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: Damnit.

Comment (ryanpbrewster) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: the GCP zone is `us-central1-f`

Comment (abeisgoat) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: Okay so I was close.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 13 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: Yeah, I wanted to distinguish these 1-line utility methods (lines 50-60), but I guess there isn't really a reason, I just liked how they look.

File: src/test/emulators/functionsEmulatorRuntime.spec.ts (hunk 16 above)
Comment (samtstern) [reply src/test/emulators/functionsEmulatorRuntime.spec.ts]: So region is `us-central1`  I was way off

File: src/emulator/functionsEmulatorRuntime.ts (hunk 13 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Things without brackets give me nightmares.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 14 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: There's a reason, but this entire method is trash and I'll just get rid of it.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 15 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: So in this case (and with the newly added `requireResolveAsync`) the value of being `async` is in cleanliness of control flow - it is not required because these operations are not async, but it helps when dealing with synchronous methods which may throw (like `require`). By wrapping these native methods in `async` functions then catching with a `NoOp`, we gain the ability to write one-liners which catch thrown errors and just end up `false`-y 

So this snippet, if it didn't use the Promise-ified version would be this...

```js
const clues: {[s: key]: any} = {};

try {
  clues["tsconfigJSON"] = require("./tsconfig.json", { paths: [frb.cwd] });
} catch (err) {
  // Optional explicit set to false since default value of undefined is false-y
  clues["tsconfigJSON"] = false;
};

try {
  clues["packageJSON"] = require("./package.json", { paths: [frb.cwd] });
} catch (err) {
  clues["packageJSON"] = false;
};
```

As opposed to the `async`d version

```js
const clues = {
    tsconfigJSON: await requireAsync("./tsconfig.json", { paths: [frb.cwd] }).catch(NoOp),
    packageJSON: await requireAsync("./package.json", { paths: [frb.cwd] }).catch(NoOp),
}
```

In either case, the clue value will be either an `any` from the `require` call or `false`.

We've shifted to this flow all over the place because we're constantly doing requires and resolutions which may fail but aren't really fatal.

**Comment by abeisgoat** [comment]
Uhm, maybe? @bkendall can you confirm this should still go into `next`?

File: src/emulator/functionsEmulatorRuntime.ts [hunk 17]
```diff
@@ -372,6 +359,31 @@ function InitializeFirebaseFunctionsStubs(functionsDir: string): void {
   };
 }
 
+/*
+  @google-cloud/firestore@2.0.0 made a breaking change which swapped relying on "grpc" to "@grpc/grpc-js"
+  which has a slightly different signature. We need to detect the firestore version to know which version
+  of grpc to pass as a credential.
+ */
+async function getGRPCInsecureCredential(frb: FunctionsRuntimeBundle): Promise<any> {
```
Comment (samtstern) [inline src/emulator/functionsEmulatorRuntime.ts]: So just FYI `@google-cloud/firestore` version `2.2.0` came out today which allows the `ssl: false` flag instead of passing in your own gRPC credential.

So if you detect that library, you can skip knowing about any gRPC at all.

Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: https://github.com/googleapis/nodejs-firestore/releases/tag/v2.2.0

Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: So yeah, I was thinking about this, but it really doesn't help that much until we drop `firebase-admin@7` because we'll still have to route differently based on version, ya know. Once we drop 7 we'll be able to only support `@google-cloud/firestore>=2.20` then life'll be more buttery.

Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: @abeisgoat true just good to know where we are headed.

Even better: the NodeJS Admin SDK now respects `FIRESTORE_EMULATOR_HOST` so we could *entirely avoid* monkey-patching the `initalizeApp()` call and just set up the environment and let the SDK handle it.

That would remove a huge amount of complexity for us.

File: package.json [hunk 18]
```diff
@@ -134,9 +134,8 @@
     "coveralls": "^3.0.1",
     "eslint": "^5.7.0",
     "eslint-plugin-prettier": "^3.0.0",
-    "firebase-admin": "^7.3.0",
+    "firebase-admin": "^7.0.0",
```
Comment (bkendall) [inline package.json]: It probably doesn't matter (as this is a dev dependency), but why downgrade?

Comment (abeisgoat) [reply package.json]: Just for completeness, we only check major version in functions runtime. It shouldn't matter, it was only `7.3.0` because that's what npm added.

File: src/emulator/functionsEmulatorRuntime.ts (hunk 17 above)
Comment (abeisgoat) [reply src/emulator/functionsEmulatorRuntime.ts]: agreed, that would be wonderful, but it'll be awhile before we have enough adoption to actually remove the old code. We'll just sit back and wait.

File: changelog.txt [hunk 19]
```diff
@@ -1,2 +1,6 @@
+* Fixed bug where raw body was missing on HTTPS function request
```
Comment (bkendall) [inline changelog.txt]: Can you add periods to each of these as they are full and complete sentences?

File: changelog.txt [hunk 20]
```diff
@@ -1,2 +1,6 @@
...
+* Fixed bug with Functions Emulator and firebase-admin@8.0.0
```
Comment (bkendall) [inline changelog.txt]: This fixes a bug with `firebase-admin@8.0.0`, but it's still fine with everything else, right (including node 6)?

I don't know why this caught my eye the second time

Comment (abeisgoat) [reply changelog.txt]: Good catch, this will subtly break 6 so I've changed this to merge into `next`
