### PR TITLE
fix #1774

### LINKED ISSUE #1774: "]0;Firebase CLI" is automatically added to .runtimeconfig.json
### [REQUIRED] Environment info

**firebase-tools: 7.6.2**

**Platform: MacOS Catalina**

### [REQUIRED] Steps to reproduce

After I set custom key:value in firebaseconfig.json using below command

```
firebase functions:config:set app.api_key=abcde12345
```

and run the command to update runtimeconfig 

```
firebase functions:config:get > .runtimeconfig.json
```

and in my actual runtimeconfig.json file, I see this line `1]0;Firebase CLI` added on top of json.
 
```JSON
]0;Firebase CLI{
  "a": {
    "id": {
      "seg": "abcde"
    },
    "api_key": "abcde"
}
```
### [REQUIRED] Expected behavior

I haven't seen this bug, until I set up `export GOOGLE_APPLICATION_CREDENTIALS=[path/json]`

### [REQUIRED] Actual behavior

This is what I see.

```JSON
]0;Firebase CLI{
  "a": {
    "id": {
      "seg": "abcde"
    },
    "api_key": "abcde"
}
```

### PR DESCRIPTION
**Pull request by kenju**
https://github.com/firebase/firebase-tools/issues/1774

### Description

"]0;Firebase CLI" is still appended by fireprit.js
when `config.template.js`'s `headless` value is `false`
which is dynamically set by `pipeline.js`.

Some environment still print `]0;Firebase CLI` in the ahead of stdout.

For example, if you print out:

    firebase functions:config:get > config.json

The created `config.json` becomes invalid JSON.

### CODE REVIEW

**Comment by samtstern** [comment]
@kenju thanks for the PR!  

@abeisgoat is there something we can do to only print this out in the right situations?

**Comment by kenju** [comment]
@samtstern Thank you for looking into this PR.

@abeisgoat Could I get a review on this PR, please? This behavior is blocking us from creating an automated deployment script (we require HACK for trimming this chars from JSON files...)

File: standalone/firepit.js [hunk 1]
```diff
@@ -972,19 +971,6 @@ function FindTool(bin) {
...
 }
 
-function SetWindowTitle(title) {
-  /*
-    This method *attempts* to set the terminal window title to something pretty so it doesn't
-    show the internal shell'ing we do. It kinda works, but fails silently, so I've left it in.
-   */
-  if (isWindows) {
-    process.title = title;
-  } else {
```
Comment (samtstern) [inline standalone/firepit.js:982]: Can we actually leave the `isWindows` branch of this code (which causes no problems) and remove the `else` branch?

**Comment by samtstern** [comment]
@kenju sorry for the delay here!  Didn't realise Abe was on vacation.  Just need a small change and we should be ready to merge, also please add an entry to `CHANGELOG.md`!

File: standalone/firepit.js (hunk 1 above)
Comment (kenju) [reply standalone/firepit.js:982]: Sure ♻️ https://github.com/firebase/firebase-tools/pull/2330/commits

**Comment by kenju** [comment]
> sorry for the delay here! Didn't realise Abe was on vacation. Just need a small change and we should be ready to merge, also please add an entry to CHANGELOG.md!

@samtstern Thank you very much for looking into this PR! No problem 👍 

I've updated the CHANGELOG.md as well https://github.com/firebase/firebase-tools/pull/2330/commits

Could I get a review on this PR again, please?
