### PR TITLE
Integration with firebase-functions 3.3.0

### LINKED ISSUE #1682: Firebase Emulator error when writing/updating document inside a Firestore trigger, when using snapshot.ref.set()
### [REQUIRED] Environment info

**firebase-tools:**
7.4.0

**Platform:**
Windows

### [REQUIRED] Test case

Since auth is not available in the context for Firestore triggers, I send along some user data in the snapshot to log the activity and use the user token to create some extra steps inside the onCreate function. I extract the userdata from the snapshot and the want to remove the userdata using the snapshot.ref.set(snapShotWithoutUserData)

### [REQUIRED] Steps to reproduce

```
export const onOrganizerCreate = functions.firestore.document("organizers/{organizerId}")
.onCreate((snapshot, context) => {
  return snapshot.ref.set({
    test: "testing"
  }, { merge: true });
})
```

I have tried ref.set(), ref.update() with or without the merge parameter, same result

### [REQUIRED] Expected behavior

Expect it to run without errors as it does when i deploy it.

### [REQUIRED] Actual behavior

The emulator/trigger crashes, giving this error

### **If i deploy the same code and run it without the emulator, it works just fine. Or if i use the firebase-admin to do the same task by building the path using the context params, it also works**

!  Non-default "firebase-admin" instance created!
   - This instance will *not* be mocked and will access production resources.
!  Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
!  functions: Error: Getting metadata from plugin failed with error: invalid_grant
    at Http2CallStream.call.on (C:\Development\<projectId>\functions\node_modules\@grpc\grpc-js\build\src\client.js:96:45)
    at Http2CallStream.emit (events.js:194:15)
    at Http2CallStream.EventEmitter.emit (domain.js:441:20)
    at process.nextTick (C:\Development\<projectId>\functions\node_modules\@grpc\grpc-js\build\src\call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
!  Your function was killed because it raised an unhandled error.
(node:13324) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are 
sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\ralcar\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\expressginated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

### PR DESCRIPTION
**Pull request by samtstern**
### Description

Fixes #1682 

If the developer is using `firebase-functions@3.3.0` or later we can now override the internal FirebaseApp.  If they are not we log a one-time warning.

I added the concept of `WARN_ONCE` for warnings we only want to log once per session, not ocne per functions execution.
	 
### Scenarios Tested

I am using these function:
```js
const functions = require("firebase-functions");
const admin = require("firebase-admin");
admin.initializeApp();

exports.triggerFirestoreFn = functions.https.onRequest(async (req, res) => {
  await admin.firestore().doc('/foo/bar').set({
    date: new Date()
  });

  res.json({ ok: true });
})

exports.firestoreFn = functions.firestore.document('/foo/bar').onWrite(async (change, ctx) => {
  const ref = change.after.ref;
  console.log(JSON.stringify(ref.firestore._settings));
  return true;
})
```

If the user has `3.2.0`:

  * The warning is displayed.
  * The ref clearly points to prod (BAD).

```
$ npx firebase emulators:exec "http http://localhost:5001/fir-dumpster/us-central1/triggerFirestoreFn"
i  Starting emulators: ["functions","firestore"]
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://localhost:5001
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: Emulator logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  functions: Watching "/tmp/tmp.rVfBbr6iiZ/functions" for Cloud Functions...
⚠  functions: You're using firebase-functions v3.2.0. Please upgrade to firebase-functions v3.3.0 or higher to benefit from the latest emulator integration.
✔  functions[triggerFirestoreFn]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/triggerFirestoreFn).
✔  functions[firestoreFn]: firestore function initialized.
i  Running script: http http://localhost:5001/fir-dumpster/us-central1/triggerFirestoreFn
i  functions: Beginning execution of "triggerFirestoreFn"
i  functions: Finished "triggerFirestoreFn" in ~1s
HTTP/1.1 200 OK
connection: keep-alive
content-length: 11
content-type: application/json; charset=utf-8
date: Thu, 10 Oct 2019 23:00:50 GMT
etag: W/"b-Ai2R8hgEarLmHKwesT1qcY913ys"
x-powered-by: Express

{
    "ok": true
}

✔  Script exited successfully (code 0)
i  functions: Beginning execution of "firestoreFn"
>  {"projectId":"fir-dumpster","firebaseVersion":"8.6.0","libName":"gccl","libVersion":"2.4.0 fire/8.6.0"}
i  functions: Finished "firestoreFn" in ~1s
i  Shutting down emulators.
i  Stopping functions emulator
i  Stopping firestore emulator
```

If the user has `3.3.0`:

  * The warning is not displayed.
  * The ref clearly points to the local emulator (GOOD).
 
```
$ npx firebase emulators:exec "http http://localhost:5001/fir-dumpster/us-central1/triggerFirestoreFn"
i  Starting emulators: ["functions","firestore"]
✔  functions: Using node@8 from host.
✔  functions: Emulator started at http://localhost:5001
i  firestore: Serving ALL traffic (including WebChannel) on http://localhost:8080
⚠  firestore: Support for WebChannel on a separate port (8081) is DEPRECATED and will go away soon. Please use port above instead.
i  firestore: Emulator logging to firestore-debug.log
✔  firestore: Emulator started at http://localhost:8080
i  firestore: For testing set FIRESTORE_EMULATOR_HOST=localhost:8080
i  functions: Watching "/tmp/tmp.rVfBbr6iiZ/functions" for Cloud Functions...
✔  functions[triggerFirestoreFn]: http function initialized (http://localhost:5001/fir-dumpster/us-central1/triggerFirestoreFn).
✔  functions[firestoreFn]: firestore function initialized.
i  Running script: http http://localhost:5001/fir-dumpster/us-central1/triggerFirestoreFn
i  functions: Beginning execution of "triggerFirestoreFn"
HTTP/1.1 200 OK
connection: keep-alive
content-length: 11
content-type: application/json; charset=utf-8
date: Thu, 10 Oct 2019 23:01:25 GMT
etag: W/"b-Ai2R8hgEarLmHKwesT1qcY913ys"
x-powered-by: Express

{
    "ok": true
}

i  functions: Finished "triggerFirestoreFn" in ~1s
✔  Script exited successfully (code 0)
i  functions: Beginning execution of "firestoreFn"
>  {"projectId":"fir-dumpster","firebaseVersion":"8.6.0","libName":"gccl","libVersion":"2.4.0 fire/8.6.0","port":8080,"servicePath":"localhost","service":"firestore.googleapis.com","sslCreds":{"callCredentials":{}},"customHeaders":{"Authorization":"Bearer owner"}}
i  functions: Finished "firestoreFn" in ~1s
i  Shutting down emulators.
i  Stopping functions emulator
i  Stopping firestore emulator
```

### Sample Commands

N/A

### CODE REVIEW

File: src/emulator/functionsEmulatorRuntime.ts [hunk 1]
```diff
@@ -558,6 +578,21 @@ async function InitializeFirebaseAdminStubs(frb: FunctionsRuntimeBundle): Promis
       databaseApp = adminModuleTarget.initializeApp(databaseAppOptions, DATABASE_APP);
       proxiedDatabase = makeProxiedDatabase(adminModuleTarget);
 
+      // Tell the Firebase Functions SDK to use the proxied app so that things like "change.after.ref"
+      // point to the right place.
+      const functionsVersion = parseVersionString(functionsResolution.version);
+      if (functionsVersion.major >= 3 && functionsVersion.minor >= 3) {
```
Comment (yuchenshi) [inline src/emulator/functionsEmulatorRuntime.ts]: The current check will fail for `4.1` (since minor is less than 3). Please consider using feature detection like `if (localFunctionsModel.app.setEmulatedAdminApp)` instead of checking version.

File: src/emulator/emulatorLogger.ts [hunk 2]
```diff
@@ -27,6 +29,7 @@ export enum Verbosity {
 
 export class EmulatorLogger {
   static verbosity: Verbosity = Verbosity.DEBUG;
+  static warnOnceCache: { [text: string]: boolean } = {};
```
[the remark this answers is not in the document]
Comment (samtstern) [reply src/emulator/emulatorLogger.ts]: :+1:

File: src/emulator/functionsEmulatorRuntime.ts (hunk 1 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Good call.

File: src/emulator/functionsEmulatorRuntime.ts [hunk 3]
```diff
@@ -246,10 +248,26 @@ async function resolveDeveloperNodeModule(
...
+  const resolution = await resolveDeveloperNodeModule(frb, name);
+  if (
+    !(resolution.installed && resolution.declared && resolution.resolution && resolution.version)
+  ) {
+    throw new Error(
+      `Assertion failure: could not fully resolve ${name}: ${JSON.stringify(resolution)}`
+    );
+  }
+
+  return resolution as SuccessfulModuleResolution;
```
Comment (bkendall) [inline src/emulator/functionsEmulatorRuntime.ts]: out of curiosity, if you've checked that all these things exist (above), is `as SuccessfulModuleResolution` required still? (I imagine it is if you still have it here, but that's interesting...)

File: src/emulator/functionsEmulatorUtils.ts [hunk 4]
```diff
@@ -63,3 +72,47 @@ export function removePathSegments(path: string, count: number): string {
...
+  if (versionA.minor != versionB.minor) {
+    return versionA.minor - versionB.minor;
+  }
+
+  if (versionA.patch != versionB.patch) {
+    return versionA.patch - versionB.patch;
+  }
+
+  return 0;
+}
```
Comment (bkendall) [inline src/emulator/functionsEmulatorUtils.ts]: I feel like you might be reinventing the wheel here a bit. [semver](https://www.npmjs.com/package/semver) should do this for you, and it's already in the repo!

Comment (bkendall) [reply src/emulator/functionsEmulatorUtils.ts]: (ohh, but I see the note at the top of the file now... hmmm.... your choice.)

File: src/emulator/functionsEmulatorRuntime.ts (hunk 3 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorRuntime.ts]: Yeah it is.  Something about type boolean and type true ?

File: src/emulator/functionsEmulatorUtils.ts (hunk 4 above)
Comment (samtstern) [reply src/emulator/functionsEmulatorUtils.ts]: We can't import `semver` into the runtime so the wheel reinvention is on purpose.
