### PR TITLE
Validate indexes during preparation.

### LINKED ISSUE #495: Firestore indexes issue - when empty
When my `firestore.indexes.json` is empty like so:
```
{
  "indexes": [
    {
    }
  ]
}

```
I'm getting an error on `firebase deploy`
`Error: An unexpected error has occurred.`
The content of my `firebase-debug.log` contains:
```
[debug] [2017-10-05T23:13:59.475Z] TypeError: Cannot read property 'length' of undefined
    at Object.hash (/Users/rootux/.nvm/versions/node/v8.1.2/lib/node_modules/firebase-tools/lib/firestore/indexes.js:158:35)
```
I would expect a better error message or just accepting of this empty file

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #495

### CODE REVIEW

File: lib/firestore/indexes.js [hunk 1]
```diff
@@ -182,6 +182,15 @@ var prepare = function(context, options) {
   var indexesPath = options.config.path(indexesFileName);
   var parsedSrc = loadCJSON(indexesPath);
 
+  if (!parsedSrc.indexes) {
+    throw new FirebaseError('Indexes file must contain "indexes" property: ' + indexesPath);
+  }
+
+  var indexes = parsedSrc.indexes;
+  for (var i = 0; i < indexes.length; i++) {
```
Comment (mbleigh) [inline lib/firestore/indexes.js]: Prefer

```js
parsedSrc.indexes.forEach(function(index) {
  _validate(index);
});
```
